MERGE INTO DDWH02_DM_MA.TDIM_VEHI_VEHICLE TRG USING
  (SELECT VEHI_CD_PLANT_CD,
          VEHI_ID_VEHI_VEHICLE,
          VEHI_CD_VAN,
          VEHI_CD_VIN,
          VEHI_CD_PLANT_ORD,
          VEHI_CD_PLANT_ORD_VAN,
          VEHI_CD_SRC_ORD,
          VEHI_CD_SRC_TP,
          VEHI_CD_CTRY_CD,
          VEHI_CD_LEGACY_MARKET,
          VEHI_CD_CUST_CD,
          VEHI_CD_MFG_MOD_CD,
          VEHI_CD_COMM_MOD_CD,
          VEHI_CD_BRAND_CD,
          VEHI_CD_PROD_FAM,
          VEHI_DS_PROD_FAM_DESC,
          VEHI_CD_MRP_CTRL_CD,
          VEHI_DS_MRP_CTRL_DESC,
          VEHI_CD_TECH_TP,
          VEHI_CD_MOD_PLN_KEY,
          VEHI_CD_MOD_VERSION,
          VEHI_CD_PRICE_BOOK,
          VEHI_CD_SERIE,
          VEHI_CD_SERIE_DESCRIPTION,
          VEHI_CD_MRP_SERIE,
          VEHI_CD_PROD_LINE,
          VEHI_CD_ENGINE_NBR,
          VEHI_CD_ENGINE_ITM,
          VEHI_CD_ENGINE_TP,
          VEHI_CD_ENGINE_FLEX_NBR,
          VEHI_DT_ENGINE_PROD_DT,
          VEHI_NR_SEQ_NBR,
          VEHI_DT_REQ_DLVR_DT,
          VEHI_DT_NEW_REQ_DLVR_DT,
          VEHI_DT_PLND_INLINE_DT,
          VEHI_DT_INLINE_DT,
          VEHI_DT_PLND_OFFLINE_DT,
          VEHI_DT_OFFLINE_DT,
          VEHI_FL_SCHED_UNIT_MARK,
          VEHI_DT_EST_FAI_OK_DT,
          VEHI_DT_ORG_EXPC_SHIP_DT,
          VEHI_DT_UPDT_EXPC_SHIP_DT,
          VEHI_DT_EXPC_FAI_OK_DT,
          VEHI_DT_FAI_OK_DT,
          VEHI_CD_VEHICLE_PRO_STU,
          VEHI_DS_VEHICLE_PRO_STU_DESC,
          VEHI_FL_AVAILABLE_MARK,
          VEHI_LD_PRODUCTION_REMARK,
          VEHI_DS_DISTR_REMARK,
          VEHI_DS_PARK_LOCATION,
          VEHI_LD_GENERAL_REMARK,
          VEHI_NR_NBR_REBUILD,
          VEHI_CD_LAST_ORD,
          VEHI_DT_LAST_ORD_STR_DT,
          VEHI_DT_LAST_ORD_END_DT,
          VEHI_CD_SEC_LAST_ORD,
          VEHI_DT_SEC_LAST_ORD_STR_DT,
          VEHI_DT_SEC_LAST_ORD_END_DT,
          VEHI_CD_LAST_RWK_ORD,
          VEHI_DT_LAST_RWK_ORD_STR_DT,
          VEHI_DT_LAST_RWK_ORD_END_DT,
          VEHI_AM_VEHICLE_VAL,
          VEHI_CD_MIGR_STATUS,
          VEHI_CD_VEHICLE_USAGE,
          VEHI_DT_VIN_ASSIGN_DT,
          VEHI_FL_VIN_ASSIGN_MARK,
          VEHI_NR_SERIE_ORD_SEQ,
          CASE
              WHEN VEHI_DT_FAI_OK_DT IS NOT NULL THEN 'FAI-OK'
              WHEN VEHI_DT_OFFLINE_DT IS NOT NULL THEN 'FLEET'
              WHEN VEHI_DT_INLINE_DT IS NOT NULL THEN 'INLINE'
              WHEN VEHI_DT_PLND_INLINE_DT IS NOT NULL THEN 'PLANNED'
              ELSE NOT_APPL
          END AS VEHI_CD_PROD_STU,
          VEHI_CD_PROD_ORD_STU,
          VEHI_LD_PROD_ORD_STU_DESC,
          VEHI_DT_LAST_BS_CREAT_DT,
          VEHI_CD_STATIC_VIN,
          VEHI_DT_INTERCOMP_INV_DT,
          VEHI_DT_SHIPM_DT,
          VEHI_DT_OK_HEADER_DT,
          VEHI_DT_OK_WHEELS_DT,
          VEHI_DT_OK_ACCESS_DT,
          VEHI_CD_DEAL_ORD_NBR,
          VEHI_DT_DEAL_ORD_DT,
          VEHI_CD_ASS_REQ_NBR,
          VEHI_DT_OK_DESPATCH_DT,
          VEHI_CD_DRAFT_NUMBER,
          VEHI_DT_CONF_PICK_UP_DT,
          VEHI_CD_LEGACY_MARKET_PALS,
          VEHI_DT_CALL_OFF_DT,
          VEHI_DT_BOAT_SHIPM_DUE_DT,
          VEHI_DT_OK_MACH_DT,
          VEHI_CD_ORD_STU,
          VEHI_CD_BRAND_CD_PALS,
          VEHI_DT_ASS_REQ_DT,
          VEHI_CD_LOAD_DOCK,
          VEHI_CD_COMM_DLVR_TERM_CD,
          VEHI_ID_BATCH_ID,
          VEHI_CD_SOURCE_SYSTEM,
          CONTROL_FIELD
   FROM
     (SELECT TM_VHMD_VEHICLE_MASTER.VHMD_CD_PLANT_CD AS VEHI_CD_PLANT_CD,
             TM_VHMD_VEHICLE_MASTER.VHMD_ID_VEHICLE_MASTER AS VEHI_ID_VEHI_VEHICLE,
             TM_VHMD_VEHICLE_MASTER.VHMD_CD_VAN AS VEHI_CD_VAN,
             ADPO_CD_VIN AS VEHI_CD_VIN,
             TM_VHMD_VEHICLE_MASTER.VHMD_CD_PLANT_ORD AS VEHI_CD_PLANT_ORD,
             TM_VHMD_VEHICLE_MASTER.VHMD_CD_PLANT_ORD_VAN AS VEHI_CD_PLANT_ORD_VAN,
             TM_VHMD_VEHICLE_MASTER.VHMD_CD_SRC_ORD AS VEHI_CD_SRC_ORD,
             TM_VHMD_VEHICLE_MASTER.VHMD_CD_SRC_ORD_TP AS VEHI_CD_SRC_TP,
             TM_VHMD_VEHICLE_MASTER.VHMD_CD_CTRY_CD AS VEHI_CD_CTRY_CD,
             TM_VHMD_VEHICLE_MASTER.VHMD_CD_LEGACY_MARKET AS VEHI_CD_LEGACY_MARKET,
             TM_VHMD_VEHICLE_MASTER.VHMD_CD_CUST_CD AS VEHI_CD_CUST_CD,
             TM_VHMD_VEHICLE_MASTER.VHMD_CD_MFG_MOD_CD AS VEHI_CD_MFG_MOD_CD,
             TM_VHMD_VEHICLE_MASTER.VHMD_CD_COMM_MOD_CD AS VEHI_CD_COMM_MOD_CD,
             TM_VHMD_VEHICLE_MASTER.VHMD_CD_BRAND_CD AS VEHI_CD_BRAND_CD,
             TM_VHMD_VEHICLE_MASTER.VHMD_CD_PROD_FAM AS VEHI_CD_PROD_FAM,
             MRPC.PROD_FAM_DESC AS VEHI_DS_PROD_FAM_DESC,
             MRPC.MAMD_CD_MRP_CTRL_CD AS VEHI_CD_MRP_CTRL_CD,
             NVL (MRPC.MRPC_DS_MRP_CTRL_DESC, DDWH02_DM_MA.FUNC_NOT_APPLICABLE ()) AS VEHI_DS_MRP_CTRL_DESC,
             TM_VHMD_VEHICLE_MASTER.VHMD_CD_TECH_TP AS VEHI_CD_TECH_TP,
             TM_VHMD_VEHICLE_MASTER.VHMD_CD_MOD_PLN_KEY AS VEHI_CD_MOD_PLN_KEY,
             TM_VHMD_VEHICLE_MASTER.VHMD_CD_MOD_VERSION AS VEHI_CD_MOD_VERSION,
             TM_VHMD_VEHICLE_MASTER.VHMD_CD_PRICE_BOOK AS VEHI_CD_PRICE_BOOK,
             TM_VHMD_VEHICLE_MASTER.VHMD_CD_SERIE AS VEHI_CD_SERIE,
             TM_VHMD_VEHICLE_MASTER.VHMD_DS_SERIE_DESC AS VEHI_CD_SERIE_DESCRIPTION,
             COALESCE (TT_PROR_PROD_ORD.PROR_CD_SERIE,
                       TT_PLOR_PLND_ORD.PLOR_CD_SERIE,
                       TM_VHMD_VEHICLE_MASTER.VHMD_CD_MRP_SERIE) VEHI_CD_MRP_SERIE,
                      SUBSTR (TM_VHMD_VEHICLE_MASTER.VHMD_CD_MRP_SERIE, 1, 1) VEHI_CD_PROD_LINE,
                      TM_VHMD_VEHICLE_MASTER.VHMD_CD_ENGINE_NBR AS VEHI_CD_ENGINE_NBR,
                      TM_VHMD_VEHICLE_MASTER.VHMD_CD_ENGINE_ITM AS VEHI_CD_ENGINE_ITM,
                      TM_VHMD_VEHICLE_MASTER.VHMD_CD_ENGINE_TP AS VEHI_CD_ENGINE_TP,
                      TM_VHMD_VEHICLE_MASTER.VHMD_CD_ENGINE_FLEX_NBR AS VEHI_CD_ENGINE_FLEX_NBR,
                      TM_VHMD_VEHICLE_MASTER.VHMD_DT_ENGINE_PROD_DT AS VEHI_DT_ENGINE_PROD_DT,
                      COALESCE (NULLIF (ADPO_NR_DAILY_ORD_SEQ,
                                        0) , NULLIF (VHSQ_NR_DAILY_ORD_SEQ,
                                                     0) , VHMD_NR_SEQ_NBR,
                                                          0) AS VEHI_NR_SEQ_NBR,
                               TM_VHMD_VEHICLE_MASTER.VHMD_DT_REQ_DLVR_DT AS VEHI_DT_REQ_DLVR_DT,
                               TM_VHMD_VEHICLE_MASTER.VHMD_DT_NEW_REQ_DLVR_DT AS VEHI_DT_NEW_REQ_DLVR_DT,
                               COALESCE (ADPO_DT_PLND_INLINE_DT,
                                         VHMD_DT_PLND_INLINE_DT,
                                         PLOR_DT_STR_PROD_DT) AS VEHI_DT_PLND_INLINE_DT,
                                        COALESCE (ADOP_DT_INLINE_DT,
                                                  PROR_DT_INLINE_DT,
                                                  VHMD_DT_INLINE_DT) AS VEHI_DT_INLINE_DT,
                                                 TM_VHMD_VEHICLE_MASTER.VHMD_DT_PLND_OFFLINE_DT AS VEHI_DT_PLND_OFFLINE_DT,
                                                 COALESCE (CASE
                                                               WHEN TM_VHMD_VEHICLE_MASTER.VHMD_CD_VEHICLE_PRO_STU >= 'ZM45'
                                                                    AND TM_VHMD_VEHICLE_MASTER.VHMD_CD_VEHICLE_PRO_STU != 'ZM65' THEN TM_VHMD_VEHICLE_MASTER.VHMD_DT_OFFLINE_DT
                                                           END,
                                                           ADOP_DT_OFFLINE_DT,
                                                           PROR_DT_OFFLINE_DT) AS VEHI_DT_OFFLINE_DT,
                                                          COALESCE (PLOR_FL_FIRM_INDIC,
                                                                    PROR_FL_FIRM_INDIC , (CASE
                                                                                              WHEN VHMD_CD_VEHICLE_PRO_STU >= 'ZM20'
                                                                                                   AND VHMD_CD_VEHICLE_PRO_STU < 'ZM35' THEN '1'
                                                                                              ELSE VHMD_FL_SCHED_UNIT_MARK
                                                                                          END)) AS VEHI_FL_SCHED_UNIT_MARK,
                                                                   TM_VHMD_VEHICLE_MASTER.VHMD_DT_EST_FAI_OK_DT AS VEHI_DT_EST_FAI_OK_DT,
                                                                   TM_VHMD_VEHICLE_MASTER.VHMD_DT_ORIG_EXPC_SHIP_DT VEHI_DT_ORG_EXPC_SHIP_DT,
                                                                   TM_VHMD_VEHICLE_MASTER.VHMD_DT_UPDT_EXPC_SHIP_DT VEHI_DT_UPDT_EXPC_SHIP_DT,
                                                                   TM_VHMD_VEHICLE_MASTER.VHMD_DT_EXPC_FAI_OK_DT AS VEHI_DT_EXPC_FAI_OK_DT,
                                                                   TM_VHMD_VEHICLE_MASTER.VHMD_DT_FAI_OK_DT AS VEHI_DT_FAI_OK_DT,
                                                                   TM_VHMD_VEHICLE_MASTER.VHMD_CD_VEHICLE_PRO_STU AS VEHI_CD_VEHICLE_PRO_STU,
                                                                   VPST_CD_VEHICLE_PRO_STU_DESC AS VEHI_DS_VEHICLE_PRO_STU_DESC,
                                                                   TM_VHMD_VEHICLE_MASTER.VHMD_FL_AVAILABLE_MARK AS VEHI_FL_AVAILABLE_MARK,
                                                                   TM_VHMD_VEHICLE_MASTER.VHMD_LD_PROD_REMARK AS VEHI_LD_PRODUCTION_REMARK,
                                                                   TM_VHMD_VEHICLE_MASTER.VHMD_DS_DISTR_REMARK AS VEHI_DS_DISTR_REMARK,
                                                                   TM_VHMD_VEHICLE_MASTER.VHMD_DS_PARK_LOCATION AS VEHI_DS_PARK_LOCATION,
                                                                   TM_VHMD_VEHICLE_MASTER.VHMD_LD_GENERAL_REMARK AS VEHI_LD_GENERAL_REMARK,
                                                                   TM_VHMD_VEHICLE_MASTER.VHMD_NR_NBR_REBUILD AS VEHI_NR_NBR_REBUILD,
                                                                   TM_VHMD_VEHICLE_MASTER.VHMD_CD_LAST_ORD AS VEHI_CD_LAST_ORD,
                                                                   TM_VHMD_VEHICLE_MASTER.VHMD_DT_LAST_ORD_STR_DT AS VEHI_DT_LAST_ORD_STR_DT,
                                                                   TM_VHMD_VEHICLE_MASTER.VHMD_DT_LAST_ORD_END_DT AS VEHI_DT_LAST_ORD_END_DT,
                                                                   TM_VHMD_VEHICLE_MASTER.VHMD_CD_SEC_LAST_ORD AS VEHI_CD_SEC_LAST_ORD,
                                                                   TM_VHMD_VEHICLE_MASTER.VHMD_DT_SEC_LAST_ORD_STR_DT VEHI_DT_SEC_LAST_ORD_STR_DT,
                                                                   TM_VHMD_VEHICLE_MASTER.VHMD_DT_SEC_LAST_ORD_END_DT VEHI_DT_SEC_LAST_ORD_END_DT,
                                                                   TM_VHMD_VEHICLE_MASTER.VHMD_CD_LAST_RWK_ORD AS VEHI_CD_LAST_RWK_ORD,
                                                                   TM_VHMD_VEHICLE_MASTER.VHMD_DT_LAST_RWK_ORD_STR_DT VEHI_DT_LAST_RWK_ORD_STR_DT,
                                                                   TM_VHMD_VEHICLE_MASTER.VHMD_DT_LAST_RWK_ORD_END_DT VEHI_DT_LAST_RWK_ORD_END_DT,
                                                                   TM_VHMD_VEHICLE_MASTER.VHMD_AM_VEHICLE_VAL AS VEHI_AM_VEHICLE_VAL,
                                                                   TM_VHMD_VEHICLE_MASTER.VHMD_CD_MIGR_STATUS AS VEHI_CD_MIGR_STATUS,
                                                                   TM_VHMD_VEHICLE_MASTER.VHMD_CD_VEHICLE_USAGE AS VEHI_CD_VEHICLE_USAGE,
                                                                   ADPO_DT_VIN_ASSIGN_DT AS VEHI_DT_VIN_ASSIGN_DT,
                                                                   NVL2 (TM_VHMD_VEHICLE_MASTER.VHMD_CD_VIN, 1, 0) AS VEHI_FL_VIN_ASSIGN_MARK,
                                                                   ADPO_NR_SERIE_ORD_SEQ AS VEHI_NR_SERIE_ORD_SEQ,
                                                                   ADPO_CD_PROD_ORD_STU AS VEHI_CD_PROD_ORD_STU,
                                                                   NVL (POST_LD_PROD_ORD_STU_DESC, DDWH02_DM_MA.FUNC_NOT_APPLICABLE ()) AS VEHI_LD_PROD_ORD_STU_DESC,
                                                                   ADPO_DT_LAST_BS_CREAT_DT AS VEHI_DT_LAST_BS_CREAT_DT,
                                                                   TTVN_CD_STATIC_VIN AS VEHI_CD_STATIC_VIN,
                                                                   TT_VHSP_VEHICLE_SHIPM.VHSP_DT_INTERCOMP_INV_DT AS VEHI_DT_INTERCOMP_INV_DT,
                                                                   TT_VHSP_VEHICLE_SHIPM.VHSP_DT_SHIPM_DT AS VEHI_DT_SHIPM_DT,
                                                                   TT_VHSP_VEHICLE_SHIPM.VHSP_DT_OK_HEADER_DT AS VEHI_DT_OK_HEADER_DT,
                                                                   TT_VHSP_VEHICLE_SHIPM.VHSP_DT_OK_WHEELS_DT AS VEHI_DT_OK_WHEELS_DT,
                                                                   TT_VHSP_VEHICLE_SHIPM.VHSP_DT_OK_ACCESS_DT AS VEHI_DT_OK_ACCESS_DT,
                                                                   TT_VHSP_VEHICLE_SHIPM.VHSP_CD_DEAL_ORD_NBR AS VEHI_CD_DEAL_ORD_NBR,
                                                                   TT_VHSP_VEHICLE_SHIPM.VHSP_DT_DEAL_ORD_DT AS VEHI_DT_DEAL_ORD_DT,
                                                                   TT_VHSP_VEHICLE_SHIPM.VHSP_CD_ASS_REQ_NBR AS VEHI_CD_ASS_REQ_NBR,
                                                                   TT_VHSP_VEHICLE_SHIPM.VHSP_DT_OK_DESPATCH_DT AS VEHI_DT_OK_DESPATCH_DT,
                                                                   TT_VHSP_VEHICLE_SHIPM.VHSP_CD_DRAFT_NUMBER AS VEHI_CD_DRAFT_NUMBER,
                                                                   TT_VHSP_VEHICLE_SHIPM.VHSP_DT_CONF_PICK_UP_DT AS VEHI_DT_CONF_PICK_UP_DT,
                                                                   TT_VHSP_VEHICLE_SHIPM.VHSP_CD_LEGACY_MARKET AS VEHI_CD_LEGACY_MARKET_PALS,
                                                                   TT_VHSP_VEHICLE_SHIPM.VHSP_DT_CALL_OFF_DT AS VEHI_DT_CALL_OFF_DT,
                                                                   TT_VHSP_VEHICLE_SHIPM.VHSP_DT_BOAT_SHIPM_DUE_DT VEHI_DT_BOAT_SHIPM_DUE_DT,
                                                                   TT_VHSP_VEHICLE_SHIPM.VHSP_DT_OK_MACH_DT AS VEHI_DT_OK_MACH_DT,
                                                                   TT_VHSP_VEHICLE_SHIPM.VHSP_CD_ORD_STU AS VEHI_CD_ORD_STU,
                                                                   TT_VHSP_VEHICLE_SHIPM.VHSP_CD_BRAND_CD AS VEHI_CD_BRAND_CD_PALS,
                                                                   TT_VHSP_VEHICLE_SHIPM.VHSP_DT_ASS_REQ_DT AS VEHI_DT_ASS_REQ_DT,
                                                                   TT_VHSP_VEHICLE_SHIPM.VHSP_CD_LOAD_DOCK AS VEHI_CD_LOAD_DOCK,
                                                                   TT_VHSP_VEHICLE_SHIPM.VHSP_CD_COMM_DLVR_TERM_CD VEHI_CD_COMM_DLVR_TERM_CD,
                                                                   NVL (P_ELT_ID_BATCH, N_ELT_ID_JOB_LOG) AS VEHI_ID_BATCH_ID,
                                                                   TM_VHMD_VEHICLE_MASTER.VHMD_CD_SOURCE_SYSTEM AS VEHI_CD_SOURCE_SYSTEM,
                                                                   DECODE (TDIM_VEHI_VEHICLE.VEHI_ID_VEHI_VEHICLE, NULL, 'I', 'U') AS CONTROL_FIELD
      FROM
        (SELECT VHMD_CD_PLANT_CD,
                VHMD_ID_VEHICLE_MASTER,
                VHMD_CD_VAN,
                VHMD_CD_VIN,
                VHMD_CD_PLANT_ORD,
                VHMD_CD_PLANT_ORD_VAN,
                VHMD_CD_SRC_ORD,
                VHMD_CD_SRC_ORD_TP,
                VHMD_CD_CTRY_CD,
                VHMD_CD_LEGACY_MARKET,
                VHMD_CD_CUST_CD,
                VHMD_CD_MFG_MOD_CD,
                VHMD_CD_COMM_MOD_CD,
                VHMD_CD_BRAND_CD,
                VHMD_ID_MAMD_PROD_FAM,
                VHMD_CD_PROD_FAM,
                VHMD_CD_TECH_TP,
                VHMD_CD_MOD_PLN_KEY,
                VHMD_CD_MOD_VERSION,
                VHMD_CD_PRICE_BOOK,
                VHMD_CD_SERIE,
                VHMD_DS_SERIE_DESC,
                VHMD_CD_MRP_SERIE,
                VHMD_CD_ENGINE_NBR,
                VHMD_CD_ENGINE_ITM,
                VHMD_CD_ENGINE_TP,
                VHMD_CD_ENGINE_FLEX_NBR,
                VHMD_DT_ENGINE_PROD_DT,
                VHMD_NR_SEQ_NBR,
                VHMD_DT_REQ_DLVR_DT,
                VHMD_DT_NEW_REQ_DLVR_DT,
                VHMD_DT_PLND_INLINE_DT,
                VHMD_DT_INLINE_DT,
                VHMD_DT_PLND_OFFLINE_DT,
                VHMD_DT_OFFLINE_DT,
                VHMD_FL_SCHED_UNIT_MARK,
                VHMD_DT_EST_FAI_OK_DT,
                VHMD_DT_ORIG_EXPC_SHIP_DT,
                VHMD_DT_UPDT_EXPC_SHIP_DT,
                VHMD_DT_EXPC_FAI_OK_DT,
                VHMD_DT_FAI_OK_DT,
                VHMD_CD_VEHICLE_PRO_STU,
                VHMD_FL_AVAILABLE_MARK,
                VHMD_LD_PROD_REMARK,
                VHMD_DS_DISTR_REMARK,
                VHMD_DS_PARK_LOCATION,
                VHMD_LD_GENERAL_REMARK,
                VHMD_NR_NBR_REBUILD,
                VHMD_CD_LAST_ORD,
                VHMD_DT_LAST_ORD_STR_DT,
                VHMD_DT_LAST_ORD_END_DT,
                VHMD_CD_SEC_LAST_ORD,
                VHMD_DT_SEC_LAST_ORD_STR_DT,
                VHMD_DT_SEC_LAST_ORD_END_DT,
                VHMD_CD_LAST_RWK_ORD,
                VHMD_DT_LAST_RWK_ORD_STR_DT,
                VHMD_DT_LAST_RWK_ORD_END_DT,
                VHMD_AM_VEHICLE_VAL,
                VHMD_CD_MIGR_STATUS,
                VHMD_CD_VEHICLE_USAGE,
                VHMD_ID_TTVN_TECH_TP,
                VHMD_ID_BATCH_ID,
                VHMD_CD_SOURCE_SYSTEM
         FROM DDWH01_DW_MA.TM_VHMD_VEHICLE_MASTER
         WHERE 1=1
           AND VHMD_CD_PLANT_CD = P_ELT_CD_PLANT
           AND VHMD_CD_MIGR_STATUS IN ('98',
                                       '99',
                                       '97',
                                       '00',
                                       '01') ) TM_VHMD_VEHICLE_MASTER,

        (SELECT MAMD_CD_MRP_CTRL_CD,
                MRPC_DS_MRP_CTRL_DESC,
                LPDS_DS_SHORT_DESC AS PROD_FAM_DESC,
                MAMD_ID_MAT_MASTER,
                MAMD_CD_PLANT_CD
         FROM DDWH01_DW_MA.TM_MAMD_MAT_MASTER,
              DDWH01_DW_MA.TM_MRPC_MRP_CONTROLLER,

           (SELECT LPDS_NR_ID_OBJECT,
                   LPDS_ID_LANG_ID_LANGUAGE,
                   LPDS_DS_SHORT_DESC
            FROM
              (SELECT *
               FROM DDWH01_DW_MA.TM_LPDS_PLANT_DESCRIPTIONS
               WHERE LPDS_CD_PLANT_CD =P_ELT_CD_PLANT ) , DDWH01_DW_MA.TM_PDTY_PLANT_DESC_TYPE ,
              (SELECT *
               FROM DDWH01_DW_MA.TM_PLNT_PLANT
               WHERE PLNT_CD_PLANT_CD =P_ELT_CD_PLANT )
            WHERE LPDS_ID_PDTY_PLANT_DESC_TP = PDTY_ID_PLANT_DESC_TP
              AND PDTY_DS_DESC_NAME = 'MAMD'
              AND LPDS_ID_LANG_ID_LANGUAGE = PLNT_ID_LANG_M ) LPDS
         WHERE 1=1
           AND MAMD_ID_MRPC_MRP_CTRL_CD = MRPC_ID_MRP_CONTROLLER (+)
           AND MAMD_CD_PLANT_CD = MRPC_CD_PLANT_CD (+)
           AND MAMD_CD_PLANT_CD = P_ELT_CD_PLANT
           AND MAMD_ID_MAT_MASTER = LPDS.LPDS_NR_ID_OBJECT (+) ) MRPC,

        (SELECT *
         FROM DDWH02_DM_MA.TDIM_VEHI_VEHICLE TDIM_VEHI_VEHICLE
         WHERE 1=1
           AND VEHI_CD_PLANT_CD = P_ELT_CD_PLANT ) TDIM_VEHI_VEHICLE,

        (SELECT *
         FROM
           (SELECT VHSP.*,
                   ROW_NUMBER () OVER (PARTITION BY VHSP_ID_VHMD_PLANT_ORD
                                       ORDER BY VHSP_ID_VEHICLE_SHIPM DESC) AS COUNTER
            FROM DDWH01_DW_MA.TT_VHSP_VEHICLE_SHIPM VHSP
            WHERE VHSP_CD_PLANT_CD = P_ELT_CD_PLANT )
         WHERE COUNTER = 1 ) TT_VHSP_VEHICLE_SHIPM,

        (SELECT *
         FROM DDWH01_DW_MA.TM_TTVN_TECH_TP_VIN_REL
         WHERE TTVN_CD_PLANT_CD = P_ELT_CD_PLANT ) TM_TTVN_TECH_TP_VIN_REL,

        (SELECT ADPO_CD_VAN,
                ADPO_CD_PART_NBR_PROD,
                MIN (ADPO_DT_VIN_ASSIGN_DT) KEEP (DENSE_RANK FIRST
                                                  ORDER BY ADPO_ID_PROR_EFF_ORD DESC) ADPO_DT_VIN_ASSIGN_DT,
                                            MAX (ADPO_DT_PLND_INLINE_DT) KEEP (DENSE_RANK FIRST
                                                                               ORDER BY ADPO_ID_PROR_EFF_ORD DESC) ADPO_DT_PLND_INLINE_DT,
                                                                         MIN (ADPO_NR_DAILY_ORD_SEQ) KEEP (DENSE_RANK FIRST
                                                                                                           ORDER BY ADPO_ID_PROR_EFF_ORD DESC) ADPO_NR_DAILY_ORD_SEQ,
                                                                                                     MIN (ADPO_NR_SERIE_ORD_SEQ) KEEP (DENSE_RANK FIRST
                                                                                                                                       ORDER BY ADPO_ID_PROR_EFF_ORD DESC) ADPO_NR_SERIE_ORD_SEQ,
                                                                                                                                 MIN (ADPO_CD_PROD_ORD_STU) KEEP (DENSE_RANK FIRST
                                                                                                                                                                  ORDER BY ADPO_ID_PROR_EFF_ORD DESC) ADPO_CD_PROD_ORD_STU,
                                                                                                                                                            MAX (ADPO_DT_LAST_BS_CREAT_DT) KEEP (DENSE_RANK FIRST
                                                                                                                                                                                                 ORDER BY ADPO_ID_PROR_EFF_ORD DESC) ADPO_DT_LAST_BS_CREAT_DT,
                                                                                                                                                                                           MAX (DECODE (ADOP_CD_OP, '0010', TRUNC (ADOP_DT_ACT_END_OP_DT), NULL)) KEEP (DENSE_RANK FIRST
                                                                                                                                                                                                                                                                        ORDER BY ADPO_ID_PROR_EFF_ORD DESC) ADOP_DT_INLINE_DT,
                                                                                                                                                                                                                                                                  MAX (DECODE (ADOP_CD_OP, '0020', TRUNC (ADOP_DT_ACT_END_OP_DT), NULL)) KEEP (DENSE_RANK FIRST
                                                                                                                                                                                                                                                                                                                                               ORDER BY ADPO_ID_PROR_EFF_ORD DESC) ADOP_DT_OFFLINE_DT,
                                                                                                                                                                                                                                                                                                                                         MAX (ADPO_CD_VIN) KEEP (DENSE_RANK FIRST
                                                                                                                                                                                                                                                                                                                                                                 ORDER BY ADPO_ID_PROR_EFF_ORD DESC) ADPO_CD_VIN,
                                                                                                                                                                                                                                                                                                                                                           MIN (POST_LD_PROD_ORD_STU_DESC) KEEP (DENSE_RANK FIRST
                                                                                                                                                                                                                                                                                                                                                                                                 ORDER BY ADPO_ID_PROR_EFF_ORD DESC) POST_LD_PROD_ORD_STU_DESC
         FROM
           (SELECT *
            FROM DDWH01_DW_MA.TT_ADPO_ACT_DECL_PROD_ORD
            WHERE ADPO_CD_PLANT_CD = P_ELT_CD_PLANT ) ,
           (SELECT *
            FROM DDWH01_DW_MA.TD_ADOP_ACT_DECL_OP
            WHERE ADOP_CD_PLANT_CD = P_ELT_CD_PLANT ) ,
           (SELECT POST_ID_PROD_ORD_STU,
                   POST_LD_PROD_ORD_STU_DESC
            FROM DDWH01_DW_MA.TM_POST_PROD_ORD_STU
            WHERE POST_CD_PLANT_CD = P_ELT_CD_PLANT )
         WHERE ADPO_CD_PROD_SUPERV = 'CRF'
           AND ADPO_ID_ACT_DECL_PROD_ORD = ADOP_ID_ADPO_ACT_DECL_PROD_ORD (+)
           AND ADPO_ID_POST_PROD_ORD_STU = POST_ID_PROD_ORD_STU (+)
         GROUP BY ADPO_CD_VAN,
                  ADPO_CD_PART_NBR_PROD) TT_ADPO_ACT_DECL_PROD_ORD,

        (SELECT PROR_CD_VAN,
                PROR_CD_PART_NBR,
                '1' PROR_FL_FIRM_INDIC,
                    MIN (DECODE (PROP_CD_OP, '0010', PROP_DT_CONFIRM_DT, NULL)) PROR_DT_INLINE_DT,
                        MIN (DECODE (PROP_CD_OP, '0020', PROP_DT_CONFIRM_DT, NULL)) PROR_DT_OFFLINE_DT,
                            MAX (PROR_CD_SERIE) PROR_CD_SERIE
         FROM
           (SELECT *
            FROM DDWH01_DW_MA.TT_PROR_PROD_ORD
            WHERE PROR_CD_PLANT_CD = P_ELT_CD_PLANT
              AND PROR_FL_LOGICAL_STATUS = '1' ) ,
           (SELECT *
            FROM DDWH01_DW_MA.TD_PROP_PROD_ORD_OP
            WHERE PROP_CD_PLANT_CD = P_ELT_CD_PLANT
              AND PROP_FL_LOGICAL_STATUS ='1' )
         WHERE PROR_CD_PROD_SUPERV = 'CRF'
           AND PROR_ID_PROD_ORD = PROP_ID_PROR_PROD_ORD (+)
         GROUP BY PROR_CD_VAN,
                  PROR_CD_PART_NBR) TT_PROR_PROD_ORD,

        (SELECT PLOR_CD_VAN,
                PLOR_CD_PART_NBR,
                MAX (PLOR_DT_STR_PROD_DT) PLOR_DT_STR_PROD_DT,
                    MAX (PLOR_FL_FIRM_INDIC) KEEP (DENSE_RANK FIRST
                                                   ORDER BY PLOR_DT_STR_PROD_DT DESC) PLOR_FL_FIRM_INDIC,
                                             MAX (PLOR_CD_SERIE) PLOR_CD_SERIE
         FROM DDWH01_DW_MA.TT_PLOR_PLND_ORD
         WHERE PLOR_CD_PLANT_CD = P_ELT_CD_PLANT
           AND PLOR_CD_PROD_SUPERV = 'CRF'
         GROUP BY PLOR_CD_VAN,
                  PLOR_CD_PART_NBR) TT_PLOR_PLND_ORD,

        (SELECT VPST_CD_VEHICLE_PRO_STU_DESC,
                VPST_CD_VEHICLE_PRO_STU
         FROM DDWH01_DW_MA.TM_VPST_VEHICLE_PRO_STU_MASTER
         WHERE VPST_CD_PLANT_CD = P_ELT_CD_PLANT ) TM_VPST_VEHICLE_PRO_STU_MASTER,

        (SELECT *
         FROM DDWH01_DW_MA.TT_VHSQ_VAN_SEQUENCES
         WHERE VHSQ_CD_PLANT_CD = P_ELT_CD_PLANT
           AND VHSQ_FL_LOGICAL_STATUS = '1' ) TT_VHSQ_VAN_SEQUENCES
      WHERE 1=1
        AND TM_VHMD_VEHICLE_MASTER.VHMD_ID_MAMD_PROD_FAM = MRPC.MAMD_ID_MAT_MASTER (+)
        AND TM_VHMD_VEHICLE_MASTER.VHMD_CD_PLANT_CD = MRPC.MAMD_CD_PLANT_CD (+)
        AND TM_VHMD_VEHICLE_MASTER.VHMD_ID_VEHICLE_MASTER = TDIM_VEHI_VEHICLE.VEHI_ID_VEHI_VEHICLE (+)
        AND TM_VHMD_VEHICLE_MASTER.VHMD_ID_VEHICLE_MASTER = TT_VHSP_VEHICLE_SHIPM.VHSP_ID_VHMD_PLANT_ORD (+)
        AND TM_VHMD_VEHICLE_MASTER.VHMD_ID_TTVN_TECH_TP = TM_TTVN_TECH_TP_VIN_REL.TTVN_ID_TECH_TP_VIN_REL (+)
        AND TM_VHMD_VEHICLE_MASTER.VHMD_CD_VAN = ADPO_CD_VAN (+)
        AND TM_VHMD_VEHICLE_MASTER.VHMD_CD_PROD_FAM = ADPO_CD_PART_NBR_PROD (+)
        AND TM_VHMD_VEHICLE_MASTER.VHMD_CD_VAN = PROR_CD_VAN (+)
        AND TM_VHMD_VEHICLE_MASTER.VHMD_CD_PROD_FAM = PROR_CD_PART_NBR (+)
        AND TM_VHMD_VEHICLE_MASTER.VHMD_CD_VAN = PLOR_CD_VAN (+)
        AND TM_VHMD_VEHICLE_MASTER.VHMD_CD_PROD_FAM = PLOR_CD_PART_NBR (+)
        AND TM_VHMD_VEHICLE_MASTER.VHMD_CD_VEHICLE_PRO_STU = VPST_CD_VEHICLE_PRO_STU (+)
        AND TM_VHMD_VEHICLE_MASTER.VHMD_CD_VAN = TT_VHSQ_VAN_SEQUENCES.VHSQ_CD_VAN (+) ) ,
     (SELECT CAST (DDWH02_DM_MA.FUNC_NOT_APPLICABLE () AS VARCHAR2 (50)) NOT_APPL
      FROM DUAL)) QRY ON (TRG.VEHI_CD_PLANT_CD = QRY.VEHI_CD_PLANT_CD
                          AND TRG.VEHI_ID_VEHI_VEHICLE = QRY.VEHI_ID_VEHI_VEHICLE) WHEN MATCHED THEN
UPDATE
SET TRG.VEHI_CD_VAN= QRY.VEHI_CD_VAN,
    TRG.VEHI_CD_VIN= QRY.VEHI_CD_VIN,
    TRG.VEHI_CD_PLANT_ORD= QRY.VEHI_CD_PLANT_ORD,
    TRG.VEHI_CD_PLANT_ORD_VAN= QRY.VEHI_CD_PLANT_ORD_VAN,
    TRG.VEHI_CD_SRC_ORD= QRY.VEHI_CD_SRC_ORD,
    TRG.VEHI_CD_SRC_TP= QRY.VEHI_CD_SRC_TP,
    TRG.VEHI_CD_CTRY_CD= QRY.VEHI_CD_CTRY_CD,
    TRG.VEHI_CD_LEGACY_MARKET= QRY.VEHI_CD_LEGACY_MARKET,
    TRG.VEHI_CD_CUST_CD= QRY.VEHI_CD_CUST_CD,
    TRG.VEHI_CD_MFG_MOD_CD= QRY.VEHI_CD_MFG_MOD_CD,
    TRG.VEHI_CD_COMM_MOD_CD= QRY.VEHI_CD_COMM_MOD_CD,
    TRG.VEHI_CD_BRAND_CD= QRY.VEHI_CD_BRAND_CD,
    TRG.VEHI_CD_PROD_FAM= QRY.VEHI_CD_PROD_FAM,
    TRG.VEHI_DS_PROD_FAM_DESC= QRY.VEHI_DS_PROD_FAM_DESC,
    TRG.VEHI_CD_MRP_CTRL_CD= QRY.VEHI_CD_MRP_CTRL_CD,
    TRG.VEHI_DS_MRP_CTRL_DESC= QRY.VEHI_DS_MRP_CTRL_DESC,
    TRG.VEHI_CD_TECH_TP= QRY.VEHI_CD_TECH_TP,
    TRG.VEHI_CD_MOD_PLN_KEY= QRY.VEHI_CD_MOD_PLN_KEY,
    TRG.VEHI_CD_MOD_VERSION= QRY.VEHI_CD_MOD_VERSION,
    TRG.VEHI_CD_PRICE_BOOK= QRY.VEHI_CD_PRICE_BOOK,
    TRG.VEHI_CD_SERIE= QRY.VEHI_CD_SERIE,
    TRG.VEHI_CD_SERIE_DESCRIPTION= QRY.VEHI_CD_SERIE_DESCRIPTION,
    TRG.VEHI_CD_MRP_SERIE= QRY.VEHI_CD_MRP_SERIE,
    TRG.VEHI_CD_PROD_LINE= QRY.VEHI_CD_PROD_LINE,
    TRG.VEHI_CD_ENGINE_NBR= QRY.VEHI_CD_ENGINE_NBR,
    TRG.VEHI_CD_ENGINE_ITM= QRY.VEHI_CD_ENGINE_ITM,
    TRG.VEHI_CD_ENGINE_TP= QRY.VEHI_CD_ENGINE_TP,
    TRG.VEHI_CD_ENGINE_FLEX_NBR= QRY.VEHI_CD_ENGINE_FLEX_NBR,
    TRG.VEHI_DT_ENGINE_PROD_DT= QRY.VEHI_DT_ENGINE_PROD_DT,
    TRG.VEHI_NR_SEQ_NBR= QRY.VEHI_NR_SEQ_NBR,
    TRG.VEHI_DT_REQ_DLVR_DT= QRY.VEHI_DT_REQ_DLVR_DT,
    TRG.VEHI_DT_NEW_REQ_DLVR_DT= QRY.VEHI_DT_NEW_REQ_DLVR_DT,
    TRG.VEHI_DT_PLND_INLINE_DT= QRY.VEHI_DT_PLND_INLINE_DT,
    TRG.VEHI_DT_INLINE_DT= QRY.VEHI_DT_INLINE_DT,
    TRG.VEHI_DT_PLND_OFFLINE_DT= QRY.VEHI_DT_PLND_OFFLINE_DT,
    TRG.VEHI_DT_OFFLINE_DT= QRY.VEHI_DT_OFFLINE_DT,
    TRG.VEHI_FL_SCHED_UNIT_MARK= QRY.VEHI_FL_SCHED_UNIT_MARK,
    TRG.VEHI_DT_EST_FAI_OK_DT= QRY.VEHI_DT_EST_FAI_OK_DT,
    TRG.VEHI_DT_ORG_EXPC_SHIP_DT= QRY.VEHI_DT_ORG_EXPC_SHIP_DT,
    TRG.VEHI_DT_UPDT_EXPC_SHIP_DT= QRY.VEHI_DT_UPDT_EXPC_SHIP_DT,
    TRG.VEHI_DT_EXPC_FAI_OK_DT= QRY.VEHI_DT_EXPC_FAI_OK_DT,
    TRG.VEHI_DT_FAI_OK_DT= QRY.VEHI_DT_FAI_OK_DT,
    TRG.VEHI_CD_VEHICLE_PRO_STU= QRY.VEHI_CD_VEHICLE_PRO_STU,
    TRG.VEHI_DS_VEHICLE_PRO_STU_DESC= QRY.VEHI_DS_VEHICLE_PRO_STU_DESC,
    TRG.VEHI_FL_AVAILABLE_MARK= QRY.VEHI_FL_AVAILABLE_MARK,
    TRG.VEHI_LD_PRODUCTION_REMARK= QRY.VEHI_LD_PRODUCTION_REMARK,
    TRG.VEHI_DS_DISTR_REMARK= QRY.VEHI_DS_DISTR_REMARK,
    TRG.VEHI_DS_PARK_LOCATION= QRY.VEHI_DS_PARK_LOCATION,
    TRG.VEHI_LD_GENERAL_REMARK= QRY.VEHI_LD_GENERAL_REMARK,
    TRG.VEHI_NR_NBR_REBUILD= QRY.VEHI_NR_NBR_REBUILD,
    TRG.VEHI_CD_LAST_ORD= QRY.VEHI_CD_LAST_ORD,
    TRG.VEHI_DT_LAST_ORD_STR_DT= QRY.VEHI_DT_LAST_ORD_STR_DT,
    TRG.VEHI_DT_LAST_ORD_END_DT= QRY.VEHI_DT_LAST_ORD_END_DT,
    TRG.VEHI_CD_SEC_LAST_ORD= QRY.VEHI_CD_SEC_LAST_ORD,
    TRG.VEHI_DT_SEC_LAST_ORD_STR_DT= QRY.VEHI_DT_SEC_LAST_ORD_STR_DT,
    TRG.VEHI_DT_SEC_LAST_ORD_END_DT= QRY.VEHI_DT_SEC_LAST_ORD_END_DT,
    TRG.VEHI_CD_LAST_RWK_ORD= QRY.VEHI_CD_LAST_RWK_ORD,
    TRG.VEHI_DT_LAST_RWK_ORD_STR_DT= QRY.VEHI_DT_LAST_RWK_ORD_STR_DT,
    TRG.VEHI_DT_LAST_RWK_ORD_END_DT= QRY.VEHI_DT_LAST_RWK_ORD_END_DT,
    TRG.VEHI_AM_VEHICLE_VAL= QRY.VEHI_AM_VEHICLE_VAL,
    TRG.VEHI_CD_MIGR_STATUS= QRY.VEHI_CD_MIGR_STATUS,
    TRG.VEHI_CD_VEHICLE_USAGE= QRY.VEHI_CD_VEHICLE_USAGE,
    TRG.VEHI_DT_VIN_ASSIGN_DT= QRY.VEHI_DT_VIN_ASSIGN_DT,
    TRG.VEHI_FL_VIN_ASSIGN_MARK= QRY.VEHI_FL_VIN_ASSIGN_MARK,
    TRG.VEHI_NR_SERIE_ORD_SEQ= QRY.VEHI_NR_SERIE_ORD_SEQ,
    TRG.VEHI_CD_PROD_STU= QRY.VEHI_CD_PROD_STU,
    TRG.VEHI_CD_PROD_ORD_STU= QRY.VEHI_CD_PROD_ORD_STU,
    TRG.VEHI_LD_PROD_ORD_STU_DESC= QRY.VEHI_LD_PROD_ORD_STU_DESC,
    TRG.VEHI_DT_LAST_BS_CREAT_DT= QRY.VEHI_DT_LAST_BS_CREAT_DT,
    TRG.VEHI_CD_STATIC_VIN= QRY.VEHI_CD_STATIC_VIN,
    TRG.VEHI_DT_INTERCOMP_INV_DT= QRY.VEHI_DT_INTERCOMP_INV_DT,
    TRG.VEHI_DT_SHIPM_DT= QRY.VEHI_DT_SHIPM_DT,
    TRG.VEHI_DT_OK_HEADER_DT= QRY.VEHI_DT_OK_HEADER_DT,
    TRG.VEHI_DT_OK_WHEELS_DT= QRY.VEHI_DT_OK_WHEELS_DT,
    TRG.VEHI_DT_OK_ACCESS_DT= QRY.VEHI_DT_OK_ACCESS_DT,
    TRG.VEHI_CD_DEAL_ORD_NBR= QRY.VEHI_CD_DEAL_ORD_NBR,
    TRG.VEHI_DT_DEAL_ORD_DT= QRY.VEHI_DT_DEAL_ORD_DT,
    TRG.VEHI_CD_ASS_REQ_NBR= QRY.VEHI_CD_ASS_REQ_NBR,
    TRG.VEHI_DT_OK_DESPATCH_DT= QRY.VEHI_DT_OK_DESPATCH_DT,
    TRG.VEHI_CD_DRAFT_NUMBER= QRY.VEHI_CD_DRAFT_NUMBER,
    TRG.VEHI_DT_CONF_PICK_UP_DT= QRY.VEHI_DT_CONF_PICK_UP_DT,
    TRG.VEHI_CD_LEGACY_MARKET_PALS= QRY.VEHI_CD_LEGACY_MARKET_PALS,
    TRG.VEHI_DT_CALL_OFF_DT= QRY.VEHI_DT_CALL_OFF_DT,
    TRG.VEHI_DT_BOAT_SHIPM_DUE_DT= QRY.VEHI_DT_BOAT_SHIPM_DUE_DT,
    TRG.VEHI_DT_OK_MACH_DT= QRY.VEHI_DT_OK_MACH_DT,
    TRG.VEHI_CD_ORD_STU= QRY.VEHI_CD_ORD_STU,
    TRG.VEHI_CD_BRAND_CD_PALS= QRY.VEHI_CD_BRAND_CD_PALS,
    TRG.VEHI_DT_ASS_REQ_DT= QRY.VEHI_DT_ASS_REQ_DT,
    TRG.VEHI_CD_LOAD_DOCK= QRY.VEHI_CD_LOAD_DOCK,
    TRG.VEHI_CD_COMM_DLVR_TERM_CD= QRY.VEHI_CD_COMM_DLVR_TERM_CD,
    TRG.VEHI_ID_BATCH_ID= QRY.VEHI_ID_BATCH_ID,
    TRG.VEHI_CD_SOURCE_SYSTEM= QRY.VEHI_CD_SOURCE_SYSTEM,
    TRG.VEHI_CD_OPERATOR_CODE= 'ETL',
    TRG.VEHI_DT_UPD_ROW= SYSDATE WHEN NOT MATCHED THEN
INSERT (VEHI_CD_PLANT_CD,
        VEHI_ID_VEHI_VEHICLE,
        VEHI_CD_VAN,
        VEHI_CD_VIN,
        VEHI_CD_PLANT_ORD,
        VEHI_CD_PLANT_ORD_VAN,
        VEHI_CD_SRC_ORD,
        VEHI_CD_SRC_TP,
        VEHI_CD_CTRY_CD,
        VEHI_CD_LEGACY_MARKET,
        VEHI_CD_CUST_CD,
        VEHI_CD_MFG_MOD_CD,
        VEHI_CD_COMM_MOD_CD,
        VEHI_CD_BRAND_CD,
        VEHI_CD_PROD_FAM,
        VEHI_DS_PROD_FAM_DESC,
        VEHI_CD_MRP_CTRL_CD,
        VEHI_DS_MRP_CTRL_DESC,
        VEHI_CD_TECH_TP,
        VEHI_CD_MOD_PLN_KEY,
        VEHI_CD_MOD_VERSION,
        VEHI_CD_PRICE_BOOK,
        VEHI_CD_SERIE,
        VEHI_CD_SERIE_DESCRIPTION,
        VEHI_CD_MRP_SERIE,
        VEHI_CD_PROD_LINE,
        VEHI_CD_ENGINE_NBR,
        VEHI_CD_ENGINE_ITM,
        VEHI_CD_ENGINE_TP,
        VEHI_CD_ENGINE_FLEX_NBR,
        VEHI_DT_ENGINE_PROD_DT,
        VEHI_NR_SEQ_NBR,
        VEHI_DT_REQ_DLVR_DT,
        VEHI_DT_NEW_REQ_DLVR_DT,
        VEHI_DT_PLND_INLINE_DT,
        VEHI_DT_INLINE_DT,
        VEHI_DT_PLND_OFFLINE_DT,
        VEHI_DT_OFFLINE_DT,
        VEHI_FL_SCHED_UNIT_MARK,
        VEHI_DT_EST_FAI_OK_DT,
        VEHI_DT_ORG_EXPC_SHIP_DT,
        VEHI_DT_UPDT_EXPC_SHIP_DT,
        VEHI_DT_EXPC_FAI_OK_DT,
        VEHI_DT_FAI_OK_DT,
        VEHI_CD_VEHICLE_PRO_STU,
        VEHI_DS_VEHICLE_PRO_STU_DESC,
        VEHI_FL_AVAILABLE_MARK,
        VEHI_LD_PRODUCTION_REMARK,
        VEHI_DS_DISTR_REMARK,
        VEHI_DS_PARK_LOCATION,
        VEHI_LD_GENERAL_REMARK,
        VEHI_NR_NBR_REBUILD,
        VEHI_CD_LAST_ORD,
        VEHI_DT_LAST_ORD_STR_DT,
        VEHI_DT_LAST_ORD_END_DT,
        VEHI_CD_SEC_LAST_ORD,
        VEHI_DT_SEC_LAST_ORD_STR_DT,
        VEHI_DT_SEC_LAST_ORD_END_DT,
        VEHI_CD_LAST_RWK_ORD,
        VEHI_DT_LAST_RWK_ORD_STR_DT,
        VEHI_DT_LAST_RWK_ORD_END_DT,
        VEHI_AM_VEHICLE_VAL,
        VEHI_CD_MIGR_STATUS,
        VEHI_CD_VEHICLE_USAGE,
        VEHI_DT_VIN_ASSIGN_DT,
        VEHI_FL_VIN_ASSIGN_MARK,
        VEHI_NR_SERIE_ORD_SEQ,
        VEHI_CD_PROD_STU,
        VEHI_CD_PROD_ORD_STU,
        VEHI_LD_PROD_ORD_STU_DESC,
        VEHI_DT_LAST_BS_CREAT_DT,
        VEHI_CD_STATIC_VIN,
        VEHI_DT_INTERCOMP_INV_DT,
        VEHI_DT_SHIPM_DT,
        VEHI_DT_OK_HEADER_DT,
        VEHI_DT_OK_WHEELS_DT,
        VEHI_DT_OK_ACCESS_DT,
        VEHI_CD_DEAL_ORD_NBR,
        VEHI_DT_DEAL_ORD_DT,
        VEHI_CD_ASS_REQ_NBR,
        VEHI_DT_OK_DESPATCH_DT,
        VEHI_CD_DRAFT_NUMBER,
        VEHI_DT_CONF_PICK_UP_DT,
        VEHI_CD_LEGACY_MARKET_PALS,
        VEHI_DT_CALL_OFF_DT,
        VEHI_DT_BOAT_SHIPM_DUE_DT,
        VEHI_DT_OK_MACH_DT,
        VEHI_CD_ORD_STU,
        VEHI_CD_BRAND_CD_PALS,
        VEHI_DT_ASS_REQ_DT,
        VEHI_CD_LOAD_DOCK,
        VEHI_CD_COMM_DLVR_TERM_CD,
        VEHI_ID_BATCH_ID,
        VEHI_CD_SOURCE_SYSTEM,
        VEHI_CD_OPERATOR_CODE,
        VEHI_DT_INS_ROW,
        VEHI_DT_UPD_ROW)
VALUES (QRY.VEHI_CD_PLANT_CD, QRY.VEHI_ID_VEHI_VEHICLE, QRY.VEHI_CD_VAN, QRY.VEHI_CD_VIN, QRY.VEHI_CD_PLANT_ORD, QRY.VEHI_CD_PLANT_ORD_VAN, QRY.VEHI_CD_SRC_ORD, QRY.VEHI_CD_SRC_TP, QRY.VEHI_CD_CTRY_CD, QRY.VEHI_CD_LEGACY_MARKET, QRY.VEHI_CD_CUST_CD, QRY.VEHI_CD_MFG_MOD_CD, QRY.VEHI_CD_COMM_MOD_CD, QRY.VEHI_CD_BRAND_CD, QRY.VEHI_CD_PROD_FAM, QRY.VEHI_DS_PROD_FAM_DESC, QRY.VEHI_CD_MRP_CTRL_CD, QRY.VEHI_DS_MRP_CTRL_DESC, QRY.VEHI_CD_TECH_TP, QRY.VEHI_CD_MOD_PLN_KEY, QRY.VEHI_CD_MOD_VERSION, QRY.VEHI_CD_PRICE_BOOK, QRY.VEHI_CD_SERIE, QRY.VEHI_CD_SERIE_DESCRIPTION, QRY.VEHI_CD_MRP_SERIE, QRY.VEHI_CD_PROD_LINE, QRY.VEHI_CD_ENGINE_NBR, QRY.VEHI_CD_ENGINE_ITM, QRY.VEHI_CD_ENGINE_TP, QRY.VEHI_CD_ENGINE_FLEX_NBR, QRY.VEHI_DT_ENGINE_PROD_DT, QRY.VEHI_NR_SEQ_NBR, QRY.VEHI_DT_REQ_DLVR_DT, QRY.VEHI_DT_NEW_REQ_DLVR_DT, QRY.VEHI_DT_PLND_INLINE_DT, QRY.VEHI_DT_INLINE_DT, QRY.VEHI_DT_PLND_OFFLINE_DT, QRY.VEHI_DT_OFFLINE_DT, QRY.VEHI_FL_SCHED_UNIT_MARK, QRY.VEHI_DT_EST_FAI_OK_DT, QRY.VEHI_DT_ORG_EXPC_SHIP_DT, QRY.VEHI_DT_UPDT_EXPC_SHIP_DT, QRY.VEHI_DT_EXPC_FAI_OK_DT, QRY.VEHI_DT_FAI_OK_DT, QRY.VEHI_CD_VEHICLE_PRO_STU, QRY.VEHI_DS_VEHICLE_PRO_STU_DESC, QRY.VEHI_FL_AVAILABLE_MARK, QRY.VEHI_LD_PRODUCTION_REMARK, QRY.VEHI_DS_DISTR_REMARK, QRY.VEHI_DS_PARK_LOCATION, QRY.VEHI_LD_GENERAL_REMARK, QRY.VEHI_NR_NBR_REBUILD, QRY.VEHI_CD_LAST_ORD, QRY.VEHI_DT_LAST_ORD_STR_DT, QRY.VEHI_DT_LAST_ORD_END_DT, QRY.VEHI_CD_SEC_LAST_ORD, QRY.VEHI_DT_SEC_LAST_ORD_STR_DT, QRY.VEHI_DT_SEC_LAST_ORD_END_DT, QRY.VEHI_CD_LAST_RWK_ORD, QRY.VEHI_DT_LAST_RWK_ORD_STR_DT, QRY.VEHI_DT_LAST_RWK_ORD_END_DT, QRY.VEHI_AM_VEHICLE_VAL, QRY.VEHI_CD_MIGR_STATUS, QRY.VEHI_CD_VEHICLE_USAGE, QRY.VEHI_DT_VIN_ASSIGN_DT, QRY.VEHI_FL_VIN_ASSIGN_MARK, QRY.VEHI_NR_SERIE_ORD_SEQ, QRY.VEHI_CD_PROD_STU, QRY.VEHI_CD_PROD_ORD_STU, QRY.VEHI_LD_PROD_ORD_STU_DESC, QRY.VEHI_DT_LAST_BS_CREAT_DT, QRY.VEHI_CD_STATIC_VIN, QRY.VEHI_DT_INTERCOMP_INV_DT, QRY.VEHI_DT_SHIPM_DT, QRY.VEHI_DT_OK_HEADER_DT, QRY.VEHI_DT_OK_WHEELS_DT, QRY.VEHI_DT_OK_ACCESS_DT, QRY.VEHI_CD_DEAL_ORD_NBR, QRY.VEHI_DT_DEAL_ORD_DT, QRY.VEHI_CD_ASS_REQ_NBR, QRY.VEHI_DT_OK_DESPATCH_DT, QRY.VEHI_CD_DRAFT_NUMBER, QRY.VEHI_DT_CONF_PICK_UP_DT, QRY.VEHI_CD_LEGACY_MARKET_PALS, QRY.VEHI_DT_CALL_OFF_DT, QRY.VEHI_DT_BOAT_SHIPM_DUE_DT, QRY.VEHI_DT_OK_MACH_DT, QRY.VEHI_CD_ORD_STU, QRY.VEHI_CD_BRAND_CD_PALS, QRY.VEHI_DT_ASS_REQ_DT, QRY.VEHI_CD_LOAD_DOCK, QRY.VEHI_CD_COMM_DLVR_TERM_CD, QRY.VEHI_ID_BATCH_ID, QRY.VEHI_CD_SOURCE_SYSTEM, 'ETL', SYSDATE, SYSDATE)