MERGE INTO DDWH02_DM_MA.TDIM_MASP_MAT_SUPP_REL TRG USING
  (SELECT MASP_CD_PLANT_CD,
          MASP_ID_MAT_SUPP_REL,
          MASP_CD_PART_NBR,
          MASP_CD_SUPPL_CD,
          MASP_CD_INFO_REC_CAT,
          MASP_LD_INFO_REC_CAT_DESC,
          MASP_CD_PURCH_ORG_CD,
          MASP_NR_QUOTE_PERC,
          MASP_QT_PLN_DLVR_TIME,
          MASP_CD_SUPPL_MAT_CD,
          MASP_NR_DAYS_FIRST_EXP,
          MASP_NR_DAYS_SEC_EXP,
          MASP_NR_DAYS_THIRD_EXP,
          MASP_CD_UNIT_OF_MEAS,
          MASP_QT_STD_QTY,
          MASP_QT_MIN_QTY,
          MASP_QT_MAX_QTY,
          MASP_PC_OVERDLVR_LIMIT,
          MASP_FL_OVERDLVR_ALLOW,
          MASP_PC_UNDERDLVR_LIMIT,
          MASP_CD_PURCH_ORD,
          MASP_DT_STR_VAL_DT,
          MASP_QT_REQ_QTY,
          MASP_CD_COMPANY_CD,
          MASP_CD_DOC_TP,
          MASP_DS_DOC_TP_DESC,
          MASP_CD_PURCH_GRP,
          MASP_CD_SITE_INT,
          MASP_FL_SEQ_LIST_MARK,
          NVL (P_ELT_ID_BATCH, N_ELT_ID_JOB_LOG) AS MASP_ID_BATCH_ID,
          MASP_CD_SOURCE_SYSTEM,
          DECODE (MASP_ID_MAT_SUPP_REL_DIM, NULL, 'I', 'U') AS CONTROL_FIELD
   FROM
     (SELECT TM_MASP_MAT_SUPP_REL.MASP_CD_PLANT_CD AS MASP_CD_PLANT_CD,
             TM_MASP_MAT_SUPP_REL.MASP_ID_MAT_SUPP_REL AS MASP_ID_MAT_SUPP_REL,
             TM_MASP_MAT_SUPP_REL.MASP_CD_PART_NBR AS MASP_CD_PART_NBR,
             TM_MASP_MAT_SUPP_REL.MASP_CD_SUPPL_CD AS MASP_CD_SUPPL_CD,
             TM_MASP_MAT_SUPP_REL.MASP_CD_INFO_REC_CAT AS MASP_CD_INFO_REC_CAT,
             TM_MASP_MAT_SUPP_REL.MASP_LD_INFO_REC_CAT_DESC AS MASP_LD_INFO_REC_CAT_DESC,
             TM_MASP_MAT_SUPP_REL.MASP_CD_PURCH_ORG_CD AS MASP_CD_PURCH_ORG_CD,
             TM_MASP_MAT_SUPP_REL.MASP_NR_QUOTE_PERC AS MASP_NR_QUOTE_PERC,
             TM_MASP_MAT_SUPP_REL.MASP_QT_PLN_DLVR_TIME AS MASP_QT_PLN_DLVR_TIME,
             TM_MASP_MAT_SUPP_REL.MASP_CD_SUPPL_MAT_CD AS MASP_CD_SUPPL_MAT_CD,
             TM_MASP_MAT_SUPP_REL.MASP_NR_DAYS_FIRST_EXP AS MASP_NR_DAYS_FIRST_EXP,
             TM_MASP_MAT_SUPP_REL.MASP_NR_DAYS_SEC_EXP AS MASP_NR_DAYS_SEC_EXP,
             TM_MASP_MAT_SUPP_REL.MASP_NR_DAYS_THIRD_EXP AS MASP_NR_DAYS_THIRD_EXP,
             TM_MASP_MAT_SUPP_REL.MASP_CD_UNIT_OF_MEAS AS MASP_CD_UNIT_OF_MEAS,
             TM_MASP_MAT_SUPP_REL.MASP_QT_STD_QTY AS MASP_QT_STD_QTY,
             TM_MASP_MAT_SUPP_REL.MASP_QT_MIN_QTY AS MASP_QT_MIN_QTY,
             TM_MASP_MAT_SUPP_REL.MASP_QT_MAX_QTY AS MASP_QT_MAX_QTY,
             TM_MASP_MAT_SUPP_REL.MASP_PC_OVERDLVR_LIMIT AS MASP_PC_OVERDLVR_LIMIT,
             TM_MASP_MAT_SUPP_REL.MASP_FL_OVERDLVR_ALLOW AS MASP_FL_OVERDLVR_ALLOW,
             TM_MASP_MAT_SUPP_REL.MASP_PC_UNDERDLVR_LIMIT AS MASP_PC_UNDERDLVR_LIMIT,
             POLN_CD_PURCH_ORD,
             POLN_CD_PURCH_ORD_LN,
             SCLN_CD_SEQ_ID,
             MAX (SCLN_CD_SEQ_ID) KEEP (DENSE_RANK FIRST
                                        ORDER BY SIGN (SCLN_DT_REQ_DLVR_DT - TO_DATE (P_ELT_DT_JOB_DATE_ELAB, 'YYYYMMDD')) DESC , ABS (SCLN_DT_REQ_DLVR_DT - TO_DATE (P_ELT_DT_JOB_DATE_ELAB, 'YYYYMMDD')) , POLN_ID_PURCH_ORD_LN) OVER (PARTITION BY TM_MASP_MAT_SUPP_REL.MASP_CD_PART_NBR,
                                                                                                                                                                                                                                                      TM_MASP_MAT_SUPP_REL.MASP_CD_SUPPL_CD,
                                                                                                                                                                                                                                                      TM_MASP_MAT_SUPP_REL.MASP_CD_INFO_REC_CAT,
                                                                                                                                                                                                                                                      TM_MASP_MAT_SUPP_REL.MASP_CD_PURCH_ORG_CD) AS SCLN_CD_SEQ_ID_MAX,
                                                                                                                                                                                                                                        MAX (POLN_CD_PURCH_ORD_LN) KEEP (DENSE_RANK FIRST
                                                                                                                                                                                                                                                                         ORDER BY SIGN (SCLN_DT_REQ_DLVR_DT - TO_DATE (P_ELT_DT_JOB_DATE_ELAB, 'YYYYMMDD')) DESC , ABS (SCLN_DT_REQ_DLVR_DT - TO_DATE (P_ELT_DT_JOB_DATE_ELAB, 'YYYYMMDD')) , POLN_ID_PURCH_ORD_LN) OVER (PARTITION BY TM_MASP_MAT_SUPP_REL.MASP_CD_PART_NBR,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       TM_MASP_MAT_SUPP_REL.MASP_CD_SUPPL_CD,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       TM_MASP_MAT_SUPP_REL.MASP_CD_INFO_REC_CAT,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       TM_MASP_MAT_SUPP_REL.MASP_CD_PURCH_ORG_CD) AS POLN_CD_PURCH_ORD_LN_MAX,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                         MAX (POLN_CD_PURCH_ORD) KEEP (DENSE_RANK FIRST
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       ORDER BY SIGN (SCLN_DT_REQ_DLVR_DT - TO_DATE (P_ELT_DT_JOB_DATE_ELAB, 'YYYYMMDD')) DESC , ABS (SCLN_DT_REQ_DLVR_DT - TO_DATE (P_ELT_DT_JOB_DATE_ELAB, 'YYYYMMDD')) , POLN_ID_PURCH_ORD_LN) OVER (PARTITION BY TM_MASP_MAT_SUPP_REL.MASP_CD_PART_NBR,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     TM_MASP_MAT_SUPP_REL.MASP_CD_SUPPL_CD,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     TM_MASP_MAT_SUPP_REL.MASP_CD_INFO_REC_CAT,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     TM_MASP_MAT_SUPP_REL.MASP_CD_PURCH_ORG_CD) AS MASP_CD_PURCH_ORD,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       MAX (POLN_DT_STR_VAL_DT) KEEP (DENSE_RANK FIRST
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ORDER BY SIGN (SCLN_DT_REQ_DLVR_DT - TO_DATE (P_ELT_DT_JOB_DATE_ELAB, 'YYYYMMDD')) DESC , ABS (SCLN_DT_REQ_DLVR_DT - TO_DATE (P_ELT_DT_JOB_DATE_ELAB, 'YYYYMMDD')) , POLN_ID_PURCH_ORD_LN) OVER (PARTITION BY TM_MASP_MAT_SUPP_REL.MASP_CD_PART_NBR,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    TM_MASP_MAT_SUPP_REL.MASP_CD_SUPPL_CD,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    TM_MASP_MAT_SUPP_REL.MASP_CD_INFO_REC_CAT,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    TM_MASP_MAT_SUPP_REL.MASP_CD_PURCH_ORG_CD) AS MASP_DT_STR_VAL_DT,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      MAX (POLN_QT_REQ_QTY) KEEP (DENSE_RANK FIRST
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ORDER BY SIGN (SCLN_DT_REQ_DLVR_DT - TO_DATE (P_ELT_DT_JOB_DATE_ELAB, 'YYYYMMDD')) DESC , ABS (SCLN_DT_REQ_DLVR_DT - TO_DATE (P_ELT_DT_JOB_DATE_ELAB, 'YYYYMMDD')) , POLN_ID_PURCH_ORD_LN) OVER (PARTITION BY TM_MASP_MAT_SUPP_REL.MASP_CD_PART_NBR,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                TM_MASP_MAT_SUPP_REL.MASP_CD_SUPPL_CD,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                TM_MASP_MAT_SUPP_REL.MASP_CD_INFO_REC_CAT,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                TM_MASP_MAT_SUPP_REL.MASP_CD_PURCH_ORG_CD) AS MASP_QT_REQ_QTY,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  MAX (PORD_CD_COMPANY_CD) KEEP (DENSE_RANK FIRST
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ORDER BY SIGN (SCLN_DT_REQ_DLVR_DT - TO_DATE (P_ELT_DT_JOB_DATE_ELAB, 'YYYYMMDD')) DESC , ABS (SCLN_DT_REQ_DLVR_DT - TO_DATE (P_ELT_DT_JOB_DATE_ELAB, 'YYYYMMDD')) , POLN_ID_PURCH_ORD_LN) OVER (PARTITION BY TM_MASP_MAT_SUPP_REL.MASP_CD_PART_NBR,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               TM_MASP_MAT_SUPP_REL.MASP_CD_SUPPL_CD,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               TM_MASP_MAT_SUPP_REL.MASP_CD_INFO_REC_CAT,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               TM_MASP_MAT_SUPP_REL.MASP_CD_PURCH_ORG_CD) AS MASP_CD_COMPANY_CD,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 MAX (PORD_CD_DOC_TP) KEEP (DENSE_RANK FIRST
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ORDER BY SIGN (SCLN_DT_REQ_DLVR_DT - TO_DATE (P_ELT_DT_JOB_DATE_ELAB, 'YYYYMMDD')) DESC , ABS (SCLN_DT_REQ_DLVR_DT - TO_DATE (P_ELT_DT_JOB_DATE_ELAB, 'YYYYMMDD')) , POLN_ID_PURCH_ORD_LN) OVER (PARTITION BY TM_MASP_MAT_SUPP_REL.MASP_CD_PART_NBR,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          TM_MASP_MAT_SUPP_REL.MASP_CD_SUPPL_CD,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          TM_MASP_MAT_SUPP_REL.MASP_CD_INFO_REC_CAT,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          TM_MASP_MAT_SUPP_REL.MASP_CD_PURCH_ORG_CD) AS MASP_CD_DOC_TP,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            MAX (PORD_DS_DOC_TP_DESC) KEEP (DENSE_RANK FIRST
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ORDER BY SIGN (SCLN_DT_REQ_DLVR_DT - TO_DATE (P_ELT_DT_JOB_DATE_ELAB, 'YYYYMMDD')) DESC , ABS (SCLN_DT_REQ_DLVR_DT - TO_DATE (P_ELT_DT_JOB_DATE_ELAB, 'YYYYMMDD')) , POLN_ID_PURCH_ORD_LN) OVER (PARTITION BY TM_MASP_MAT_SUPP_REL.MASP_CD_PART_NBR,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          TM_MASP_MAT_SUPP_REL.MASP_CD_SUPPL_CD,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          TM_MASP_MAT_SUPP_REL.MASP_CD_INFO_REC_CAT,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          TM_MASP_MAT_SUPP_REL.MASP_CD_PURCH_ORG_CD) AS MASP_DS_DOC_TP_DESC,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            MAX (PORD_CD_PURCH_GRP) KEEP (DENSE_RANK FIRST
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ORDER BY SIGN (SCLN_DT_REQ_DLVR_DT - TO_DATE (P_ELT_DT_JOB_DATE_ELAB, 'YYYYMMDD')) DESC , ABS (SCLN_DT_REQ_DLVR_DT - TO_DATE (P_ELT_DT_JOB_DATE_ELAB, 'YYYYMMDD')) , POLN_ID_PURCH_ORD_LN) OVER (PARTITION BY TM_MASP_MAT_SUPP_REL.MASP_CD_PART_NBR,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        TM_MASP_MAT_SUPP_REL.MASP_CD_SUPPL_CD,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        TM_MASP_MAT_SUPP_REL.MASP_CD_INFO_REC_CAT,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        TM_MASP_MAT_SUPP_REL.MASP_CD_PURCH_ORG_CD) AS MASP_CD_PURCH_GRP,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          MAX (SCLN_CD_SITE_INT) KEEP (DENSE_RANK FIRST
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       ORDER BY SIGN (SCLN_DT_REQ_DLVR_DT - TO_DATE (P_ELT_DT_JOB_DATE_ELAB, 'YYYYMMDD')) DESC , ABS (SCLN_DT_REQ_DLVR_DT - TO_DATE (P_ELT_DT_JOB_DATE_ELAB, 'YYYYMMDD')) , POLN_ID_PURCH_ORD_LN) OVER (PARTITION BY TM_MASP_MAT_SUPP_REL.MASP_CD_PART_NBR,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     TM_MASP_MAT_SUPP_REL.MASP_CD_SUPPL_CD,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     TM_MASP_MAT_SUPP_REL.MASP_CD_INFO_REC_CAT,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     TM_MASP_MAT_SUPP_REL.MASP_CD_PURCH_ORG_CD) AS MASP_CD_SITE_INT,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       TM_SQLS.SQLP_ID_SEQ_LIST_PART_NBR,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       MAX (SQLP_ID_SEQ_LIST_PART_NBR) KEEP (DENSE_RANK FIRST
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ORDER BY SQLP_ID_SQLM_SEQ_LIST_ID) OVER (PARTITION BY TM_MASP_MAT_SUPP_REL.MASP_CD_PART_NBR,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   TM_MASP_MAT_SUPP_REL.MASP_CD_SUPPL_CD,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   TM_MASP_MAT_SUPP_REL.MASP_CD_INFO_REC_CAT,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   TM_MASP_MAT_SUPP_REL.MASP_CD_PURCH_ORG_CD) SQLP_ID_SEQ_LIST_PART_NBR_MAX,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     DECODE (MAX (TM_SQLS.SQLP_ID_SEQ_LIST_PART_NBR) KEEP (DENSE_RANK FIRST
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ORDER BY SQLP_ID_SQLM_SEQ_LIST_ID) OVER (PARTITION BY TM_MASP_MAT_SUPP_REL.MASP_CD_PART_NBR, TM_MASP_MAT_SUPP_REL.MASP_CD_SUPPL_CD, TM_MASP_MAT_SUPP_REL.MASP_CD_INFO_REC_CAT, TM_MASP_MAT_SUPP_REL.MASP_CD_PURCH_ORG_CD) , NULL, '0', '1') AS MASP_FL_SEQ_LIST_MARK,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     MASP_CD_SOURCE_SYSTEM AS MASP_CD_SOURCE_SYSTEM,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     TDIM_MASP_MAT_SUPP_REL.MASP_ID_MAT_SUPP_REL AS MASP_ID_MAT_SUPP_REL_DIM
      FROM
        (SELECT TM_MASP_MAT_SUPP_REL.*,
                IREC_LD_INFO_REC_CAT_DESC AS MASP_LD_INFO_REC_CAT_DESC
         FROM DDWH01_DW_MA.TM_MASP_MAT_SUPP_REL,
              DDWH01_DW_MA.TM_IREC_INFO_REC_CAT
         WHERE MASP_CD_PLANT_CD =P_ELT_CD_PLANT
           AND IREC_CD_PLANT_CD =P_ELT_CD_PLANT
           AND MASP_FL_LOGICAL_DELETION = '0'
           AND MASP_ID_IREC_INFO_REC_CAT = IREC_ID_INFO_REC_CAT ) TM_MASP_MAT_SUPP_REL,

        (SELECT *
         FROM DDWH01_DW_MA.TD_SCLN_SCHED_LN
         WHERE SCLN_CD_PLANT_CD = P_ELT_CD_PLANT
           AND SCLN_FL_LOGICAL_STATUS = '1' ) TD_SCLN_SCHED_LN,

        (SELECT *
         FROM DDWH01_DW_MA.TD_POLN_PURCH_ORD_LN
         WHERE POLN_CD_PLANT_CD =P_ELT_CD_PLANT
           AND POLN_FL_LOGICAL_STATUS='1' ) TD_POLN_PURCH_ORD_LN,

        (SELECT TT_PORD_PURCH_ORD.*,
                TM_POTP_PURCH_ORD_TP.POTP_DS_DOC_TP_DESC AS PORD_DS_DOC_TP_DESC
         FROM DDWH01_DW_MA.TT_PORD_PURCH_ORD,
              DDWH01_DW_MA.TM_POTP_PURCH_ORD_TP
         WHERE PORD_CD_PLANT_CD = P_ELT_CD_PLANT
           AND POTP_CD_PLANT_CD = P_ELT_CD_PLANT
           AND PORD_FL_LOGICAL_STATUS='1'
           AND PORD_ID_POTP_DOC_TP = POTP_ID_PURCH_ORD_TP ) TT_PORD_PURCH_ORD,

        (SELECT *
         FROM DDWH01_DW_MA.TM_SQLP_SEQ_LIST_PART_NBR,
              DDWH01_DW_MA.TM_SQLM_SEQ_LIST_MASTER
         WHERE SQLM_CD_PLANT_CD =P_ELT_CD_PLANT
           AND SQLP_CD_PLANT_CD =P_ELT_CD_PLANT
           AND TM_SQLP_SEQ_LIST_PART_NBR.SQLP_ID_SQLM_SEQ_LIST_ID = TM_SQLM_SEQ_LIST_MASTER.SQLM_ID_SEQ_LIST_MASTER
           AND SQLM_FL_LOGICAL_STATUS = '1'
           AND SQLP_FL_LOGICAL_STATUS = '1'
           AND SQLM_CD_SEQ_LIST_TP = 'PUR' ) TM_SQLS,

        (SELECT MASP_ID_MAT_SUPP_REL,
                MASP_CD_PART_NBR,
                MASP_CD_SUPPL_CD,
                MASP_CD_INFO_REC_CAT,
                MASP_CD_PURCH_ORG_CD
         FROM DDWH02_DM_MA.TDIM_MASP_MAT_SUPP_REL
         WHERE MASP_CD_PLANT_CD = P_ELT_CD_PLANT ) TDIM_MASP_MAT_SUPP_REL
      WHERE 1=1
        AND TM_MASP_MAT_SUPP_REL.MASP_ID_MAT_SUPP_REL = TD_POLN_PURCH_ORD_LN.POLN_ID_MASP_MAT_SUPP_REL (+)
        AND TD_POLN_PURCH_ORD_LN.POLN_ID_PORD_PURCH_ORD = TT_PORD_PURCH_ORD.PORD_ID_PURCH_ORD (+)
        AND TD_POLN_PURCH_ORD_LN.POLN_ID_PURCH_ORD_LN = TD_SCLN_SCHED_LN.SCLN_ID_POLN_PURCH_ORD (+)
        AND TM_MASP_MAT_SUPP_REL.MASP_CD_PART_NBR = TM_SQLS.SQLP_CD_PART_NBR (+)
        AND TM_MASP_MAT_SUPP_REL.MASP_CD_SUPPL_CD = TM_SQLS.SQLM_CD_SUPPL_CD (+)
        AND TM_MASP_MAT_SUPP_REL.MASP_CD_PART_NBR = TDIM_MASP_MAT_SUPP_REL.MASP_CD_PART_NBR (+)
        AND TM_MASP_MAT_SUPP_REL.MASP_CD_SUPPL_CD = TDIM_MASP_MAT_SUPP_REL.MASP_CD_SUPPL_CD (+)
        AND TM_MASP_MAT_SUPP_REL.MASP_CD_INFO_REC_CAT = TDIM_MASP_MAT_SUPP_REL.MASP_CD_INFO_REC_CAT (+)
        AND TM_MASP_MAT_SUPP_REL.MASP_CD_PURCH_ORG_CD = TDIM_MASP_MAT_SUPP_REL.MASP_CD_PURCH_ORG_CD (+) )
   WHERE NVL (MASP_CD_PURCH_ORD, 'NA') = NVL (POLN_CD_PURCH_ORD, 'NA')
     AND NVL (POLN_CD_PURCH_ORD_LN, 'NA') = NVL (POLN_CD_PURCH_ORD_LN_MAX, 'NA')
     AND NVL (SCLN_CD_SEQ_ID, 'NA') = NVL (SCLN_CD_SEQ_ID_MAX, 'NA')
     AND NVL (SQLP_ID_SEQ_LIST_PART_NBR, -1) = NVL (SQLP_ID_SEQ_LIST_PART_NBR_MAX, -1) ) QRY ON (TRG.MASP_CD_PLANT_CD = QRY.MASP_CD_PLANT_CD
                                                                                                 AND TRG.MASP_ID_MAT_SUPP_REL = QRY.MASP_ID_MAT_SUPP_REL) WHEN MATCHED THEN
UPDATE
SET TRG.MASP_CD_PART_NBR= QRY.MASP_CD_PART_NBR,
    TRG.MASP_CD_SUPPL_CD= QRY.MASP_CD_SUPPL_CD,
    TRG.MASP_CD_INFO_REC_CAT= QRY.MASP_CD_INFO_REC_CAT,
    TRG.MASP_LD_INFO_REC_CAT_DESC= QRY.MASP_LD_INFO_REC_CAT_DESC,
    TRG.MASP_CD_PURCH_ORG_CD= QRY.MASP_CD_PURCH_ORG_CD,
    TRG.MASP_NR_QUOTE_PERC= QRY.MASP_NR_QUOTE_PERC,
    TRG.MASP_QT_PLN_DLVR_TIME= QRY.MASP_QT_PLN_DLVR_TIME,
    TRG.MASP_CD_SUPPL_MAT_CD= QRY.MASP_CD_SUPPL_MAT_CD,
    TRG.MASP_NR_DAYS_FIRST_EXP= QRY.MASP_NR_DAYS_FIRST_EXP,
    TRG.MASP_NR_DAYS_SEC_EXP= QRY.MASP_NR_DAYS_SEC_EXP,
    TRG.MASP_NR_DAYS_THIRD_EXP= QRY.MASP_NR_DAYS_THIRD_EXP,
    TRG.MASP_CD_UNIT_OF_MEAS= QRY.MASP_CD_UNIT_OF_MEAS,
    TRG.MASP_QT_STD_QTY= QRY.MASP_QT_STD_QTY,
    TRG.MASP_QT_MIN_QTY= QRY.MASP_QT_MIN_QTY,
    TRG.MASP_QT_MAX_QTY= QRY.MASP_QT_MAX_QTY,
    TRG.MASP_PC_OVERDLVR_LIMIT= QRY.MASP_PC_OVERDLVR_LIMIT,
    TRG.MASP_FL_OVERDLVR_ALLOW= QRY.MASP_FL_OVERDLVR_ALLOW,
    TRG.MASP_PC_UNDERDLVR_LIMIT= QRY.MASP_PC_UNDERDLVR_LIMIT,
    TRG.MASP_CD_PURCH_ORD= QRY.MASP_CD_PURCH_ORD,
    TRG.MASP_DT_STR_VAL_DT= QRY.MASP_DT_STR_VAL_DT,
    TRG.MASP_QT_REQ_QTY= QRY.MASP_QT_REQ_QTY,
    TRG.MASP_CD_COMPANY_CD= QRY.MASP_CD_COMPANY_CD,
    TRG.MASP_CD_DOC_TP= QRY.MASP_CD_DOC_TP,
    TRG.MASP_DS_DOC_TP_DESC= QRY.MASP_DS_DOC_TP_DESC,
    TRG.MASP_CD_PURCH_GRP= QRY.MASP_CD_PURCH_GRP,
    TRG.MASP_CD_SITE_INT= QRY.MASP_CD_SITE_INT,
    TRG.MASP_FL_SEQ_LIST_MARK= QRY.MASP_FL_SEQ_LIST_MARK,
    TRG.MASP_ID_BATCH_ID= QRY.MASP_ID_BATCH_ID,
    TRG.MASP_CD_SOURCE_SYSTEM= QRY.MASP_CD_SOURCE_SYSTEM,
    TRG.MASP_CD_OPERATOR_CODE= 'ETL',
    TRG.MASP_DT_UPD_ROW= SYSDATE WHEN NOT MATCHED THEN
INSERT (MASP_CD_PLANT_CD,
        MASP_ID_MAT_SUPP_REL,
        MASP_CD_PART_NBR,
        MASP_CD_SUPPL_CD,
        MASP_CD_INFO_REC_CAT,
        MASP_LD_INFO_REC_CAT_DESC,
        MASP_CD_PURCH_ORG_CD,
        MASP_NR_QUOTE_PERC,
        MASP_QT_PLN_DLVR_TIME,
        MASP_CD_SUPPL_MAT_CD,
        MASP_NR_DAYS_FIRST_EXP,
        MASP_NR_DAYS_SEC_EXP,
        MASP_NR_DAYS_THIRD_EXP,
        MASP_CD_UNIT_OF_MEAS,
        MASP_QT_STD_QTY,
        MASP_QT_MIN_QTY,
        MASP_QT_MAX_QTY,
        MASP_PC_OVERDLVR_LIMIT,
        MASP_FL_OVERDLVR_ALLOW,
        MASP_PC_UNDERDLVR_LIMIT,
        MASP_CD_PURCH_ORD,
        MASP_DT_STR_VAL_DT,
        MASP_QT_REQ_QTY,
        MASP_CD_COMPANY_CD,
        MASP_CD_DOC_TP,
        MASP_DS_DOC_TP_DESC,
        MASP_CD_PURCH_GRP,
        MASP_CD_SITE_INT,
        MASP_FL_SEQ_LIST_MARK,
        MASP_ID_BATCH_ID,
        MASP_CD_SOURCE_SYSTEM,
        MASP_CD_OPERATOR_CODE,
        MASP_DT_INS_ROW,
        MASP_DT_UPD_ROW)
VALUES (QRY.MASP_CD_PLANT_CD, QRY.MASP_ID_MAT_SUPP_REL, QRY.MASP_CD_PART_NBR, QRY.MASP_CD_SUPPL_CD, QRY.MASP_CD_INFO_REC_CAT, QRY.MASP_LD_INFO_REC_CAT_DESC, QRY.MASP_CD_PURCH_ORG_CD, QRY.MASP_NR_QUOTE_PERC, QRY.MASP_QT_PLN_DLVR_TIME, QRY.MASP_CD_SUPPL_MAT_CD, QRY.MASP_NR_DAYS_FIRST_EXP, QRY.MASP_NR_DAYS_SEC_EXP, QRY.MASP_NR_DAYS_THIRD_EXP, QRY.MASP_CD_UNIT_OF_MEAS, QRY.MASP_QT_STD_QTY, QRY.MASP_QT_MIN_QTY, QRY.MASP_QT_MAX_QTY, QRY.MASP_PC_OVERDLVR_LIMIT, QRY.MASP_FL_OVERDLVR_ALLOW, QRY.MASP_PC_UNDERDLVR_LIMIT, QRY.MASP_CD_PURCH_ORD, QRY.MASP_DT_STR_VAL_DT, QRY.MASP_QT_REQ_QTY, QRY.MASP_CD_COMPANY_CD, QRY.MASP_CD_DOC_TP, QRY.MASP_DS_DOC_TP_DESC, QRY.MASP_CD_PURCH_GRP, QRY.MASP_CD_SITE_INT, QRY.MASP_FL_SEQ_LIST_MARK, QRY.MASP_ID_BATCH_ID, QRY.MASP_CD_SOURCE_SYSTEM, 'ETL', SYSDATE, SYSDATE)