MERGE INTO ddwh01_dw.TH_ZCOS_STANDARD_COST_STC TARGET USING
  (SELECT PART_NUMBER ZCOS_CD_MATERIAL_NUMBER ,
          'AG' ZCOS_DS_PLANT_SEGMENT ,
               'KT01' ZCOS_CD_PLANT_GPP ,
                      NULL ZCOS_CD_VALUATION_TYPE ,
                           STD_YEAR ZCOS_NR_FISCAL_CURR_YEAR ,
                           EFFECTIVE_DATE ZCOS_DT_MODIFICATION_DATE ,
                           SYSTEM ZCOS_CD_SOURCE_SYSTEM ,
                                  TOT_STC_AMT ZCOS_NR_STANDARD_PRICE ,
                                  UOM_CONV_FTR ZCOS_NR_PRICE_UNIT ,
                                  BASE_STC_AMT ZCOS_NR_BASE_MATERIAL_COST ,
                                  SUBCONTR_IND ZCOS_NR_SUBCONTRACTING ,
                                  ULOC ZCOS_CD_WPS_USING_LOC ,
                                  TABLE_ID ZCOS_DS_WPS_USING_LOC ,
                                  PART_PREFIX ZCOS_CD_PREFIX ,
                                  CURR_CDE ZCOS_CD_CURRENCY ,
                                  STC_UOM_CDE ZCOS_CD_STC_UOM_CDE ,
                                  PO_UOM_CDE ZCOS_PO_UOM_CDE ,
                                  WAREHOUSE ZCOS_CD_WAREHOUSE
   FROM ddwh00_sa.TS_STDC0001_WW_EXT SA1
   UNION ALL SELECT PART_NUMBER ZCOS_CD_MATERIAL_NUMBER ,
                    'AS' ZCOS_DS_PLANT_SEGMENT ,
                         'IN05' ZCOS_CD_PLANT_GPP ,
                                NULL ZCOS_CD_VALUATION_TYPE ,
                                     STD_YEAR ZCOS_NR_FISCAL_CURR_YEAR ,
                                     EFFECTIVE_DATE ZCOS_DT_MODIFICATION_DATE ,
                                     SYSTEM ZCOS_CD_SOURCE_SYSTEM ,
                                            TOT_STC_AMT ZCOS_NR_STANDARD_PRICE ,
                                            UOM_CONV_FTR ZCOS_NR_PRICE_UNIT ,
                                            BASE_STC_AMT ZCOS_NR_BASE_MATERIAL_COST ,
                                            SUBCONTR_IND ZCOS_NR_SUBCONTRACTING ,
                                            ULOC ZCOS_CD_WPS_USING_LOC ,
                                            TABLE_ID ZCOS_DS_WPS_USING_LOC ,
                                            PART_PREFIX ZCOS_CD_PREFIX ,
                                            CURR_CDE ZCOS_CD_CURRENCY ,
                                            STC_UOM_CDE ZCOS_CD_STC_UOM_CDE ,
                                            PO_UOM_CDE ZCOS_PO_UOM_CDE ,
                                            WAREHOUSE ZCOS_CD_WAREHOUSE
   FROM ddwh00_sa.TS_STDC0002_WW_EXT SA2
   UNION ALL SELECT PART_NUMBER ZCOS_CD_MATERIAL_NUMBER ,
                    'AG' ZCOS_DS_PLANT_SEGMENT ,
                         'PU01' ZCOS_CD_PLANT_GPP ,
                                NULL ZCOS_CD_VALUATION_TYPE ,
                                     STD_YEAR ZCOS_NR_FISCAL_CURR_YEAR ,
                                     EFFECTIVE_DATE ZCOS_DT_MODIFICATION_DATE ,
                                     SYSTEM ZCOS_CD_SOURCE_SYSTEM ,
                                            TOT_STC_AMT ZCOS_NR_STANDARD_PRICE ,
                                            UOM_CONV_FTR ZCOS_NR_PRICE_UNIT ,
                                            BASE_STC_AMT ZCOS_NR_BASE_MATERIAL_COST ,
                                            SUBCONTR_IND ZCOS_NR_SUBCONTRACTING ,
                                            ULOC ZCOS_CD_WPS_USING_LOC ,
                                            TABLE_ID ZCOS_DS_WPS_USING_LOC ,
                                            PART_PREFIX ZCOS_CD_PREFIX ,
                                            CURR_CDE ZCOS_CD_CURRENCY ,
                                            STC_UOM_CDE ZCOS_CD_STC_UOM_CDE ,
                                            PO_UOM_CDE ZCOS_PO_UOM_CDE ,
                                            WAREHOUSE ZCOS_CD_WAREHOUSE
   FROM ddwh00_sa.TS_STDC0003_WW_EXT SA3
   UNION ALL SELECT PART_NUMBER ZCOS_CD_MATERIAL_NUMBER,
                    'AG' ZCOS_DS_PLANT_SEGMENT,
                         'PH01' ZCOS_CD_PLANT_GPP,
                                NULL ZCOS_CD_VALUATION_TYPE,
                                     STD_YEAR ZCOS_NR_FISCAL_CURR_YEAR,
                                     EFFECTIVE_DATE ZCOS_DT_MODIFICATION_DATE,
                                     SYSTEM ZCOS_CD_SOURCE_SYSTEM,
                                            TOT_STC_AMT ZCOS_NR_STANDARD_PRICE,
                                            UOM_CONV_FTR ZCOS_NR_PRICE_UNIT,
                                            BASE_STC_AMT ZCOS_NR_BASE_MATERIAL_COST,
                                            SUBCONTR_IND ZCOS_NR_SUBCONTRACTING,
                                            ULOC ZCOS_CD_WPS_USING_LOC,
                                            TABLE_ID ZCOS_DS_WPS_USING_LOC,
                                            PART_PREFIX ZCOS_CD_PREFIX,
                                            CURR_CDE ZCOS_CD_CURRENCY,
                                            STC_UOM_CDE ZCOS_CD_STC_UOM_CDE,
                                            PO_UOM_CDE ZCOS_PO_UOM_CDE,
                                            WAREHOUSE ZCOS_CD_WAREHOUSE
   FROM ddwh00_sa.TS_STDC0004_WW_EXT SA4
   UNION ALL SELECT PART_NUMBER ZCOS_CD_MATERIAL_NUMBER ,
                    'CE' ZCOS_DS_PLANT_SEGMENT ,
                         'IN02' ZCOS_CD_PLANT_GPP ,
                                NULL ZCOS_CD_VALUATION_TYPE ,
                                     STD_YEAR ZCOS_NR_FISCAL_CURR_YEAR ,
                                     EFFECTIVE_DATE ZCOS_DT_MODIFICATION_DATE ,
                                     SYSTEM ZCOS_CD_SOURCE_SYSTEM ,
                                            TOT_STC_AMT ZCOS_NR_STANDARD_PRICE ,
                                            UOM_CONV_FTR ZCOS_NR_PRICE_UNIT ,
                                            BASE_STC_AMT ZCOS_NR_BASE_MATERIAL_COST ,
                                            SUBCONTR_IND ZCOS_NR_SUBCONTRACTING ,
                                            ULOC ZCOS_CD_WPS_USING_LOC ,
                                            TABLE_ID ZCOS_DS_WPS_USING_LOC ,
                                            PART_PREFIX ZCOS_CD_PREFIX ,
                                            CURR_CDE ZCOS_CD_CURRENCY ,
                                            STC_UOM_CDE ZCOS_CD_STC_UOM_CDE ,
                                            PO_UOM_CDE ZCOS_PO_UOM_CDE ,
                                            WAREHOUSE ZCOS_CD_WAREHOUSE
   FROM ddwh00_sa.TS_STDC0005_WW_EXT SA5
   UNION ALL SELECT PART_NUMBER ZCOS_CD_MATERIAL_NUMBER ,
                    'AG' ZCOS_DS_PLANT_SEGMENT ,
                         'ND01' ZCOS_CD_PLANT_GPP ,
                                NULL ZCOS_CD_VALUATION_TYPE ,
                                     STD_YEAR ZCOS_NR_FISCAL_CURR_YEAR ,
                                     EFFECTIVE_DATE ZCOS_DT_MODIFICATION_DATE ,
                                     SYSTEM ZCOS_CD_SOURCE_SYSTEM ,
                                            TOT_STC_AMT ZCOS_NR_STANDARD_PRICE ,
                                            UOM_CONV_FTR ZCOS_NR_PRICE_UNIT ,
                                            BASE_STC_AMT ZCOS_NR_BASE_MATERIAL_COST ,
                                            SUBCONTR_IND ZCOS_NR_SUBCONTRACTING ,
                                            ULOC ZCOS_CD_WPS_USING_LOC ,
                                            TABLE_ID ZCOS_DS_WPS_USING_LOC ,
                                            PART_PREFIX ZCOS_CD_PREFIX ,
                                            CURR_CDE ZCOS_CD_CURRENCY ,
                                            STC_UOM_CDE ZCOS_CD_STC_UOM_CDE ,
                                            PO_UOM_CDE ZCOS_PO_UOM_CDE ,
                                            WAREHOUSE ZCOS_CD_WAREHOUSE
   FROM ddwh00_sa.TS_STDC0006_WW_EXT SA6
   UNION ALL SELECT PART_NUMBER ZCOS_CD_MATERIAL_NUMBER ,
                    'AG' ZCOS_DS_PLANT_SEGMENT ,
                         CASE
                             WHEN ULOC = 'CN' THEN 'CN02'
                             WHEN ULOC = 'CH' THEN 'CN06'
                             WHEN ULOC = 'CU' THEN 'CN05'
                             WHEN ULOC = 'CF' THEN 'FS01'
                             WHEN ULOC = 'CI' THEN 'CN12'
                             WHEN ULOC = 'DR' THEN 'CN14'
                             WHEN ULOC = 'DH' THEN 'CN13'
                         END AS ZCOS_CD_PLANT_GPP ,
                         NULL ZCOS_CD_VALUATION_TYPE ,
                              STD_YEAR ZCOS_NR_FISCAL_CURR_YEAR ,
                              EFFECTIVE_DATE ZCOS_DT_MODIFICATION_DATE ,
                              SYSTEM ZCOS_CD_SOURCE_SYSTEM ,
                                     TOT_STC_AMT ZCOS_NR_STANDARD_PRICE ,
                                     UOM_CONV_FTR ZCOS_NR_PRICE_UNIT ,
                                     BASE_STC_AMT ZCOS_NR_BASE_MATERIAL_COST ,
                                     SUBCONTR_IND ZCOS_NR_SUBCONTRACTING ,
                                     ULOC ZCOS_CD_WPS_USING_LOC ,
                                     TABLE_ID ZCOS_DS_WPS_USING_LOC ,
                                     PART_PREFIX ZCOS_CD_PREFIX ,
                                     CURR_CDE ZCOS_CD_CURRENCY ,
                                     STC_UOM_CDE ZCOS_CD_STC_UOM_CDE ,
                                     PO_UOM_CDE ZCOS_PO_UOM_CDE ,
                                     WAREHOUSE ZCOS_CD_WAREHOUSE
   FROM ddwh00_sa.TS_STDC0007_WW_EXT SA7 MINUS SELECT ZCOS_CD_MATERIAL_NUMBER ,
                                                      ZCOS_DS_PLANT_SEGMENT ,
                                                      ZCOS_CD_PLANT_GPP ,
                                                      ZCOS_CD_VALUATION_TYPE ,
                                                      ZCOS_NR_FISCAL_CURR_YEAR ,
                                                      ZCOS_DT_MODIFICATION_DATE ,
                                                      ZCOS_CD_SOURCE_SYSTEM ,
                                                      ZCOS_NR_STANDARD_PRICE ,
                                                      ZCOS_NR_PRICE_UNIT ,
                                                      ZCOS_NR_BASE_MATERIAL_COST ,
                                                      ZCOS_NR_SUBCONTRACTING ,
                                                      ZCOS_CD_WPS_USING_LOC ,
                                                      ZCOS_DS_WPS_USING_LOC ,
                                                      ZCOS_CD_PREFIX ,
                                                      ZCOS_CD_CURRENCY ,
                                                      ZCOS_CD_STC_UOM_CDE ,
                                                      ZCOS_PO_UOM_CDE ,
                                                      ZCOS_CD_WAREHOUSE
   FROM ddwh01_dw.TH_ZCOS_STANDARD_COST_STC DW) SA ON (TARGET.ZCOS_CD_MATERIAL_NUMBER = SA.ZCOS_CD_MATERIAL_NUMBER
                                                       AND TARGET.ZCOS_CD_PLANT_GPP = SA.ZCOS_CD_PLANT_GPP
                                                       AND nvl(TARGET.ZCOS_CD_VALUATION_TYPE, '*') = NVL(SA.ZCOS_CD_VALUATION_TYPE, '*')
                                                       AND TARGET.ZCOS_NR_FISCAL_CURR_YEAR = SA.ZCOS_NR_FISCAL_CURR_YEAR
                                                       AND TARGET.ZCOS_DT_MODIFICATION_DATE = SA.ZCOS_DT_MODIFICATION_DATE
                                                       AND TARGET.ZCOS_CD_SOURCE_SYSTEM = SA.ZCOS_CD_SOURCE_SYSTEM) WHEN MATCHED THEN
UPDATE
SET TARGET.ZCOS_DS_PLANT_SEGMENT = SA.ZCOS_DS_PLANT_SEGMENT ,
    TARGET.ZCOS_NR_STANDARD_PRICE = SA.ZCOS_NR_STANDARD_PRICE ,
    TARGET.ZCOS_NR_PRICE_UNIT = SA.ZCOS_NR_PRICE_UNIT ,
    TARGET.ZCOS_NR_BASE_MATERIAL_COST = SA.ZCOS_NR_BASE_MATERIAL_COST ,
    TARGET.ZCOS_NR_SUBCONTRACTING = SA.ZCOS_NR_SUBCONTRACTING ,
    TARGET.ZCOS_CD_WPS_USING_LOC = SA.ZCOS_CD_WPS_USING_LOC ,
    TARGET.ZCOS_DS_WPS_USING_LOC = SA.ZCOS_DS_WPS_USING_LOC ,
    TARGET.ZCOS_CD_PREFIX = SA.ZCOS_CD_PREFIX ,
    TARGET.ZCOS_CD_CURRENCY = SA.ZCOS_CD_CURRENCY ,
    TARGET.ZCOS_CD_STC_UOM_CDE = SA.ZCOS_CD_STC_UOM_CDE ,
    TARGET.ZCOS_PO_UOM_CDE = SA.ZCOS_PO_UOM_CDE ,
    TARGET.ZCOS_CD_WAREHOUSE = SA.ZCOS_CD_WAREHOUSE ,
    TARGET.ZCOS_DT_LAST_MODIFY = SYSDATE ,
    TARGET.ZCOS_ID_BATCH_LAST_MODIFY = NVL(p_ELT_ID_BATCH, n_ELT_ID_JOB_LOG) WHEN NOT MATCHED THEN
INSERT (ZCOS_ID_COST ,
        ZCOS_CD_MATERIAL_NUMBER ,
        ZCOS_DS_PLANT_SEGMENT ,
        ZCOS_CD_PLANT_GPP ,
        ZCOS_CD_VALUATION_TYPE ,
        ZCOS_NR_FISCAL_CURR_YEAR ,
        ZCOS_DT_MODIFICATION_DATE ,
        ZCOS_CD_SOURCE_SYSTEM ,
        ZCOS_NR_STANDARD_PRICE ,
        ZCOS_NR_PRICE_UNIT ,
        ZCOS_NR_BASE_MATERIAL_COST ,
        ZCOS_NR_SUBCONTRACTING ,
        ZCOS_CD_WPS_USING_LOC ,
        ZCOS_DS_WPS_USING_LOC ,
        ZCOS_CD_PREFIX ,
        ZCOS_CD_CURRENCY ,
        ZCOS_CD_STC_UOM_CDE ,
        ZCOS_PO_UOM_CDE ,
        ZCOS_CD_WAREHOUSE ,
        ZCOS_ID_BATCH_ID ,
        ZCOS_DT_END_VALIDITY ,
        ZCOS_DT_START_VALIDITY ,
        ZCOS_DT_INSERT ,
        ZCOS_ID_BATCH_LAST_MODIFY ,
        ZCOS_DT_LAST_MODIFY)
VALUES (DDWH01_DW.SEQ_TH_STDC.NEXTVAL ,SA.ZCOS_CD_MATERIAL_NUMBER ,SA.ZCOS_DS_PLANT_SEGMENT ,SA.ZCOS_CD_PLANT_GPP ,SA.ZCOS_CD_VALUATION_TYPE ,SA.ZCOS_NR_FISCAL_CURR_YEAR ,SA.ZCOS_DT_MODIFICATION_DATE ,SA.ZCOS_CD_SOURCE_SYSTEM ,SA.ZCOS_NR_STANDARD_PRICE ,SA.ZCOS_NR_PRICE_UNIT ,SA.ZCOS_NR_BASE_MATERIAL_COST ,SA.ZCOS_NR_SUBCONTRACTING ,SA.ZCOS_CD_WPS_USING_LOC ,SA.ZCOS_DS_WPS_USING_LOC ,SA.ZCOS_CD_PREFIX ,SA.ZCOS_CD_CURRENCY ,SA.ZCOS_CD_STC_UOM_CDE ,SA.ZCOS_PO_UOM_CDE ,SA.ZCOS_CD_WAREHOUSE , NVL(p_ELT_ID_BATCH, n_ELT_ID_JOB_LOG) , TO_DATE('01/01/1900', 'DD/MM/YYYY') , TO_DATE('31/12/9999', 'DD/MM/YYYY') , SYSDATE , NVL(p_ELT_ID_BATCH, n_ELT_ID_JOB_LOG) , SYSDATE);