INSERT INTO DDWH02_DM_MA.TW_MTCL_MC_LEAD_TIME (MTCL_CD_PLANT_CD, MTCL_ID_MTCL, MTCL_ID_REQU_REQ_CAT, MTCL_CD_REQ_CAT, MTCL_ID_VEHI_VAN, MTCL_CD_VAN, MTCL_ID_TIME_REQ_DT, MTCL_DT_REQ_DT, MTCL_ID_TIME_INDREQ_REQ_DT, MTCL_DT_INDREQ_REQ_DT, MTCL_CD_PROD_LINE, MTCL_CD_IND_ID, MTCL_CD_SALE_ORD_NBR, MTCL_CD_SALE_ORD_LN, MTCL_CD_SCHED_LN_ID, MTCL_ID_MTRL_PART_NBR_IR, MTCL_CD_PART_NBR_IR, MTCL_ID_CUST_CUST_CD, MTCL_CD_CUST_CD, MTCL_ID_MTRL_COMP, MTCL_CD_COMP, MTCL_CD_VAN_STU, MTCL_QT_BOM_QTY, MTCL_QT_CONSUMED_QTY, MTCL_QT_MOUNTED_QTY, MTCL_CD_COMP_PROCUR_TP, MTCL_CD_COMP_ASS_MARK, MTCL_ID_VEND_SUPPL_CD, MTCL_CD_SUPPL_CD, MTCL_QT_BACKLOG, MTCL_QT_CONS_QTY, MTCL_QT_PROM_QTY, MTCL_QT_ASN_QTY, MTCL_QT_INB_QTY, MTCL_CD_AGING_CAT_INB, MTCL_QT_QUALITY_AREA_QTY, MTCL_CD_AGING_CAT_QLTY_AREA, MTCL_QT_DEC_AREA_QTY, MTCL_CD_AGING_CAT_DEC_AREA, MTCL_QT_EXT_QTY, MTCL_CD_AGING_CAT_EXT, MTCL_QT_OTHER_CLICK_QTY, MTCL_CD_AGING_CAT_OTHER, MTCL_QT_WIP_LN_QTY, MTCL_QT_WIP_HARD_QTY, MTCL_QT_MOUNT_QTY, MTCL_NT_MOUNT_COMP_PATH, MTCL_QT_STOCK_QTY, MTCL_CD_AGING_CAT_STOCK, MTCL_QT_W999_QTY, MTCL_QT_MISS_QTY, MTCL_QT_CALC_MISS_QTY, MTCL_QT_CALC_MISS_QTY_PROM, MTCL_QT_REQ_QTY, MTCL_QT_REQ_PROG_QTY, MTCL_ID_COVC_COVERAGE_CD, MTCL_CD_COVERAGE_CD, MTCL_NR_COVERAGE_VAL, MTCL_QT_COVERAGE_QTY, MTCL_ID_COVC_COVERAGE_PROM, MTCL_CD_COVERAGE_PROM, MTCL_NR_COVERAGE_VAL_PROM, MTCL_QT_COVERAGE_QTY_PROM, MTCL_NR_WST_COV_VAL, MTCL_QT_WST_COV_QTY, MTCL_ID_TIME_WST_COV, MTCL_NR_WST_COV_VAL_PROM, MTCL_QT_WST_COV_QTY_PROM, MTCL_ID_TIME_WST_COV_PROM, MTCL_FL_STOP_MARK, MTCL_FL_PROM_MARK, MTCL_FL_CRITICAL_MARK, MTCL_FL_MTO_MARK, MTCL_FL_LEAF_COMP_MARK, MTCL_FL_SEQ_LIST_MARK, MTCL_FL_CALC_MISS_MARK, MTCL_FL_CALC_MISS_PROM_MARK, MTCL_FL_MISS_MARK, MTCL_QT_MIN_LEAD_TIME, MTCL_QT_MAX_LEAD_TIME, MTCL_ID_BATCH_ID, MTCL_CD_SOURCE_SYSTEM, MTCL_CD_OPERATOR_CODE, MTCL_DT_INS_ROW, MTCL_DT_UPD_ROW)
SELECT MTCL_CD_PLANT_CD,
       0 AS MTCL_ID_MTCL,
       MTCL_ID_REQU_REQ_CAT,
       MTCL_CD_REQ_CAT,
       MTCL_ID_VEHI_VAN,
       MTCL_CD_VAN,
       TO_NUMBER (TO_CHAR (MTCL_DT_REQ_DT, 'J')) AS MTCL_ID_TIME_REQ_DT,
       MTCL_DT_REQ_DT,
       TO_NUMBER (TO_CHAR (MTCL_DT_INDREQ_REQ_DT, 'J')) AS MTCL_ID_TIME_INDREQ_REQ_DT,
       MTCL_DT_INDREQ_REQ_DT,
       MTCL_CD_PROD_LINE,
       MTCL_CD_IND_ID,
       MTCL_CD_SALE_ORD_NBR,
       MTCL_CD_SALE_ORD_LN,
       MTCL_CD_SCHED_LN_ID,
       MTCL_ID_MTRL_PART_NBR_IR,
       MTCL_CD_PART_NBR_IR,
       MTCL_ID_CUST_CUST_CD,
       MTCL_CD_CUST_CD,
       MTCL_ID_MTRL_COMP,
       MTCL_CD_COMP,
       MTCL_CD_VAN_STU,
       MTCL_QT_BOM_QTY,
       MTCL_QT_CONSUMED_QTY,
       MTCL_QT_MOUNTED_QTY,
       MTCL_CD_COMP_PROCUR_TP,
       MTCL_CD_COMP_ASS_MARK,
       MTCL_ID_VEND_SUPPL_CD,
       MTCL_CD_SUPPL_CD,
       MTCL_QT_BACKLOG,
       MTCL_QT_CONS_QTY,
       MTCL_QT_PROM_QTY,
       MTCL_QT_ASN_QTY,
       MTCL_QT_INB_QTY,
       MTCL_CD_AGING_CAT_INB,
       MTCL_QT_QUALITY_AREA_QTY,
       MTCL_CD_AGING_CAT_QLTY_AREA,
       MTCL_QT_DEC_AREA_QTY,
       MTCL_CD_AGING_CAT_DEC_AREA,
       MTCL_QT_EXT_QTY,
       MTCL_CD_AGING_CAT_EXT,
       MTCL_QT_OTHER_CLICK_QTY,
       MTCL_CD_AGING_CAT_OTHER,
       MTCL_QT_WIP_LN_QTY,
       MTCL_QT_WIP_HARD_QTY,
       MTCL_QT_MOUNT_QTY,
       MTCL_NT_MOUNT_COMP_PATH,
       MTCL_QT_STOCK_QTY,
       MTCL_CD_AGING_CAT_STOCK,
       MTCL_QT_W999_QTY,
       MTCL_QT_MISS_QTY,
       MTCL_QT_CALC_MISS_QTY,
       MTCL_QT_CALC_MISS_QTY_PROM,
       MTCL_QT_REQ_QTY,
       MTCL_QT_REQ_PROG_QTY,
       MTCL_ID_COVC_COVERAGE_CD,
       MTCL_CD_COVERAGE_CD,
       MTCL_NR_COVERAGE_VAL,
       MTCL_QT_COVERAGE_QTY,
       MTCL_ID_COVC_COVERAGE_PROM,
       MTCL_CD_COVERAGE_PROM,
       MTCL_NR_COVERAGE_VAL_PROM,
       MTCL_QT_COVERAGE_QTY_PROM,
       MAX (MTCL_NR_COVERAGE_VAL) OVER (PARTITION BY MTCL_CD_PLANT_CD,
                                                     MTCL_CD_COMP) MTCL_NR_WST_COV_VAL,
                                       SUM (MTCL_QT_COVERAGE_QTY) KEEP (DENSE_RANK FIRST
                                                                        ORDER BY MTCL_NR_COVERAGE_VAL DESC NULLS LAST) OVER (PARTITION BY MTCL_CD_PLANT_CD,
                                                                                                                                          MTCL_CD_COMP) AS MTCL_QT_WST_COV_QTY,
                                                                                                                            MIN (TO_CHAR (NVL (MTCL_DT_REQ_DT, TO_DATE (P_ELT_DT_JOB_DATE_ELAB, 'YYYYMMDD')), 'J')) KEEP (DENSE_RANK FIRST
                                                                                                                                                                                                                          ORDER BY MTCL_NR_COVERAGE_VAL DESC NULLS LAST) OVER (PARTITION BY MTCL_CD_PLANT_CD,
                                                                                                                                                                                                                                                                                            MTCL_CD_COMP) AS MTCL_ID_TIME_WST_COV,
                                                                                                                                                                                                                                                                              MAX (MTCL_NR_COVERAGE_VAL_PROM) OVER (PARTITION BY MTCL_CD_PLANT_CD,
                                                                                                                                                                                                                                                                                                                                 MTCL_CD_COMP) AS MTCL_NR_WST_COV_VAL_PROM,
                                                                                                                                                                                                                                                                                                                   SUM (MTCL_QT_COVERAGE_QTY_PROM) KEEP (DENSE_RANK FIRST
                                                                                                                                                                                                                                                                                                                                                         ORDER BY MTCL_NR_COVERAGE_VAL_PROM DESC NULLS LAST) OVER (PARTITION BY MTCL_CD_PLANT_CD,
                                                                                                                                                                                                                                                                                                                                                                                                                                MTCL_CD_COMP) AS MTCL_QT_WST_COV_QTY_PROM,
                                                                                                                                                                                                                                                                                                                                                                                                                  MIN (TO_CHAR (NVL (MTCL_DT_REQ_DT, TO_DATE (P_ELT_DT_JOB_DATE_ELAB, 'YYYYMMDD')), 'J')) KEEP (DENSE_RANK FIRST
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ORDER BY MTCL_NR_COVERAGE_VAL_PROM DESC NULLS LAST) OVER (PARTITION BY MTCL_CD_PLANT_CD,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       MTCL_CD_COMP) AS MTCL_ID_TIME_WST_COV_PROM,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         MTCL_FL_STOP_MARK,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         MTCL_FL_PROM_MARK,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         MTCL_FL_CRITICAL_MARK,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         MTCL_FL_MTO_MARK,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         MTCL_FL_LEAF_COMP_MARK,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         MTCL_FL_SEQ_LIST_MARK,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         MTCL_FL_CALC_MISS_MARK,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         MTCL_FL_CALC_MISS_PROM_MARK,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         CASE
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             WHEN MTCL_QT_MISS_QTY>0 THEN '1'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ELSE '0'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         END AS MTCL_FL_MISS_MARK,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         MTCL_QT_MIN_LEAD_TIME,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         MTCL_QT_MAX_LEAD_TIME,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         NVL (P_ELT_ID_BATCH, N_ELT_ID_JOB_LOG) AS MTCL_ID_BATCH_ID,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         'MA' AS MTCL_CD_SOURCE_SYSTEM,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         'ETL' AS MCMW_CD_OPERATOR_CODE,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         SYSDATE AS MCMW_DT_INS_ROW,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         SYSDATE AS MCMW_DT_UPD_ROW
FROM
  (SELECT MCRL_CD_PLANT_CD AS MTCL_CD_PLANT_CD,
          MCRL_ID_REQU_REQ_CAT AS MTCL_ID_REQU_REQ_CAT,
          MCRL_CD_REQ_CAT AS MTCL_CD_REQ_CAT,
          MCRL_ID_VEHI_VAN AS MTCL_ID_VEHI_VAN,
          MCRL_CD_VAN AS MTCL_CD_VAN,
          MCRL_ID_TIME_REQ_DT AS MTCL_ID_TIME_REQ_DT,
          MCRL_DT_REQ_DT AS MTCL_DT_REQ_DT,
          MCRL_ID_TIME_INDREQ_REQ_DT AS MTCL_ID_TIME_INDREQ_REQ_DT,
          MCRL_DT_INDREQ_REQ_DT AS MTCL_DT_INDREQ_REQ_DT,
          MCRL_CD_PROD_LINE AS MTCL_CD_PROD_LINE,
          MCRL_CD_IND_ID AS MTCL_CD_IND_ID,
          MCRL_CD_SALE_ORD_NBR AS MTCL_CD_SALE_ORD_NBR,
          MCRL_CD_SALE_ORD_LN AS MTCL_CD_SALE_ORD_LN,
          MCRL_CD_SCHED_LN_ID AS MTCL_CD_SCHED_LN_ID,
          MCRL_ID_MTRL_PART_NBR_IR AS MTCL_ID_MTRL_PART_NBR_IR,
          MCRL_CD_PART_NBR_IR AS MTCL_CD_PART_NBR_IR,
          MCRL_ID_CUST_CUST_CD AS MTCL_ID_CUST_CUST_CD,
          MCRL_CD_CUST_CD AS MTCL_CD_CUST_CD,
          MCRL_ID_MTRL_COMP AS MTCL_ID_MTRL_COMP,
          MCRL_CD_COMP AS MTCL_CD_COMP,
          MCRL_CD_VAN_STU AS MTCL_CD_VAN_STU,
          MCRL_QT_BOM_QTY AS MTCL_QT_BOM_QTY,
          MCRL_QT_CONSUMED_QTY AS MTCL_QT_CONSUMED_QTY,
          MCRL_QT_MOUNTED_QTY AS MTCL_QT_MOUNTED_QTY,
          MCRL_CD_COMP_PROCUR_TP AS MTCL_CD_COMP_PROCUR_TP,
          MCRL_CD_COMP_ASS_MARK AS MTCL_CD_COMP_ASS_MARK,
          MCRL_ID_VEND_SUPPL_CD AS MTCL_ID_VEND_SUPPL_CD,
          MCRL_CD_SUPPL_CD AS MTCL_CD_SUPPL_CD,
          MCRL_QT_BACKLOG AS MTCL_QT_BACKLOG,
          MCRL_QT_CONS_QTY AS MTCL_QT_CONS_QTY,
          MCRL_QT_PROM_QTY AS MTCL_QT_PROM_QTY,
          MCRL_QT_ASN_QTY AS MTCL_QT_ASN_QTY,
          MCRL_QT_INB_QTY AS MTCL_QT_INB_QTY,
          MCRL_CD_AGING_CAT_INB AS MTCL_CD_AGING_CAT_INB,
          MCRL_QT_QUALITY_AREA_QTY AS MTCL_QT_QUALITY_AREA_QTY,
          MCRL_CD_AGING_CAT_QLTY_AREA AS MTCL_CD_AGING_CAT_QLTY_AREA,
          MCRL_QT_DEC_AREA_QTY AS MTCL_QT_DEC_AREA_QTY,
          MCRL_CD_AGING_CAT_DEC_AREA AS MTCL_CD_AGING_CAT_DEC_AREA,
          MCRL_QT_EXT_QTY AS MTCL_QT_EXT_QTY,
          MCRL_CD_AGING_CAT_EXT AS MTCL_CD_AGING_CAT_EXT,
          MCRL_QT_OTHER_CLICK_QTY AS MTCL_QT_OTHER_CLICK_QTY,
          MCRL_CD_AGING_CAT_OTHER AS MTCL_CD_AGING_CAT_OTHER,
          MCRL_QT_WIP_LN_QTY AS MTCL_QT_WIP_LN_QTY,
          MCRL_QT_WIP_HARD_QTY AS MTCL_QT_WIP_HARD_QTY,
          MCRL_QT_MOUNT_QTY AS MTCL_QT_MOUNT_QTY,
          MCRL_NT_MOUNT_COMP_PATH AS MTCL_NT_MOUNT_COMP_PATH,
          MCRL_QT_STOCK_QTY AS MTCL_QT_STOCK_QTY,
          MCRL_CD_AGING_CAT_STOCK AS MTCL_CD_AGING_CAT_STOCK,
          MCRL_QT_W999_QTY AS MTCL_QT_W999_QTY,
          MCRL_QT_MISS_QTY AS MTCL_QT_MISS_QTY,
          MCRL_QT_CALC_MISS_QTY AS MTCL_QT_CALC_MISS_QTY,
          MCRL_QT_CALC_MISS_QTY_PROM AS MTCL_QT_CALC_MISS_QTY_PROM,
          MCRL_QT_REQ_QTY AS MTCL_QT_REQ_QTY,
          MCRL_QT_REQ_PROG_QTY AS MTCL_QT_REQ_PROG_QTY,
          MCRL_ID_COVC_COVERAGE_CD AS MTCL_ID_COVC_COVERAGE_CD,
          MCRL_CD_COVERAGE_CD AS MTCL_CD_COVERAGE_CD,
          MCRL_NR_COVERAGE_VAL AS MTCL_NR_COVERAGE_VAL,
          MCRL_QT_COVERAGE_QTY AS MTCL_QT_COVERAGE_QTY,
          MCRL_ID_COVC_COVERAGE_PROM AS MTCL_ID_COVC_COVERAGE_PROM,
          MCRL_CD_COVERAGE_PROM AS MTCL_CD_COVERAGE_PROM,
          MCRL_NR_COVERAGE_VAL_PROM AS MTCL_NR_COVERAGE_VAL_PROM,
          MCRL_QT_COVERAGE_QTY_PROM AS MTCL_QT_COVERAGE_QTY_PROM,
          MCRL_FL_STOP_MARK AS MTCL_FL_STOP_MARK,
          MCRL_FL_PROM_MARK AS MTCL_FL_PROM_MARK,
          MCRL_FL_CRITICAL_MARK AS MTCL_FL_CRITICAL_MARK,
          MCRL_FL_MTO_MARK AS MTCL_FL_MTO_MARK,
          MCRL_FL_LEAF_COMP_MARK AS MTCL_FL_LEAF_COMP_MARK,
          MCRL_FL_SEQ_LIST_MARK AS MTCL_FL_SEQ_LIST_MARK,
          MCRL_FL_CALC_MISS_MARK AS MTCL_FL_CALC_MISS_MARK,
          MCRL_FL_CALC_MISS_PROM_MARK AS MTCL_FL_CALC_MISS_PROM_MARK,
          MCRL_FL_MISS_MARK AS MTCL_FL_MISS_MARK,
          MCRL_QT_MIN_LEAD_TIME AS MTCL_QT_MIN_LEAD_TIME,
          MCRL_QT_MAX_LEAD_TIME AS MTCL_QT_MAX_LEAD_TIME
   FROM TABLE (DDWH02_DM_MA.PKG_DM_MAT_COV_RULES_CALC.MC_MCRL_RULES_LT_CALC (
                                                                             CURSOR
                                                                               (SELECT *
                                                                                FROM DDWH02_DM_MA.TW_MCMW_MC_MAT_COVERAGE_WORK
                                                                                WHERE MCMW_CD_PLANT_CD = P_ELT_CD_PLANT ))))