INSERT INTO DDWH02_DM_MA.TW_MTCR_MC_REQ_TIME (MTCR_CD_PLANT_CD, MTCR_ID_MTCR, MTCR_ID_REQU_REQ_CAT, MTCR_CD_REQ_CAT, MTCR_ID_VEHI_VAN, MTCR_CD_VAN, MTCR_ID_TIME_REQ_DT, MTCR_DT_REQ_DT, MTCR_ID_TIME_INDREQ_REQ_DT, MTCR_DT_INDREQ_REQ_DT, MTCR_CD_PROD_LINE, MTCR_CD_IND_ID, MTCR_CD_SALE_ORD_NBR, MTCR_CD_SALE_ORD_LN, MTCR_CD_SCHED_LN_ID, MTCR_ID_MTRL_PART_NBR_IR, MTCR_CD_PART_NBR_IR, MTCR_ID_CUST_CUST_CD, MTCR_CD_CUST_CD, MTCR_ID_MTRL_COMP, MTCR_CD_COMP, MTCR_CD_VAN_STU, MTCR_QT_BOM_QTY, MTCR_QT_CONSUMED_QTY, MTCR_QT_MOUNTED_QTY, MTCR_CD_COMP_PROCUR_TP, MTCR_CD_COMP_ASS_MARK, MTCR_ID_VEND_SUPPL_CD, MTCR_CD_SUPPL_CD, MTCR_QT_BACKLOG, MTCR_QT_CONS_QTY, MTCR_QT_PROM_QTY, MTCR_QT_ASN_QTY, MTCR_QT_INB_QTY, MTCR_CD_AGING_CAT_INB, MTCR_QT_QUALITY_AREA_QTY, MTCR_CD_AGING_CAT_QLTY_AREA, MTCR_QT_DEC_AREA_QTY, MTCR_CD_AGING_CAT_DEC_AREA, MTCR_QT_EXT_QTY, MTCR_CD_AGING_CAT_EXT, MTCR_QT_OTHER_CLICK_QTY, MTCR_CD_AGING_CAT_OTHER, MTCR_QT_WIP_LN_QTY, MTCR_QT_WIP_HARD_QTY, MTCR_QT_MOUNT_QTY, MTCR_NT_MOUNT_COMP_PATH, MTCR_QT_STOCK_QTY, MTCR_CD_AGING_CAT_STOCK, MTCR_QT_W999_QTY, MTCR_QT_MISS_QTY, MTCR_QT_CALC_MISS_QTY, MTCR_QT_CALC_MISS_QTY_PROM, MTCR_QT_REQ_QTY, MTCR_QT_REQ_PROG_QTY, MTCR_ID_COVC_COVERAGE_CD, MTCR_CD_COVERAGE_CD, MTCR_NR_COVERAGE_VAL, MTCR_QT_COVERAGE_QTY, MTCR_ID_COVC_COVERAGE_PROM, MTCR_CD_COVERAGE_PROM, MTCR_NR_COVERAGE_VAL_PROM, MTCR_QT_COVERAGE_QTY_PROM, MTCR_NR_WST_COV_VAL, MTCR_QT_WST_COV_QTY, MTCR_ID_TIME_WST_COV, MTCR_NR_WST_COV_VAL_PROM, MTCR_QT_WST_COV_QTY_PROM, MTCR_ID_TIME_WST_COV_PROM, MTCR_FL_STOP_MARK, MTCR_FL_PROM_MARK, MTCR_FL_CRITICAL_MARK, MTCR_FL_MTO_MARK, MTCR_FL_LEAF_COMP_MARK, MTCR_FL_SEQ_LIST_MARK, MTCR_FL_CALC_MISS_MARK, MTCR_FL_CALC_MISS_PROM_MARK, MTCR_FL_MISS_MARK, MTCR_QT_MIN_LEAD_TIME, MTCR_QT_MAX_LEAD_TIME, MTCR_ID_BATCH_ID, MTCR_CD_SOURCE_SYSTEM, MTCR_CD_OPERATOR_CODE, MTCR_DT_INS_ROW, MTCR_DT_UPD_ROW)
SELECT MTCR_CD_PLANT_CD,
       0 AS MTCR_ID_MTCR,
       MTCR_ID_REQU_REQ_CAT,
       MTCR_CD_REQ_CAT,
       MTCR_ID_VEHI_VAN,
       MTCR_CD_VAN,
       TO_NUMBER (TO_CHAR (MTCR_DT_REQ_DT, 'J')) AS MTCR_ID_TIME_REQ_DT,
       MTCR_DT_REQ_DT,
       TO_NUMBER (TO_CHAR (MTCR_DT_INDREQ_REQ_DT, 'J')) AS MTCR_ID_TIME_INDREQ_REQ_DT,
       MTCR_DT_INDREQ_REQ_DT,
       MTCR_CD_PROD_LINE,
       MTCR_CD_IND_ID,
       MTCR_CD_SALE_ORD_NBR,
       MTCR_CD_SALE_ORD_LN,
       MTCR_CD_SCHED_LN_ID,
       MTCR_ID_MTRL_PART_NBR_IR,
       MTCR_CD_PART_NBR_IR,
       MTCR_ID_CUST_CUST_CD,
       MTCR_CD_CUST_CD,
       MTCR_ID_MTRL_COMP,
       MTCR_CD_COMP,
       MTCR_CD_VAN_STU,
       MTCR_QT_BOM_QTY,
       MTCR_QT_CONSUMED_QTY,
       MTCR_QT_MOUNTED_QTY,
       MTCR_CD_COMP_PROCUR_TP,
       MTCR_CD_COMP_ASS_MARK,
       MTCR_ID_VEND_SUPPL_CD,
       MTCR_CD_SUPPL_CD,
       MTCR_QT_BACKLOG,
       MTCR_QT_CONS_QTY,
       MTCR_QT_PROM_QTY,
       MTCR_QT_ASN_QTY,
       MTCR_QT_INB_QTY,
       MTCR_CD_AGING_CAT_INB,
       MTCR_QT_QUALITY_AREA_QTY,
       MTCR_CD_AGING_CAT_QLTY_AREA,
       MTCR_QT_DEC_AREA_QTY,
       MTCR_CD_AGING_CAT_DEC_AREA,
       MTCR_QT_EXT_QTY,
       MTCR_CD_AGING_CAT_EXT,
       MTCR_QT_OTHER_CLICK_QTY,
       MTCR_CD_AGING_CAT_OTHER,
       MTCR_QT_WIP_LN_QTY,
       MTCR_QT_WIP_HARD_QTY,
       MTCR_QT_MOUNT_QTY,
       MTCR_NT_MOUNT_COMP_PATH,
       MTCR_QT_STOCK_QTY,
       MTCR_CD_AGING_CAT_STOCK,
       MTCR_QT_W999_QTY,
       MTCR_QT_MISS_QTY,
       MTCR_QT_CALC_MISS_QTY,
       MTCR_QT_CALC_MISS_QTY_PROM,
       MTCR_QT_REQ_QTY,
       MTCR_QT_REQ_PROG_QTY,
       MTCR_ID_COVC_COVERAGE_CD,
       MTCR_CD_COVERAGE_CD,
       MTCR_NR_COVERAGE_VAL,
       MTCR_QT_COVERAGE_QTY,
       MTCR_ID_COVC_COVERAGE_PROM,
       MTCR_CD_COVERAGE_PROM,
       MTCR_NR_COVERAGE_VAL_PROM,
       MTCR_QT_COVERAGE_QTY_PROM,
       MAX (MTCR_NR_COVERAGE_VAL) OVER (PARTITION BY MTCR_CD_PLANT_CD,
                                                     MTCR_CD_COMP) MTCR_NR_WST_COV_VAL,
                                       SUM (MTCR_QT_COVERAGE_QTY) KEEP (DENSE_RANK FIRST
                                                                        ORDER BY MTCR_NR_COVERAGE_VAL DESC NULLS LAST) OVER (PARTITION BY MTCR_CD_PLANT_CD,
                                                                                                                                          MTCR_CD_COMP) AS MTCR_QT_WST_COV_QTY,
                                                                                                                            MIN (TO_CHAR (NVL (MTCR_DT_REQ_DT, TO_DATE (P_ELT_DT_JOB_DATE_ELAB, 'YYYYMMDD')), 'J')) KEEP (DENSE_RANK FIRST
                                                                                                                                                                                                                          ORDER BY MTCR_NR_COVERAGE_VAL DESC NULLS LAST) OVER (PARTITION BY MTCR_CD_PLANT_CD,
                                                                                                                                                                                                                                                                                            MTCR_CD_COMP) AS MTCR_ID_TIME_WST_COV,
                                                                                                                                                                                                                                                                              MAX (MTCR_NR_COVERAGE_VAL_PROM) OVER (PARTITION BY MTCR_CD_PLANT_CD,
                                                                                                                                                                                                                                                                                                                                 MTCR_CD_COMP) AS MTCR_NR_WST_COV_VAL_PROM,
                                                                                                                                                                                                                                                                                                                   SUM (MTCR_QT_COVERAGE_QTY_PROM) KEEP (DENSE_RANK FIRST
                                                                                                                                                                                                                                                                                                                                                         ORDER BY MTCR_NR_COVERAGE_VAL_PROM DESC NULLS LAST) OVER (PARTITION BY MTCR_CD_PLANT_CD,
                                                                                                                                                                                                                                                                                                                                                                                                                                MTCR_CD_COMP) AS MTCR_QT_WST_COV_QTY_PROM,
                                                                                                                                                                                                                                                                                                                                                                                                                  MIN (TO_CHAR (NVL (MTCR_DT_REQ_DT, TO_DATE (P_ELT_DT_JOB_DATE_ELAB, 'YYYYMMDD')), 'J')) KEEP (DENSE_RANK FIRST
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ORDER BY MTCR_NR_COVERAGE_VAL_PROM DESC NULLS LAST) OVER (PARTITION BY MTCR_CD_PLANT_CD,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       MTCR_CD_COMP) AS MTCR_ID_TIME_WST_COV_PROM,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         MTCR_FL_STOP_MARK,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         MTCR_FL_PROM_MARK,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         MTCR_FL_CRITICAL_MARK,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         MTCR_FL_MTO_MARK,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         MTCR_FL_LEAF_COMP_MARK,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         MTCR_FL_SEQ_LIST_MARK,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         MTCR_FL_CALC_MISS_MARK,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         MTCR_FL_CALC_MISS_PROM_MARK,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         CASE
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             WHEN MTCR_QT_MISS_QTY>0 THEN '1'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ELSE '0'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         END AS MTCR_FL_MISS_MARK,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         MTCR_QT_MIN_LEAD_TIME,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         MTCR_QT_MAX_LEAD_TIME,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         NVL (P_ELT_ID_BATCH, N_ELT_ID_JOB_LOG) AS MTCR_ID_BATCH_ID,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         'MA' AS MTCR_CD_SOURCE_SYSTEM,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         'ETL' AS MCMW_CD_OPERATOR_CODE,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         SYSDATE AS MCMW_DT_INS_ROW,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         SYSDATE AS MCMW_DT_UPD_ROW
FROM
  (SELECT MCRL_CD_PLANT_CD AS MTCR_CD_PLANT_CD,
          MCRL_ID_REQU_REQ_CAT AS MTCR_ID_REQU_REQ_CAT,
          MCRL_CD_REQ_CAT AS MTCR_CD_REQ_CAT,
          MCRL_ID_VEHI_VAN AS MTCR_ID_VEHI_VAN,
          MCRL_CD_VAN AS MTCR_CD_VAN,
          MCRL_ID_TIME_REQ_DT AS MTCR_ID_TIME_REQ_DT,
          MCRL_DT_REQ_DT AS MTCR_DT_REQ_DT,
          MCRL_ID_TIME_INDREQ_REQ_DT AS MTCR_ID_TIME_INDREQ_REQ_DT,
          MCRL_DT_INDREQ_REQ_DT AS MTCR_DT_INDREQ_REQ_DT,
          MCRL_CD_PROD_LINE AS MTCR_CD_PROD_LINE,
          MCRL_CD_IND_ID AS MTCR_CD_IND_ID,
          MCRL_CD_SALE_ORD_NBR AS MTCR_CD_SALE_ORD_NBR,
          MCRL_CD_SALE_ORD_LN AS MTCR_CD_SALE_ORD_LN,
          MCRL_CD_SCHED_LN_ID AS MTCR_CD_SCHED_LN_ID,
          MCRL_ID_MTRL_PART_NBR_IR AS MTCR_ID_MTRL_PART_NBR_IR,
          MCRL_CD_PART_NBR_IR AS MTCR_CD_PART_NBR_IR,
          MCRL_ID_CUST_CUST_CD AS MTCR_ID_CUST_CUST_CD,
          MCRL_CD_CUST_CD AS MTCR_CD_CUST_CD,
          MCRL_ID_MTRL_COMP AS MTCR_ID_MTRL_COMP,
          MCRL_CD_COMP AS MTCR_CD_COMP,
          MCRL_CD_VAN_STU AS MTCR_CD_VAN_STU,
          MCRL_QT_BOM_QTY AS MTCR_QT_BOM_QTY,
          MCRL_QT_CONSUMED_QTY AS MTCR_QT_CONSUMED_QTY,
          MCRL_QT_MOUNTED_QTY AS MTCR_QT_MOUNTED_QTY,
          MCRL_CD_COMP_PROCUR_TP AS MTCR_CD_COMP_PROCUR_TP,
          MCRL_CD_COMP_ASS_MARK AS MTCR_CD_COMP_ASS_MARK,
          MCRL_ID_VEND_SUPPL_CD AS MTCR_ID_VEND_SUPPL_CD,
          MCRL_CD_SUPPL_CD AS MTCR_CD_SUPPL_CD,
          MCRL_QT_BACKLOG AS MTCR_QT_BACKLOG,
          MCRL_QT_CONS_QTY AS MTCR_QT_CONS_QTY,
          MCRL_QT_PROM_QTY AS MTCR_QT_PROM_QTY,
          MCRL_QT_ASN_QTY AS MTCR_QT_ASN_QTY,
          MCRL_QT_INB_QTY AS MTCR_QT_INB_QTY,
          MCRL_CD_AGING_CAT_INB AS MTCR_CD_AGING_CAT_INB,
          MCRL_QT_QUALITY_AREA_QTY AS MTCR_QT_QUALITY_AREA_QTY,
          MCRL_CD_AGING_CAT_QLTY_AREA AS MTCR_CD_AGING_CAT_QLTY_AREA,
          MCRL_QT_DEC_AREA_QTY AS MTCR_QT_DEC_AREA_QTY,
          MCRL_CD_AGING_CAT_DEC_AREA AS MTCR_CD_AGING_CAT_DEC_AREA,
          MCRL_QT_EXT_QTY AS MTCR_QT_EXT_QTY,
          MCRL_CD_AGING_CAT_EXT AS MTCR_CD_AGING_CAT_EXT,
          MCRL_QT_OTHER_CLICK_QTY AS MTCR_QT_OTHER_CLICK_QTY,
          MCRL_CD_AGING_CAT_OTHER AS MTCR_CD_AGING_CAT_OTHER,
          MCRL_QT_WIP_LN_QTY AS MTCR_QT_WIP_LN_QTY,
          MCRL_QT_WIP_HARD_QTY AS MTCR_QT_WIP_HARD_QTY,
          MCRL_QT_MOUNT_QTY AS MTCR_QT_MOUNT_QTY,
          MCRL_NT_MOUNT_COMP_PATH AS MTCR_NT_MOUNT_COMP_PATH,
          MCRL_QT_STOCK_QTY AS MTCR_QT_STOCK_QTY,
          MCRL_CD_AGING_CAT_STOCK AS MTCR_CD_AGING_CAT_STOCK,
          MCRL_QT_W999_QTY AS MTCR_QT_W999_QTY,
          MCRL_QT_MISS_QTY AS MTCR_QT_MISS_QTY,
          MCRL_QT_CALC_MISS_QTY AS MTCR_QT_CALC_MISS_QTY,
          MCRL_QT_CALC_MISS_QTY_PROM AS MTCR_QT_CALC_MISS_QTY_PROM,
          MCRL_QT_REQ_QTY AS MTCR_QT_REQ_QTY,
          MCRL_QT_REQ_PROG_QTY AS MTCR_QT_REQ_PROG_QTY,
          MCRL_ID_COVC_COVERAGE_CD AS MTCR_ID_COVC_COVERAGE_CD,
          MCRL_CD_COVERAGE_CD AS MTCR_CD_COVERAGE_CD,
          MCRL_NR_COVERAGE_VAL AS MTCR_NR_COVERAGE_VAL,
          MCRL_QT_COVERAGE_QTY AS MTCR_QT_COVERAGE_QTY,
          MCRL_ID_COVC_COVERAGE_PROM AS MTCR_ID_COVC_COVERAGE_PROM,
          MCRL_CD_COVERAGE_PROM AS MTCR_CD_COVERAGE_PROM,
          MCRL_NR_COVERAGE_VAL_PROM AS MTCR_NR_COVERAGE_VAL_PROM,
          MCRL_QT_COVERAGE_QTY_PROM AS MTCR_QT_COVERAGE_QTY_PROM,
          MCRL_FL_STOP_MARK AS MTCR_FL_STOP_MARK,
          MCRL_FL_PROM_MARK AS MTCR_FL_PROM_MARK,
          MCRL_FL_CRITICAL_MARK AS MTCR_FL_CRITICAL_MARK,
          MCRL_FL_MTO_MARK AS MTCR_FL_MTO_MARK,
          MCRL_FL_LEAF_COMP_MARK AS MTCR_FL_LEAF_COMP_MARK,
          MCRL_FL_SEQ_LIST_MARK AS MTCR_FL_SEQ_LIST_MARK,
          MCRL_FL_CALC_MISS_MARK AS MTCR_FL_CALC_MISS_MARK,
          MCRL_FL_CALC_MISS_PROM_MARK AS MTCR_FL_CALC_MISS_PROM_MARK,
          MCRL_FL_MISS_MARK AS MTCR_FL_MISS_MARK,
          MCRL_QT_MIN_LEAD_TIME AS MTCR_QT_MIN_LEAD_TIME,
          MCRL_QT_MAX_LEAD_TIME AS MTCR_QT_MAX_LEAD_TIME
   FROM TABLE (DDWH02_DM_MA.PKG_DM_MAT_COV_RULES_CALC.MC_MCRL_RULES_CALC (
                                                                          CURSOR
                                                                            (SELECT *
                                                                             FROM DDWH02_DM_MA.TW_MCMW_MC_MAT_COVERAGE_WORK
                                                                             WHERE MCMW_CD_PLANT_CD = P_ELT_CD_PLANT ))))