INSERT INTO DDWH02_DM_MA.TFCT_CDET_CALL_DETAILS TRG (CDET_CD_PLANT_CD, CDET_ID_CDET, CDET_ID_TIME_SNAPSHOT, CDET_ID_MAMD_PART_NBR, CDET_CD_PART_NBR, CDET_ID_TIME_ASSIGN_DT, CDET_ID_TIME_ORD_ASSIGN_DT, CDET_CD_CALL_GROUP_ID, CDET_CD_CALL_ORD_NBR, CDET_CD_CALL_ORD_NBR_LN, CDET_ID_CTMD_CALL_TP, CDET_CD_ORD_TP, CDET_ID_TIME_EXPC_CLOSE_DT, CDET_DT_EXPC_CLOSE_DT, CDET_ID_TIME_EFF_CLOSE_DT, CDET_ID_TIME_ORD_EFF_CLOSE_DT, CDET_ID_TIME_TUGGING_DT, CDET_DT_TUGGING_DT, CDET_NR_AGING, CDET_QT_REQ_QTY, CDET_QT_SHIPP_QTY, CDET_ID_STAT_STU, CDET_CD_STU, CDET_CD_REFURNISH_BUILDING, CDET_CD_REFURNISH_LOC, CDET_CD_KIT_ID, CDET_CD_KITTER_ID, CDET_CD_TUGGER_ID, CDET_CD_ROUTE, CDET_CD_SRC_BUILDING, CDET_CD_SRC_LOC, CDET_CD_SRC_ORG, CDET_CD_BIN_SRC, CDET_CD_DEST_LOC, CDET_CD_DEST_ORG, CDET_CD_USER_ID, CDET_ID_VHMD_VAN, CDET_CD_VAN, CDET_ID_PLST, CDET_CD_WCTR_CD, CDET_CD_EFF_ORD, CDET_CD_OP, CDET_NR_AGING_DAYS, CDET_NR_AGING_HOURS, CDET_FL_NEW_CALL, CDET_FL_CLOSED_CALL, CDET_FL_BACKLOG, CDET_FL_CLOSED_ADVANCE, CDET_FL_CLOSED_DELAY, CDET_ID_BATCH_ID, CDET_CD_SOURCE_SYSTEM, CDET_CD_OPERATOR_CODE, CDET_DT_INS_ROW, CDET_DT_UPD_ROW)
SELECT QRY.CDET_CD_PLANT_CD,
       DDWH02_DM_MA.SEQ_CDET_TFCT01.NEXTVAL,
       QRY.CDET_ID_TIME_SNAPSHOT,
       QRY.CDET_ID_MAMD_PART_NBR,
       QRY.CDET_CD_PART_NBR,
       QRY.CDET_ID_TIME_ASSIGN_DT,
       QRY.CDET_ID_TIME_ORD_ASSIGN_DT,
       QRY.CDET_CD_CALL_GROUP_ID,
       QRY.CDET_CD_CALL_ORD_NBR,
       QRY.CDET_CD_CALL_ORD_NBR_LN,
       QRY.CDET_ID_CTMD_CALL_TP,
       QRY.CDET_CD_ORD_TP,
       QRY.CDET_ID_TIME_EXPC_CLOSE_DT,
       QRY.CDET_DT_EXPC_CLOSE_DT,
       QRY.CDET_ID_TIME_EFF_CLOSE_DT,
       QRY.CDET_ID_TIME_ORD_EFF_CLOSE_DT,
       QRY.TBC_NUMBER,
       TO_DATE (QRY.TBC_DATA, 'YYYY-MM-DD HH24:MI:SS'),
       QRY.CDET_NR_AGING,
       QRY.CDET_QT_REQ_QTY,
       QRY.CDET_QT_SHIPP_QTY,
       QRY.CDET_ID_STAT_STU,
       QRY.CDET_CD_STU,
       QRY.CDET_CD_REFURNISH_BUILDING,
       QRY.CDET_CD_REFURNISH_LOC,
       QRY.CDET_CD_KIT_ID,
       QRY.CDET_CD_KITTER_ID,
       QRY.CDET_CD_TUGGER_ID,
       QRY.CDET_CD_ROUTE,
       QRY.CDET_CD_SRC_BUILDING,
       QRY.CDET_CD_SRC_LOC,
       QRY.CDET_CD_SRC_ORG,
       QRY.CDET_CD_BIN_SRC,
       QRY.CDET_CD_DEST_LOC,
       QRY.CDET_CD_DEST_ORG,
       QRY.CDET_CD_USER_ID,
       QRY.CDET_ID_VHMD_VAN,
       QRY.CDET_CD_VAN,
       QRY.CDET_ID_PLST,
       QRY.CDET_CD_WCTR_CD,
       QRY.CDET_CD_EFF_ORD,
       QRY.CDET_CD_OP,
       QRY.CDET_NR_AGING_DAYS,
       QRY.CDET_NR_AGING_HOURS,
       QRY.CDET_FL_NEW_CALL,
       QRY.CDET_FL_CLOSED_CALL,
       QRY.CDET_FL_BACKLOG,
       QRY.CDET_FL_CLOSED_ADVANCE,
       QRY.CDET_FL_CLOSED_DELAY,
       QRY.CDET_ID_BATCH_ID,
       QRY.CDET_CD_SOURCE_SYSTEM,
       'ETL',
       SYSDATE,
       SYSDATE
FROM
  (SELECT CALL_CD_PLANT_CD AS CDET_CD_PLANT_CD,
          NULL AS CDET_ID_CDET,
          CDET_ID_TIME_SNAPSHOT AS CDET_ID_TIME_SNAPSHOT,
          WHMR_ID_MAMD_PART_NBR AS CDET_ID_MAMD_PART_NBR,
          WHMR_CD_PART_NBR AS CDET_CD_PART_NBR,
          WHMR_DT_ASSIGN_DT AS CDET_ID_TIME_ASSIGN_DT,
          NVL (WHMR_DT_ASSIGN_DT_MIN, -2) AS CDET_ID_TIME_ORD_ASSIGN_DT,
          CDET_CD_CALL_GROUP_ID AS CDET_CD_CALL_GROUP_ID,
          CALL_CD_CALL_ORD_NBR AS CDET_CD_CALL_ORD_NBR,
          CALL_CD_CALL_ORD_NBR_LN AS CDET_CD_CALL_ORD_NBR_LN,
          CALL_ID_CTMD_CALL_TP AS CDET_ID_CTMD_CALL_TP,
          CALL_CD_CALL_ORD_TP AS CDET_CD_ORD_TP,
          CDET_ID_TIME_EXPC_CLOSE_DT AS CDET_ID_TIME_EXPC_CLOSE_DT,
          CDET_DT_EXPC_CLOSE_DT AS CDET_DT_EXPC_CLOSE_DT,
          NVL (CALL_DT_EFF_CLOSE_DT_NUMBER, -2) AS CDET_ID_TIME_EFF_CLOSE_DT,
          NVL (CALL_DT_EFF_CLOSE_DT_MAX, -2) AS CDET_ID_TIME_ORD_EFF_CLOSE_DT,
          -2 AS TBC_NUMBER,
          '1900-01-01 00:00:00' AS TBC_DATA,
          CDET_NR_AGING AS CDET_NR_AGING,
          WHMR_QT_REQ_QTY AS CDET_QT_REQ_QTY,
          WHMR_QT_SHIPP_QTY AS CDET_QT_SHIPP_QTY,
          WHMR_ID_SUMD_STU AS CDET_ID_STAT_STU,
          WHMR_CD_STU AS CDET_CD_STU,
          CALL_CD_REFURNISH_BUILDING AS CDET_CD_REFURNISH_BUILDING,
          CALL_CD_REFURNISH_LOC AS CDET_CD_REFURNISH_LOC,
          CALL_CD_KIT_ID AS CDET_CD_KIT_ID,
          CALL_CD_KITTER_ID AS CDET_CD_KITTER_ID,
          CALL_CD_TUGGER_ID AS CDET_CD_TUGGER_ID,
          CALL_CD_ROUTE AS CDET_CD_ROUTE,
          INMO_CD_SRC_BUILDING AS CDET_CD_SRC_BUILDING,
          NVL (INMO_CD_SRC_LOC, DDWH02_DM_MA.FUNC_NOT_APPLICABLE_CODE ()) AS CDET_CD_SRC_LOC,
          MBUD_CD_DEP_CD_M1 AS CDET_CD_SRC_ORG,
          INMO_CD_BIN_SRC AS CDET_CD_BIN_SRC,
          NVL (INMO_CD_DEST_LOC, CALL_CD_REFURNISH_LOC) AS CDET_CD_DEST_LOC,
          MBUD_CD_DEP_CD_M2 AS CDET_CD_DEST_ORG,
          INMO_CD_USER_ID AS CDET_CD_USER_ID,
          CALL_ID_VHMD_VAN AS CDET_ID_VHMD_VAN,
          CALL_CD_VAN AS CDET_CD_VAN,
          CALL_ID_PLMD_WCTR_CD AS CDET_ID_PLST,
          CALL_CD_WCTR_CD AS CDET_CD_WCTR_CD,
          CALL_CD_EFF_ORD AS CDET_CD_EFF_ORD,
          CALL_CD_OP AS CDET_CD_OP,
          ROUND (CDET_NR_AGING_DAYS, 7) AS CDET_NR_AGING_DAYS,
          ROUND (CDET_NR_AGING_HOURS, 7) AS CDET_NR_AGING_HOURS,
          CDET_FL_NEW_CALL AS CDET_FL_NEW_CALL,
          CDET_FL_CLOSED_CALL AS CDET_FL_CLOSED_CALL,
          CDET_FL_BACKLOG AS CDET_FL_BACKLOG,
          '1' AS CDET_FL_CLOSED_ADVANCE,
          '1' AS CDET_FL_CLOSED_DELAY,
          CALL_ID_BATCH_ID AS CDET_ID_BATCH_ID,
          CALL_CD_SOURCE_SYSTEM AS CDET_CD_SOURCE_SYSTEM
   FROM
     (SELECT SRC.CALL_CD_PLANT_CD,
             SRC.CDET_ID_TIME_SNAPSHOT,
             SRC.WHMR_ID_MAMD_PART_NBR,
             SRC.WHMR_CD_PART_NBR,
             NVL (SRC.WHMR_DT_ASSIGN_DT, -2) WHMR_DT_ASSIGN_DT,
             SRC.WHMR_DT_ASSIGN_DT_MIN,
             SRC.CALL_CD_CALL_ORD_NBR AS CDET_CD_CALL_GROUP_ID,
             SRC.CALL_CD_CALL_ORD_NBR,
             SRC.CALL_CD_CALL_ORD_NBR_LN,
             SRC.CALL_ID_CTMD_CALL_TP,
             SRC.CALL_CD_CALL_ORD_TP,
             SRC.CDET_ID_TIME_EXPC_CLOSE_DT,
             SRC.CDET_DT_EXPC_CLOSE_DT,
             SRC.CALL_DT_EFF_CLOSE_DT_NUMBER,
             SRC.CALL_DT_EFF_CLOSE_DT_MAX,
             SRC.CDET_NR_AGING,
             SRC.WHMR_QT_REQ_QTY,
             SRC.WHMR_QT_SHIPP_QTY,
             SRC.WHMR_ID_SUMD_STU,
             SRC.WHMR_CD_STU,
             SRC.CALL_CD_REFURNISH_BUILDING,
             SRC.CALL_CD_REFURNISH_LOC,
             SRC.CALL_CD_KIT_ID,
             SRC.CALL_CD_KITTER_ID,
             SRC.CALL_CD_TUGGER_ID,
             SRC.CALL_CD_ROUTE,
             INMO_CD_SRC_BUILDING,
             INMO_CD_SRC_LOC,
             MBUD_CD_DEP_CD_M1,
             INMO_CD_BIN_SRC,
             INMO_CD_DEST_LOC,
             MBUD_CD_DEP_CD_M2,
             INMO_CD_USER_ID,
             SRC.CALL_ID_VHMD_VAN,
             SRC.CALL_CD_VAN,
             SRC.CALL_ID_PLMD_WCTR_CD,
             SRC.CALL_CD_WCTR_CD,
             SRC.CALL_CD_EFF_ORD,
             SRC.CALL_CD_OP,
             SRC.CDET_NR_AGING_DAYS,
             SRC.CDET_NR_AGING_HOURS,
             CASE
                 WHEN SRC.WHMR_DT_ASSIGN_DT = SRC.CDET_ID_TIME_SNAPSHOT THEN '1'
             END AS CDET_FL_NEW_CALL,
             CASE
                 WHEN SRC.CALL_DT_EFF_CLOSE_DT_NUMBER = SRC.CDET_ID_TIME_SNAPSHOT THEN '1'
             END AS CDET_FL_CLOSED_CALL,
             CASE
                 WHEN SRC.CDET_ID_TIME_EXPC_CLOSE_DT <= SRC.CDET_ID_TIME_SNAPSHOT
                      AND CALL_DT_EFF_CLOSE_DT_NUMBER IS NULL THEN '1'
             END CDET_FL_BACKLOG,
             NVL (P_ELT_ID_BATCH, N_ELT_ID_JOB_LOG) AS CALL_ID_BATCH_ID,
             SRC.CALL_CD_SOURCE_SYSTEM
      FROM
        (SELECT CALL_CD_PLANT_CD,
                CALL_ID_CALLS,
                TO_NUMBER (TO_CHAR (TO_DATE (P_ELT_DT_JOB_DATE_ELAB, 'YYYYMMDD'), 'J')) CDET_ID_TIME_SNAPSHOT,
                WHMR_ID_MAMD_PART_NBR,
                WHMR_CD_PART_NBR,
                TO_NUMBER (TO_CHAR (WHMR_DT_ASSIGN_DT, 'J')) WHMR_DT_ASSIGN_DT,
                WHMR_DT.WHMR_DT_ASSIGN_DT_MIN,
                TD_CALL_CALLS.CALL_CD_CALL_ORD_NBR,
                CALL_CD_CALL_ORD_NBR_LN,
                CALL_ID_CTMD_CALL_TP,
                CALL_CD_CALL_ORD_TP,
                TO_NUMBER (TO_CHAR (WHMR_DT_EXPC_DLVR_DT, 'J')) CDET_ID_TIME_EXPC_CLOSE_DT,
                WHMR_DT_EXPC_DLVR_DT AS CDET_DT_EXPC_CLOSE_DT,
                CALL_DT_EFF_CLOSE_DT,
                CALL_DT_EFF_CLOSE_DT AS CALL_DT_EFF_CLOSE_DT_DATE,
                TO_NUMBER (TO_CHAR (CALL_DT_EFF_CLOSE_DT, 'J')) CALL_DT_EFF_CLOSE_DT_NUMBER,
                CALL_DT_EFF_CLOSE_DT_MAX,

           (SELECT COUNT (PCAL_PC_WK_DAY_PERCENT)
            FROM DDWH01_DW_MA.TM_PCAL_PLANT_CALENDAR
            WHERE (PCAL_DT_DAY BETWEEN WHMR_DT_ASSIGN_DT AND TO_DATE (P_ELT_DT_JOB_DATE_ELAB, 'YYYYMMDD'))
              AND PCAL_PC_WK_DAY_PERCENT>0
              AND WHMR_CD_STU <> 'CHIUSA'
              AND PCAL_CD_PLANT_CD = P_ELT_CD_PLANT ) CDET_NR_AGING,
                WHMR_QT_REQ_QTY,
                WHMR_QT_SHIPP_QTY,
                CALL_CD_REFURNISH_BUILDING,
                CALL_CD_REFURNISH_LOC,
                CALL_CD_KIT_ID,
                CALL_CD_KITTER_ID,
                CALL_CD_TUGGER_ID,
                CALL_CD_ROUTE,
                INMO_CD_SRC_BUILDING,
                INMO_CD_SRC_LOC,
                CASE
                    WHEN M1.MBUD_CD_DEP_CD IS NULL THEN 'OTHERS'
                    ELSE M1.MBUD_CD_DEP_CD
                END AS MBUD_CD_DEP_CD_M1,
                INMO_CD_BIN_SRC,
                INMO_CD_DEST_LOC,
                CASE
                    WHEN M2.MBUD_CD_DEP_CD IS NULL THEN 'OTHERS'
                    ELSE M2.MBUD_CD_DEP_CD
                END AS MBUD_CD_DEP_CD_M2,
                INMO_CD_USER_ID,
                CALL_ID_VHMD_VAN,
                CALL_CD_VAN,
                CALL_ID_PLMD_WCTR_CD,
                CALL_CD_WCTR_CD,
                CALL_CD_EFF_ORD,
                CALL_CD_OP,
                (DDWH01_DW_MA.PKG_CALENDAR.GETAGE (TO_DATE (P_ELT_DT_JOB_DATE_ELAB, 'YYYYMMDD') +1, WHMR_DT_INS_DT, CALL_NT_AGE) - DDWH01_DW_MA.PKG_CALENDAR.GETAGE (WHMR_DT_ASSIGN_DT, WHMR_DT_INS_DT, CALL_NT_AGE)) /24 AS CDET_NR_AGING_DAYS,
                DDWH01_DW_MA.PKG_CALENDAR.GETAGE (TO_DATE (P_ELT_DT_JOB_DATE_ELAB, 'YYYYMMDD') +1, WHMR_DT_INS_DT, CALL_NT_AGE) - DDWH01_DW_MA.PKG_CALENDAR.GETAGE (WHMR_DT_ASSIGN_DT, WHMR_DT_INS_DT, CALL_NT_AGE) AS CDET_NR_AGING_HOURS,
                CALL_CD_SOURCE_SYSTEM,
                WHMR_ID_SUMD_STU,
                WHMR_CD_STU
         FROM
           (SELECT *
            FROM DDWH01_DW_MA.TD_CALL_CALLS
            WHERE CALL_CD_PLANT_CD = P_ELT_CD_PLANT ) TD_CALL_CALLS
         LEFT JOIN
           (SELECT TO_NUMBER (TO_CHAR (MAX (CALL_DT_EFF_CLOSE_DT) , 'J')) AS CALL_DT_EFF_CLOSE_DT_MAX,
                   CALL_CD_CALL_ORD_NBR
            FROM DDWH01_DW_MA.TD_CALL_CALLS CALLS_SUB
            WHERE
                (SELECT COUNT (*)
                 FROM DDWH01_DW_MA.TD_CALL_CALLS
                 WHERE CALL_CD_CALL_ORD_NBR = CALLS_SUB.CALL_CD_CALL_ORD_NBR
                   AND CALL_DT_EFF_CLOSE_DT IS NULL
                   AND CALL_CD_PLANT_CD = P_ELT_CD_PLANT ) = 0
              AND CALL_CD_PLANT_CD = P_ELT_CD_PLANT
            GROUP BY CALL_CD_CALL_ORD_NBR) CALL_DT ON TD_CALL_CALLS.CALL_CD_CALL_ORD_NBR = CALL_DT.CALL_CD_CALL_ORD_NBR
         LEFT JOIN
           (SELECT *
            FROM DDWH01_DW_MA.TT_WHMR_WH_MAT_REQ
            WHERE WHMR_CD_PLANT_CD = P_ELT_CD_PLANT ) TT_WHMR_WH_MAT_REQ ON TD_CALL_CALLS.CALL_CD_PLANT_CD=WHMR_CD_PLANT_CD
         AND TD_CALL_CALLS.CALL_ID_WHMR_WH_MAT_REQ = WHMR_ID_WH_MAT_REQ
         AND TD_CALL_CALLS.CALL_CD_CALL_ORD_NBR = WHMR_CD_ORD_NBR
         AND TD_CALL_CALLS.CALL_CD_CALL_ORD_NBR_LN = WHMR_CD_ORD_NBR_LN
         AND TD_CALL_CALLS.CALL_CD_CALL_ORD_TP = WHMR_CD_ORD_TP
         AND WHMR_CD_REQ_TP = 'C'
         LEFT JOIN
           (SELECT TO_NUMBER (TO_CHAR (MIN (WHMR_DT_ASSIGN_DT) , 'J')) AS WHMR_DT_ASSIGN_DT_MIN,
                   WHMR_CD_ORD_NBR
            FROM DDWH01_DW_MA.TT_WHMR_WH_MAT_REQ
            WHERE WHMR_CD_REQ_TP = 'C'
              AND WHMR_CD_PLANT_CD = P_ELT_CD_PLANT
            GROUP BY WHMR_CD_ORD_NBR) WHMR_DT ON TT_WHMR_WH_MAT_REQ.WHMR_CD_ORD_NBR = WHMR_DT.WHMR_CD_ORD_NBR
         LEFT JOIN
           (SELECT MIN (INMO_DT_MOV_CREAT_DT) , MIN (INMO_CD_MOV_ID) AS INMO_CD_MOV_ID,
                                                    INMO_CD_SRC_BUILDING,
                                                    INMO_CD_SRC_LOC,
                                                    INMO_CD_BIN_SRC,
                                                    INMO_CD_DEST_LOC,
                                                    INMO_ID_WHMR_WH_MAT_REQ,
                                                    INMO_CD_USER_ID,
                                                    INMO_CD_PLANT_CD
            FROM DDWH01_DW_MA.TD_INMO_MAT_MOVE
            WHERE INMO_CD_MOV_TP IN ('PIK',
                                     'PRE')
              AND INMO_CD_MOV_SRC= 'TSK'
              AND INMO_CD_ORIG_TASK_ID IS NULL
              AND INMO_CD_PLANT_CD = P_ELT_CD_PLANT
              AND INMO_FL_LOGICAL_STATUS = '1'
            GROUP BY INMO_CD_SRC_BUILDING,
                     INMO_CD_SRC_LOC,
                     INMO_CD_BIN_SRC,
                     INMO_CD_DEST_LOC,
                     INMO_CD_DEST_LOC,
                     INMO_ID_WHMR_WH_MAT_REQ,
                     INMO_CD_USER_ID,
                     INMO_CD_PLANT_CD) TD_INMO_MAT_MOVE ON WHMR_ID_WH_MAT_REQ=INMO_ID_WHMR_WH_MAT_REQ
         AND WHMR_CD_PLANT_CD=INMO_CD_PLANT_CD
         LEFT JOIN
           (SELECT MBUD_CD_MBU_CD AS MBUD_CD_MBU_CD_M1,
                   MBUD_CD_PLANT_CD,
                   MBUD_CD_DEP_CD
            FROM DDWH01_DW_MA.TM_MBUD_MBU_MASTER
            WHERE MBUD_CD_PLANT_CD = P_ELT_CD_PLANT ) M1 ON SUBSTR (TD_INMO_MAT_MOVE.INMO_CD_SRC_LOC, 0, 3) = M1.MBUD_CD_DEP_CD
         LEFT JOIN
           (SELECT MBUD_CD_MBU_CD AS MBUD_CD_MBU_CD_M2,
                   MBUD_CD_DEP_CD,
                   MBUD_CD_PLANT_CD
            FROM DDWH01_DW_MA.TM_MBUD_MBU_MASTER
            WHERE MBUD_CD_PLANT_CD = P_ELT_CD_PLANT ) M2 ON SUBSTR (INMO_CD_DEST_LOC, 0, 3) = M2.MBUD_CD_DEP_CD) SRC) CALL_DETAILS
   WHERE 1=1
     AND (CDET_FL_NEW_CALL ='1'
          OR CDET_FL_CLOSED_CALL='1'
          OR CDET_FL_BACKLOG='1') ) QRY