INSERT INTO DDWH02_DM_MA.TFCT_MTCV_MAT_COVERAGE TRG (MTCV_CD_PLANT_CD, MTCV_ID_MTCV, MTCV_ID_REQU_REQ_CAT, MTCV_CD_REQ_CAT, MTCV_ID_VEHI_VAN, MTCV_CD_VAN, MTCV_ID_TIME_REQ_DT, MTCV_DT_REQ_DT, MTCV_CD_PROD_LINE, MTCV_CD_IND_ID, MTCV_CD_SALE_ORD_NBR, MTCV_CD_SALE_ORD_LN, MTCV_CD_SCHED_LN_ID, MTCV_ID_MTRL_PART_NBR_IR, MTCV_CD_PART_NBR_IR, MTCV_ID_CUST_CUST_CD, MTCV_CD_CUST_CD, MTCV_ID_MTRL_COMP, MTCV_CD_COMP, MTCV_CD_VAN_STU, MTCV_QT_BOM_QTY, MTCV_QT_CONSUMED_QTY, MTCV_QT_MOUNTED_QTY, MTCV_CD_COMP_PROCUR_TP, MTCV_CD_COMP_ASS_MARK, MTCV_ID_VEND_SUPPL_CD, MTCV_CD_SUPPL_CD, MTCV_QT_BACKLOG, MTCV_QT_CONS_QTY, MTCV_QT_PROM_QTY, MTCV_QT_ASN_QTY, MTCV_QT_INB_QTY, MTCV_CD_AGING_CAT_INB, MTCV_QT_QUALITY_AREA_QTY, MTCV_CD_AGING_CAT_QLTY_AREA, MTCV_QT_DEC_AREA_QTY, MTCV_CD_AGING_CAT_DEC_AREA, MTCV_QT_EXT_QTY, MTCV_CD_AGING_CAT_EXT, MTCV_QT_OTHER_CLICK_QTY, MTCV_CD_AGING_CAT_OTHER, MTCV_QT_WIP_LN_QTY, MTCV_QT_WIP_HARD_QTY, MTCV_QT_MOUNT_QTY, MTCV_NT_MOUNT_COMP_PATH, MTCV_QT_STOCK_QTY, MTCV_CD_AGING_CAT_STOCK, MTCV_QT_W999_QTY, MTCV_QT_MISS_QTY, MTCV_QT_CALC_MISS_QTY, MTCV_QT_CALC_MISS_QTY_PROM, MTCV_QT_REQ_QTY, MTCV_QT_REQ_PROG_QTY, MTCV_ID_COVC_COVERAGE_CD, MTCV_CD_COVERAGE_CD, MTCV_NR_COVERAGE_VAL, MTCV_QT_COVERAGE_QTY, MTCV_ID_COVC_COVERAGE_PROM, MTCV_CD_COVERAGE_PROM, MTCV_NR_COVERAGE_VAL_PROM, MTCV_QT_COVERAGE_QTY_PROM, MTCV_NR_WST_COV_VAL, MTCV_QT_WST_COV_QTY, MTCV_ID_TIME_WST_COV, MTCV_NR_WST_COV_VAL_PROM, MTCV_QT_WST_COV_QTY_PROM, MTCV_ID_TIME_WST_COV_PROM, MTCV_FL_STOP_MARK, MTCV_FL_PROM_MARK, MTCV_FL_CRITICAL_MARK, MTCV_FL_MTO_MARK, MTCV_FL_LEAF_COMP_MARK, MTCV_FL_SEQ_LIST_MARK, MTCV_FL_CALC_MISS_MARK, MTCV_FL_CALC_MISS_PROM_MARK, MTCV_FL_MISS_MARK, MTCV_ID_BATCH_ID, MTCV_CD_SOURCE_SYSTEM, MTCV_CD_OPERATOR_CODE, MTCV_DT_INS_ROW, MTCV_DT_UPD_ROW)
SELECT QRY.MTCV_CD_PLANT_CD,
       QRY.MTCV_ID_MTCV,
       QRY.MTCV_ID_REQU_REQ_CAT,
       QRY.MTCV_CD_REQ_CAT,
       QRY.MTCV_ID_VEHI_VAN,
       QRY.MTCV_CD_VAN,
       QRY.MTCV_ID_TIME_REQ_DT,
       QRY.MTCV_DT_REQ_DT,
       QRY.MTCV_CD_PROD_LINE,
       QRY.MTCV_CD_IND_ID,
       QRY.MTCV_CD_SALE_ORD_NBR,
       QRY.MTCV_CD_SALE_ORD_LN,
       QRY.MTCV_CD_SCHED_LN_ID,
       QRY.MTCV_ID_MTRL_PART_NBR_IR,
       QRY.MTCV_CD_PART_NBR_IR,
       QRY.MTCV_ID_CUST_CUST_CD,
       QRY.MTCV_CD_CUST_CD,
       QRY.MTCV_ID_MTRL_COMP,
       QRY.MTCV_CD_COMP,
       QRY.MTCV_CD_VAN_STU,
       QRY.MTCV_QT_BOM_QTY,
       QRY.MTCV_QT_CONSUMED_QTY,
       QRY.MTCV_QT_MOUNTED_QTY,
       QRY.MTCV_CD_COMP_PROCUR_TP,
       QRY.MTCV_CD_COMP_ASS_MARK,
       QRY.MTCV_ID_VEND_SUPPL_CD,
       QRY.MTCV_CD_SUPPL_CD,
       QRY.MTCV_QT_BACKLOG,
       QRY.MTCV_QT_CONS_QTY,
       QRY.MTCV_QT_PROM_QTY,
       QRY.MTCV_QT_ASN_QTY,
       QRY.MTCV_QT_INB_QTY,
       QRY.MTCV_CD_AGING_CAT_INB,
       QRY.MTCV_QT_QUALITY_AREA_QTY,
       QRY.MTCV_CD_AGING_CAT_QLTY_AREA,
       QRY.MTCV_QT_DEC_AREA_QTY,
       QRY.MTCV_CD_AGING_CAT_DEC_AREA,
       QRY.MTCV_QT_EXT_QTY,
       QRY.MTCV_CD_AGING_CAT_EXT,
       QRY.MTCV_QT_OTHER_CLICK_QTY,
       QRY.MTCV_CD_AGING_CAT_OTHER,
       QRY.MTCV_QT_WIP_LN_QTY,
       QRY.MTCV_QT_WIP_HARD_QTY,
       QRY.MTCV_QT_MOUNT_QTY,
       QRY.MTCV_NT_MOUNT_COMP_PATH,
       QRY.MTCV_QT_STOCK_QTY,
       QRY.MTCV_CD_AGING_CAT_STOCK,
       QRY.MTCV_QT_W999_QTY,
       QRY.MTCV_QT_MISS_QTY,
       QRY.MTCV_QT_CALC_MISS_QTY,
       QRY.MTCV_QT_CALC_MISS_QTY_PROM,
       QRY.MTCV_QT_REQ_QTY,
       QRY.MTCV_QT_REQ_PROG_QTY,
       QRY.MTCV_ID_COVC_COVERAGE_CD,
       QRY.MTCV_CD_COVERAGE_CD,
       QRY.MTCV_NR_COVERAGE_VAL,
       QRY.MTCV_QT_COVERAGE_QTY,
       QRY.MTCV_ID_COVC_COVERAGE_PROM,
       QRY.MTCV_CD_COVERAGE_PROM,
       QRY.MTCV_NR_COVERAGE_VAL_PROM,
       QRY.MTCV_QT_COVERAGE_QTY_PROM,
       QRY.MTCV_NR_WST_COV_VAL,
       QRY.MTCV_QT_WST_COV_QTY,
       QRY.MTCV_ID_TIME_WST_COV,
       QRY.MTCV_NR_WST_COV_VAL_PROM,
       QRY.MTCV_QT_WST_COV_QTY_PROM,
       QRY.MTCV_ID_TIME_WST_COV_PROM,
       QRY.MTCV_FL_STOP_MARK,
       QRY.MTCV_FL_PROM_MARK,
       QRY.MTCV_FL_CRITICAL_MARK,
       QRY.MTCV_FL_MTO_MARK,
       QRY.MTCV_FL_LEAF_COMP_MARK,
       QRY.MTCV_FL_SEQ_LIST_MARK,
       QRY.MTCV_FL_CALC_MISS_MARK,
       QRY.MTCV_FL_CALC_MISS_PROM_MARK,
       QRY.MTCV_FL_MISS_MARK,
       QRY.MTCV_ID_BATCH_ID,
       QRY.MTCV_CD_SOURCE_SYSTEM,
       'ETL',
       SYSDATE,
       SYSDATE
FROM
  (SELECT MTCV_CD_PLANT_CD,
          MTCV_ID_MTCV,
          MTCV_ID_REQU_REQ_CAT,
          MTCV_CD_REQ_CAT,
          MTCV_ID_VEHI_VAN,
          MTCV_CD_VAN,
          MTCV_ID_TIME_REQ_DT,
          MTCV_DT_REQ_DT,
          MTCV_CD_PROD_LINE,
          MTCV_CD_IND_ID,
          MTCV_CD_SALE_ORD_NBR,
          MTCV_CD_SALE_ORD_LN,
          MTCV_CD_SCHED_LN_ID,
          MTCV_ID_MTRL_PART_NBR_IR,
          MTCV_CD_PART_NBR_IR,
          MTCV_ID_CUST_CUST_CD,
          MTCV_CD_CUST_CD,
          MTCV_ID_MTRL_COMP,
          MTCV_CD_COMP,
          MTCV_CD_VAN_STU,
          MTCV_QT_BOM_QTY,
          MTCV_QT_CONSUMED_QTY,
          MTCV_QT_MOUNTED_QTY,
          MTCV_CD_COMP_PROCUR_TP,
          MTCV_CD_COMP_ASS_MARK,
          MTCV_ID_VEND_SUPPL_CD,
          MTCV_CD_SUPPL_CD,
          MTCV_QT_BACKLOG,
          MTCV_QT_CONS_QTY,
          MTCV_QT_PROM_QTY,
          MTCV_QT_ASN_QTY,
          MTCV_QT_INB_QTY,
          MTCV_CD_AGING_CAT_INB,
          MTCV_QT_QUALITY_AREA_QTY,
          MTCV_CD_AGING_CAT_QLTY_AREA,
          MTCV_QT_DEC_AREA_QTY,
          MTCV_CD_AGING_CAT_DEC_AREA,
          MTCV_QT_EXT_QTY,
          MTCV_CD_AGING_CAT_EXT,
          MTCV_QT_OTHER_CLICK_QTY,
          MTCV_CD_AGING_CAT_OTHER,
          MTCV_QT_WIP_LN_QTY,
          MTCV_QT_WIP_HARD_QTY,
          MTCV_QT_MOUNT_QTY,
          MTCV_NT_MOUNT_COMP_PATH,
          MTCV_QT_STOCK_QTY,
          MTCV_CD_AGING_CAT_STOCK,
          MTCV_QT_W999_QTY,
          MTCV_QT_MISS_QTY,
          MTCV_QT_CALC_MISS_QTY,
          MTCV_QT_CALC_MISS_QTY_PROM,
          MTCV_QT_REQ_QTY,
          MTCV_QT_REQ_PROG_QTY,
          MTCV_ID_COVC_COVERAGE_CD,
          MTCV_CD_COVERAGE_CD,
          MTCV_NR_COVERAGE_VAL,
          MTCV_QT_COVERAGE_QTY,
          MTCV_ID_COVC_COVERAGE_PROM,
          MTCV_CD_COVERAGE_PROM,
          MTCV_NR_COVERAGE_VAL_PROM,
          MTCV_QT_COVERAGE_QTY_PROM,
          MTCV_NR_WST_COV_VAL,
          MTCV_QT_WST_COV_QTY,
          MTCV_ID_TIME_WST_COV,
          MTCV_NR_WST_COV_VAL_PROM,
          MTCV_QT_WST_COV_QTY_PROM,
          MTCV_ID_TIME_WST_COV_PROM,
          MTCV_FL_STOP_MARK,
          MTCV_FL_PROM_MARK,
          MTCV_FL_CRITICAL_MARK,
          MTCV_FL_MTO_MARK,
          MTCV_FL_LEAF_COMP_MARK,
          MTCV_FL_SEQ_LIST_MARK,
          MTCV_FL_CALC_MISS_MARK,
          MTCV_FL_CALC_MISS_PROM_MARK,
          MTCV_FL_MISS_MARK,
          NVL (P_ELT_ID_BATCH, N_ELT_ID_JOB_LOG) AS MTCV_ID_BATCH_ID,
          MTCV_CD_SOURCE_SYSTEM
   FROM
     (SELECT MTCD_CD_PLANT_CD AS MTCV_CD_PLANT_CD,
             MAX (MTCD_ID_MTCV) KEEP (DENSE_RANK FIRST
                                      ORDER BY MTCD_NR_COVERAGE_VAL DESC NULLS LAST) AS MTCV_ID_MTCV,
                 MTCD_ID_REQU_REQ_CAT AS MTCV_ID_REQU_REQ_CAT,
                 MTCD_CD_REQ_CAT AS MTCV_CD_REQ_CAT,
                 MAX (MTCD_ID_VEHI_VAN) KEEP (DENSE_RANK FIRST
                                              ORDER BY MTCD_NR_COVERAGE_VAL DESC NULLS LAST) AS MTCV_ID_VEHI_VAN,
                     MAX (MTCD_CD_VAN) KEEP (DENSE_RANK FIRST
                                             ORDER BY MTCD_NR_COVERAGE_VAL DESC NULLS LAST) MTCV_CD_VAN,
                                       MAX (TO_NUMBER (TO_CHAR (CALC_REQ_DT, 'J'))) KEEP (DENSE_RANK FIRST
                                                                                          ORDER BY MTCD_NR_COVERAGE_VAL DESC NULLS LAST) AS MTCV_ID_TIME_REQ_DT,
                                           MAX (CALC_REQ_DT) KEEP (DENSE_RANK FIRST
                                                                   ORDER BY MTCD_NR_COVERAGE_VAL DESC NULLS LAST) AS MTCV_DT_REQ_DT,
                                               MTCD_CD_PROD_LINE AS MTCV_CD_PROD_LINE,
                                               MAX (MTCD_CD_IND_ID) KEEP (DENSE_RANK FIRST
                                                                          ORDER BY MTCD_NR_COVERAGE_VAL DESC NULLS LAST) AS MTCV_CD_IND_ID,
                                                   MAX (MTCD_CD_SALE_ORD_NBR) KEEP (DENSE_RANK FIRST
                                                                                    ORDER BY MTCD_NR_COVERAGE_VAL DESC NULLS LAST) AS MTCV_CD_SALE_ORD_NBR,
                                                       MAX (MTCD_CD_SALE_ORD_LN) KEEP (DENSE_RANK FIRST
                                                                                       ORDER BY MTCD_NR_COVERAGE_VAL DESC NULLS LAST) AS MTCV_CD_SALE_ORD_LN,
                                                           MAX (MTCD_CD_SCHED_LN_ID) KEEP (DENSE_RANK FIRST
                                                                                           ORDER BY MTCD_NR_COVERAGE_VAL DESC NULLS LAST) AS MTCV_CD_SCHED_LN_ID,
                                                               MAX (MTCD_ID_MTRL_PART_NBR_IR) KEEP (DENSE_RANK FIRST
                                                                                                    ORDER BY MTCD_NR_COVERAGE_VAL DESC NULLS LAST) AS MTCV_ID_MTRL_PART_NBR_IR,
                                                                   MAX (MTCD_CD_PART_NBR_IR) KEEP (DENSE_RANK FIRST
                                                                                                   ORDER BY MTCD_NR_COVERAGE_VAL DESC NULLS LAST) AS MTCV_CD_PART_NBR_IR,
                                                                       MAX (MTCD_ID_CUST_CUST_CD) KEEP (DENSE_RANK FIRST
                                                                                                        ORDER BY MTCD_NR_COVERAGE_VAL DESC NULLS LAST) AS MTCV_ID_CUST_CUST_CD,
                                                                           MAX (MTCD_CD_CUST_CD) KEEP (DENSE_RANK FIRST
                                                                                                       ORDER BY MTCD_NR_COVERAGE_VAL DESC NULLS LAST) AS MTCV_CD_CUST_CD,
                                                                               MTCD_ID_MTRL_COMP AS MTCV_ID_MTRL_COMP,
                                                                               MTCD_CD_COMP AS MTCV_CD_COMP,
                                                                               MTCD_CD_VAN_STU AS MTCV_CD_VAN_STU,
                                                                               SUM (MTCD_QT_BOM_QTY) AS MTCV_QT_BOM_QTY,
                                                                                   SUM (MTCD_QT_CONSUMED_QTY) AS MTCV_QT_CONSUMED_QTY,
                                                                                       SUM (MTCD_QT_MOUNTED_QTY) AS MTCV_QT_MOUNTED_QTY,
                                                                                           MTCD_CD_COMP_PROCUR_TP AS MTCV_CD_COMP_PROCUR_TP,
                                                                                           MTCD_CD_COMP_ASS_MARK AS MTCV_CD_COMP_ASS_MARK,
                                                                                           MTCD_ID_VEND_SUPPL_CD AS MTCV_ID_VEND_SUPPL_CD,
                                                                                           MTCD_CD_SUPPL_CD AS MTCV_CD_SUPPL_CD,
                                                                                           MAX (MTCD_QT_BACKLOG) KEEP (DENSE_RANK FIRST
                                                                                                                       ORDER BY MTCD_NR_COVERAGE_VAL DESC NULLS LAST) AS MTCV_QT_BACKLOG,
                                                                                               MTCD_QT_CONS_QTY AS MTCV_QT_CONS_QTY,
                                                                                               MTCD_QT_PROM_QTY AS MTCV_QT_PROM_QTY,
                                                                                               MTCD_QT_ASN_QTY AS MTCV_QT_ASN_QTY,
                                                                                               MTCD_QT_INB_QTY AS MTCV_QT_INB_QTY,
                                                                                               MTCD_CD_AGING_CAT_INB AS MTCV_CD_AGING_CAT_INB,
                                                                                               MTCD_QT_QUALITY_AREA_QTY AS MTCV_QT_QUALITY_AREA_QTY,
                                                                                               MTCD_CD_AGING_CAT_QLTY_AREA AS MTCV_CD_AGING_CAT_QLTY_AREA,
                                                                                               MTCD_QT_DEC_AREA_QTY AS MTCV_QT_DEC_AREA_QTY,
                                                                                               MTCD_CD_AGING_CAT_DEC_AREA AS MTCV_CD_AGING_CAT_DEC_AREA,
                                                                                               MTCD_QT_EXT_QTY AS MTCV_QT_EXT_QTY,
                                                                                               MTCD_CD_AGING_CAT_EXT AS MTCV_CD_AGING_CAT_EXT,
                                                                                               MTCD_QT_OTHER_CLICK_QTY AS MTCV_QT_OTHER_CLICK_QTY,
                                                                                               MTCD_CD_AGING_CAT_OTHER AS MTCV_CD_AGING_CAT_OTHER,
                                                                                               MTCD_QT_WIP_LN_QTY AS MTCV_QT_WIP_LN_QTY,
                                                                                               MTCD_QT_WIP_HARD_QTY AS MTCV_QT_WIP_HARD_QTY,
                                                                                               MTCD_QT_MOUNT_QTY AS MTCV_QT_MOUNT_QTY,
                                                                                               MTCD_NT_MOUNT_COMP_PATH AS MTCV_NT_MOUNT_COMP_PATH,
                                                                                               MTCD_QT_STOCK_QTY AS MTCV_QT_STOCK_QTY,
                                                                                               MTCD_CD_AGING_CAT_STOCK AS MTCV_CD_AGING_CAT_STOCK,
                                                                                               MTCD_QT_W999_QTY AS MTCV_QT_W999_QTY,
                                                                                               SUM (MTCD_QT_MISS_QTY) AS MTCV_QT_MISS_QTY,
                                                                                                   MAX (MTCD_QT_CALC_MISS_QTY) KEEP (DENSE_RANK FIRST
                                                                                                                                     ORDER BY MTCD_NR_COVERAGE_VAL DESC NULLS LAST) AS MTCV_QT_CALC_MISS_QTY,
                                                                                                       MAX (MTCD_QT_CALC_MISS_QTY_PROM) KEEP (DENSE_RANK FIRST
                                                                                                                                              ORDER BY MTCD_NR_COVERAGE_VAL DESC NULLS LAST) AS MTCV_QT_CALC_MISS_QTY_PROM,
                                                                                                           SUM (MTCD_QT_REQ_QTY) AS MTCV_QT_REQ_QTY,
                                                                                                               MAX (MTCD_QT_REQ_PROG_QTY) AS MTCV_QT_REQ_PROG_QTY,
                                                                                                                   MAX (MTCD_ID_COVC_COVERAGE_CD) KEEP (DENSE_RANK FIRST
                                                                                                                                                        ORDER BY MTCD_NR_COVERAGE_VAL DESC NULLS LAST) AS MTCV_ID_COVC_COVERAGE_CD,
                                                                                                                       MAX (MTCD_CD_COVERAGE_CD) KEEP (DENSE_RANK FIRST
                                                                                                                                                       ORDER BY MTCD_NR_COVERAGE_VAL DESC NULLS LAST) AS MTCV_CD_COVERAGE_CD,
                                                                                                                           MAX (MTCD_NR_COVERAGE_VAL) KEEP (DENSE_RANK FIRST
                                                                                                                                                            ORDER BY MTCD_NR_COVERAGE_VAL DESC NULLS LAST) AS MTCV_NR_COVERAGE_VAL,
                                                                                                                               SUM (MTCD_QT_COVERAGE_QTY) KEEP (DENSE_RANK FIRST
                                                                                                                                                                ORDER BY MTCD_NR_COVERAGE_VAL DESC NULLS LAST) AS MTCV_QT_COVERAGE_QTY,
                                                                                                                                   MAX (MTCD_ID_COVC_COVERAGE_PROM) KEEP (DENSE_RANK FIRST
                                                                                                                                                                          ORDER BY MTCD_NR_COVERAGE_VAL DESC NULLS LAST) AS MTCV_ID_COVC_COVERAGE_PROM,
                                                                                                                                       MAX (MTCD_CD_COVERAGE_PROM) KEEP (DENSE_RANK FIRST
                                                                                                                                                                         ORDER BY MTCD_NR_COVERAGE_VAL DESC NULLS LAST) AS MTCV_CD_COVERAGE_PROM,
                                                                                                                                           MAX (MTCD_NR_COVERAGE_VAL_PROM) KEEP (DENSE_RANK FIRST
                                                                                                                                                                                 ORDER BY MTCD_NR_COVERAGE_VAL DESC NULLS LAST) AS MTCV_NR_COVERAGE_VAL_PROM,
                                                                                                                                               SUM (MTCD_QT_COVERAGE_QTY_PROM) KEEP (DENSE_RANK FIRST
                                                                                                                                                                                     ORDER BY MTCD_NR_COVERAGE_VAL DESC NULLS LAST) AS MTCV_QT_COVERAGE_QTY_PROM,
                                                                                                                                                   MTCD_NR_WST_COV_VAL AS MTCV_NR_WST_COV_VAL,
                                                                                                                                                   MTCD_QT_WST_COV_QTY AS MTCV_QT_WST_COV_QTY,
                                                                                                                                                   MTCD_ID_TIME_WST_COV AS MTCV_ID_TIME_WST_COV,
                                                                                                                                                   MTCD_NR_WST_COV_VAL_PROM AS MTCV_NR_WST_COV_VAL_PROM,
                                                                                                                                                   MTCD_QT_WST_COV_QTY_PROM AS MTCV_QT_WST_COV_QTY_PROM,
                                                                                                                                                   MTCD_ID_TIME_WST_COV_PROM AS MTCV_ID_TIME_WST_COV_PROM,
                                                                                                                                                   MTCD_FL_STOP_MARK AS MTCV_FL_STOP_MARK,
                                                                                                                                                   MTCD_FL_PROM_MARK AS MTCV_FL_PROM_MARK,
                                                                                                                                                   MTCD_FL_CRITICAL_MARK AS MTCV_FL_CRITICAL_MARK,
                                                                                                                                                   MTCD_FL_MTO_MARK AS MTCV_FL_MTO_MARK,
                                                                                                                                                   MTCD_FL_LEAF_COMP_MARK AS MTCV_FL_LEAF_COMP_MARK,
                                                                                                                                                   MAX (MTCD_FL_SEQ_LIST_MARK) KEEP (DENSE_RANK FIRST
                                                                                                                                                                                     ORDER BY MTCD_NR_COVERAGE_VAL DESC NULLS LAST) AS MTCV_FL_SEQ_LIST_MARK,
                                                                                                                                                       MAX (MTCD_FL_CALC_MISS_MARK) KEEP (DENSE_RANK FIRST
                                                                                                                                                                                          ORDER BY MTCD_NR_COVERAGE_VAL DESC NULLS LAST) AS MTCV_FL_CALC_MISS_MARK,
                                                                                                                                                           MAX (MTCD_FL_CALC_MISS_PROM_MARK) KEEP (DENSE_RANK FIRST
                                                                                                                                                                                                   ORDER BY MTCD_NR_COVERAGE_VAL DESC NULLS LAST) AS MTCV_FL_CALC_MISS_PROM_MARK,
                                                                                                                                                               MAX (MTCD_FL_MISS_MARK) KEEP (DENSE_RANK FIRST
                                                                                                                                                                                             ORDER BY MTCD_NR_COVERAGE_VAL DESC NULLS LAST) AS MTCV_FL_MISS_MARK,
                                                                                                                                                                   MAX (MTCD_CD_SOURCE_SYSTEM) AS MTCV_CD_SOURCE_SYSTEM
      FROM
        (SELECT MTCD.*,
                CASE
                    WHEN MTCD_DT_REQ_DT <= TRUNC (TO_DATE (P_ELT_DT_JOB_DATE_ELAB, 'YYYYMMDD') +13, 'IW') +6 THEN MTCD_DT_REQ_DT
                    ELSE TRUNC (MTCD_DT_REQ_DT, 'IW')
                END CALC_REQ_DT,
                CASE
                    WHEN MTCD_CD_VAN_STU = 'PLANNED'
                         OR MTCD_CD_REQ_CAT <> 'VH' THEN CASE
                                                             WHEN MTCD_DT_REQ_DT <= TRUNC (TO_DATE (P_ELT_DT_JOB_DATE_ELAB, 'YYYYMMDD') +13, 'IW') +6 THEN MTCD_DT_REQ_DT
                                                             ELSE TRUNC (MTCD_DT_REQ_DT, 'IW')
                                                         END
                    ELSE NULL
                END DT_REQ_DT_FUTURE
         FROM DDWH02_DM_MA.TFCT_MTCD_MAT_COVERAGE_DET MTCD
         WHERE MTCD_CD_PLANT_CD =P_ELT_CD_PLANT
           AND MTCD_NR_TIME_TP_INDIC = 0 )
      GROUP BY MTCD_ID_REQU_REQ_CAT,
               MTCD_CD_REQ_CAT,
               MTCD_ID_MTRL_COMP,
               MTCD_CD_COMP,
               MTCD_CD_VAN_STU,
               DT_REQ_DT_FUTURE,
               MTCD_CD_PROD_LINE,
               MTCD_CD_COMP_PROCUR_TP,
               MTCD_CD_COMP_ASS_MARK,
               MTCD_ID_VEND_SUPPL_CD,
               MTCD_CD_SUPPL_CD,
               MTCD_QT_CONS_QTY,
               MTCD_QT_PROM_QTY,
               MTCD_QT_INB_QTY,
               MTCD_QT_QUALITY_AREA_QTY,
               MTCD_QT_DEC_AREA_QTY,
               MTCD_QT_EXT_QTY,
               MTCD_QT_OTHER_CLICK_QTY,
               MTCD_QT_WIP_LN_QTY,
               MTCD_QT_WIP_HARD_QTY,
               MTCD_QT_MOUNT_QTY,
               MTCD_QT_STOCK_QTY,
               MTCD_QT_W999_QTY,
               MTCD_QT_ASN_QTY,
               MTCD_CD_AGING_CAT_INB,
               MTCD_CD_AGING_CAT_QLTY_AREA,
               MTCD_CD_AGING_CAT_DEC_AREA,
               MTCD_CD_AGING_CAT_EXT,
               MTCD_CD_AGING_CAT_OTHER,
               MTCD_NT_MOUNT_COMP_PATH,
               MTCD_CD_AGING_CAT_STOCK,
               MTCD_NR_WST_COV_VAL,
               MTCD_QT_WST_COV_QTY,
               MTCD_ID_TIME_WST_COV,
               MTCD_NR_WST_COV_VAL_PROM,
               MTCD_QT_WST_COV_QTY_PROM,
               MTCD_ID_TIME_WST_COV_PROM,
               MTCD_FL_MTO_MARK,
               MTCD_FL_LEAF_COMP_MARK,
               MTCD_CD_PLANT_CD,
               MTCD_FL_STOP_MARK,
               MTCD_FL_PROM_MARK,
               MTCD_FL_CRITICAL_MARK)) QRY