INSERT INTO DDWH02_DM_MA.TW_MCMW_MC_MAT_COVERAGE_WORK (MCMW_CD_PLANT_CD, MCMW_ID_MCMW, MCMW_ID_REQU_REQ_CAT, MCMW_CD_REQ_CAT, MCMW_ID_VEHI_VAN, MCMW_CD_VAN, MCMW_ID_TIME_REQ_DT, MCMW_DT_REQ_DT, MCMW_ID_TIME_REQ_DT_LT, MCMW_DT_REQ_DT_LT, MCMW_ID_TIME_PLND_INLINE_DT, MCMW_DT_PLND_INLINE_DT, MCMW_ID_TIME_INLINE_DT, MCMW_DT_INLINE_DT, MCMW_CD_PROD_LINE, MCMW_CD_VEHI_STU, MCMW_CD_SERIE, MCMW_NR_SEQ_NBR, MCMW_CD_IND_ID, MCMW_CD_SALE_ORD_NBR, MCMW_CD_SALE_ORD_LN, MCMW_CD_SCHED_LN_ID, MCMW_ID_MTRL_PART_NBR_IR, MCMW_CD_PART_NBR_IR, MCMW_ID_CUST_CUST_CD, MCMW_CD_CUST_CD, MCMW_ID_TIME_EXPL_DT, MCMW_DT_EXPL_DT, MCMW_ID_MAMD_MAT_MASTER, MCMW_ID_MTRL_COMP, MCMW_CD_COMP, MCMW_CD_PROCUR_TP, MCMW_CD_COMP_ASS_MARK, MCMW_ID_VEND_SUPPL_CD, MCMW_CD_SUPPL_CD, MCMW_FL_LEAF_COMP_MARK, MCMW_QT_COMP_QTY, MCMW_QT_COMP_QTY_CONS, MCMW_QT_COMP_QTY_MNT, MCMW_QT_COMP_QTY_MNT_LT, MCMW_QT_COMP_QTY_REQ, MCMW_QT_COMP_QTY_REQ_LT, MCMW_QT_COMP_QTY_REQ_PROG, MCMW_QT_COMP_QTY_REQ_PROG_LT, MCMW_QT_MIN_LEAD_TIME, MCMW_QT_MAX_LEAD_TIME, MCMW_QT_CONS_QTY, MCMW_NR_AGING_CONS_QTY, MCMW_QT_INB_QTY, MCMW_NR_AGING_INB_QTY, MCMW_QT_QUALITY_AREA_QTY, MCMW_NR_AGING_QTY_AREA_QTY, MCMW_QT_DEC_QTY, MCMW_NR_AGING_DEC_QTY, MCMW_QT_AVAILABLE_QTY, MCMW_NR_AGING_AVAILABLE_QTY, MCMW_QT_EXT_QTY, MCMW_NR_AGING_EXT_QTY, MCMW_QT_OTHERS_QTY, MCMW_NR_AGING_OTHERS_QTY, MCMW_QT_WIP_LN_QTY, MCMW_QT_WIP_HARD_QTY, MCMW_QT_W999_QTY, MCMW_QT_TOT_STOCK_QTY, MCMW_QT_MOUNT_QTY, MCMW_NT_MOUNT_COMP_PATH, MCMW_QT_PROM_QTY, MCMW_QT_TOT_PROM_QTY, MCMW_ID_PLNT_VENDORS, MCMW_CD_PLNT_VENDOR_CD, MCMW_ID_MASP_VEND_SUPPL_CD, MCMW_CD_MASP_SUPPL_CD, MCMW_QT_MIDE_MISS_QTY, MCMW_QT_BKPM_REM_QTY, MCMW_QT_BARE_SCLN_REM_REQ_QTY, MCMW_QT_BACKLOG, MCMW_CD_INB_AGING_CAT, MCMW_CD_QLTY_AGING_CAT, MCMW_CD_DECA_AGING_CAT, MCMW_CD_EXT_AGING_CAT, MCMW_CD_OTHER_AGING_CAT, MCMW_CD_STK_AGING_CAT, MCMW_FL_MTO_MARK, MCMW_FL_SEQ_LIST_MARK, MCMW_ID_BATCH_ID, MCMW_CD_SOURCE_SYSTEM, MCMW_CD_OPERATOR_CODE, MCMW_DT_INS_ROW, MCMW_DT_UPD_ROW) WITH TW_PROMISE AS
  (SELECT X.CD_PLANT,
          X.PART_NBR,
          X.TIME_DT_DAY AS DT_DAY,
          NVL (SUM (EXPR_QT_PROM_QTY) OVER (PARTITION BY X.CD_PLANT, X.PART_NBR
                                            ORDER BY X.TIME_DT_DAY ASC NULLS FIRST) , 0) AS QT_PROM_QTY,
          NVL (SUM (EXPR_QT_PROM_QTY) OVER (PARTITION BY X.CD_PLANT, X.PART_NBR) , 0) AS TOT_QT_PROM_QTY
   FROM
     (SELECT EXPR_CD_PART_NBR,
             EXPR_DT_PROM_DT,
             SUM (EXPR_QT_PROM_QTY) EXPR_QT_PROM_QTY
      FROM DDWH01_DW_MA.TT_EXPR_EXP_PROM_RCPT
      WHERE EXPR_CD_PLANT_CD=P_ELT_CD_PLANT
        AND EXPR_FL_LOGICAL_STATUS='1'
        AND EXPR_DT_PROM_DT>=TO_DATE (P_ELT_DT_JOB_DATE_ELAB, 'YYYYMMDD')
      GROUP BY EXPR_CD_PART_NBR,
               EXPR_DT_PROM_DT) ,
     (SELECT DISTINCT EXPR_CD_PLANT_CD CD_PLANT,
                      EXPR_CD_PART_NBR PART_NBR,
                      TIME_DT_DAY,
                      TIME_ID_TIME
      FROM DDWH01_DW_MA.TT_EXPR_EXP_PROM_RCPT,
           DDWH02_DM_MA.TDIM_TIME_TIME
      WHERE EXPR_CD_PLANT_CD=P_ELT_CD_PLANT
        AND EXPR_FL_LOGICAL_STATUS = '1'
        AND EXPR_DT_PROM_DT>=TO_DATE (P_ELT_DT_JOB_DATE_ELAB, 'YYYYMMDD')
        AND TIME_DT_DAY BETWEEN TO_DATE (P_ELT_DT_JOB_DATE_ELAB, 'YYYYMMDD') AND TO_DATE (P_ELT_DT_JOB_DATE_ELAB, 'YYYYMMDD') +TO_NUMBER (P_DAY_TIMELINE) ) X
   WHERE EXPR_CD_PART_NBR (+) =X.PART_NBR
     AND EXPR_DT_PROM_DT (+) =X.TIME_DT_DAY )
SELECT MCMW_CD_PLANT_CD,
       0 AS MCMW_ID_MCMW,
       MCMW_ID_REQU_REQ_CAT,
       MCMW_CD_REQ_CAT,
       MCMW_ID_VEHI_VAN,
       MCMW_CD_VAN,
       MCMW_ID_TIME_REQ_DT,
       MCMW_DT_REQ_DT,
       MCMW_ID_TIME_REQ_DT_LT,
       MCMW_DT_REQ_DT_LT,
       MCMW_ID_TIME_PLND_INLINE_DT,
       MCMW_DT_PLND_INLINE_DT,
       MCMW_ID_TIME_INLINE_DT,
       MCMW_DT_INLINE_DT,
       MCMW_CD_PROD_LINE,
       MCMW_CD_VEHI_STU,
       MCMW_CD_SERIE,
       MCMW_NR_SEQ_NBR,
       MCMW_CD_IND_ID,
       MCMW_CD_SALE_ORD_NBR,
       MCMW_CD_SALE_ORD_LN,
       MCMW_CD_SCHED_LN_ID,
       MCMW_ID_MTRL_PART_NBR_IR,
       MCMW_CD_PART_NBR_IR,
       MCMW_ID_CUST_CUST_CD,
       MCMW_CD_CUST_CD,
       MCMW_ID_TIME_EXPL_DT,
       MCMW_DT_EXPL_DT,
       MCMW_ID_MAMD_MAT_MASTER,
       MCMW_ID_MTRL_COMP,
       MCMW_CD_COMP,
       MCMW_CD_PROCUR_TP,
       MCMW_CD_COMP_ASS_MARK,
       MCMW_ID_VEND_SUPPL_CD,
       MCMW_CD_SUPPL_CD,
       MCMW_FL_LEAF_COMP_MARK,
       MCMW_QT_COMP_QTY,
       MCMW_QT_COMP_QTY_CONS,
       MCMW_QT_COMP_QTY_MNT,
       MCMW_QT_COMP_QTY_MNT_LT,
       MCMW_QT_COMP_QTY_REQ,
       MCMW_QT_COMP_QTY_REQ_LT,
       MCMW_QT_COMP_QTY_REQ_PROG,
       MCMW_QT_COMP_QTY_REQ_PROG_LT,
       MCMW_QT_MIN_LEAD_TIME,
       MCMW_QT_MAX_LEAD_TIME,
       MCMW_QT_CONS_QTY,
       MCMW_NR_AGING_CONS_QTY,
       MCMW_QT_INB_QTY,
       MCMW_NR_AGING_INB_QTY,
       MCMW_QT_QUALITY_AREA_QTY,
       MCMW_NR_AGING_QTY_AREA_QTY,
       MCMW_QT_DEC_QTY,
       MCMW_NR_AGING_DEC_QTY,
       MCMW_QT_AVAILABLE_QTY,
       MCMW_NR_AGING_AVAILABLE_QTY,
       MCMW_QT_EXT_QTY,
       MCMW_NR_AGING_EXT_QTY,
       MCMW_QT_OTHERS_QTY,
       MCMW_NR_AGING_OTHERS_QTY,
       MCMW_QT_WIP_LN_QTY,
       MCMW_QT_WIP_HARD_QTY,
       MCMW_QT_W999_QTY,
       MCMW_QT_TOT_STOCK_QTY,
       MCMW_QT_MOUNT_QTY,
       MCMW_NT_MOUNT_COMP_PATH,
       MCMW_QT_PROM_QTY,
       MCMW_QT_TOT_PROM_QTY,
       MCMW_ID_PLNT_VENDORS,
       MCMW_CD_PLNT_VENDOR_CD,
       MCMW_ID_MASP_VEND_SUPPL_CD,
       MCMW_CD_MASP_SUPPL_CD,
       MCMW_QT_MIDE_MISS_QTY,
       MCMW_QT_BKPM_REM_QTY,
       MCMW_QT_BARE_SCLN_REM_REQ_QTY,
       MCMW_QT_BACKLOG,
       MCMW_CD_INB_AGING_CAT,
       MCMW_CD_QLTY_AGING_CAT,
       MCMW_CD_DECA_AGING_CAT,
       MCMW_CD_EXT_AGING_CAT,
       MCMW_CD_OTHER_AGING_CAT,
       MCMW_CD_STK_AGING_CAT,
       MCMW_FL_MTO_MARK,
       CASE
           WHEN SQLP_CD_PART_NBR IS NOT NULL THEN '1'
           ELSE '0'
       END MCMW_FL_SEQ_LIST_MARK,
       NVL (P_ELT_ID_BATCH, N_ELT_ID_JOB_LOG) AS MCMW_ID_BATCH_ID,
       'MA' AS MCMW_CD_SOURCE_SYSTEM,
       'ETL' AS MCMW_CD_OPERATOR_CODE,
       SYSDATE AS MCMW_DT_INS_ROW,
       SYSDATE AS MCMW_DT_UPD_ROW
FROM
  (SELECT MCMC_CD_PLANT_CD AS MCMW_CD_PLANT_CD,
          NVL (MCMC_ID_REQU_REQ_CAT, -2) AS MCMW_ID_REQU_REQ_CAT,
          MCMC_CD_REQ_CAT AS MCMW_CD_REQ_CAT,
          NVL (MCMC_ID_VEHI_VAN, -2) AS MCMW_ID_VEHI_VAN,
          MCMC_CD_VAN AS MCMW_CD_VAN,
          NVL (TO_NUMBER (TO_CHAR (MCMC_DT_REQ_DT, 'J')), -2) AS MCMW_ID_TIME_REQ_DT,
          MCMC_DT_REQ_DT AS MCMW_DT_REQ_DT,
          NVL (TO_NUMBER (TO_CHAR (MCMC_DT_REQ_DT_LT, 'J')), -2) AS MCMW_ID_TIME_REQ_DT_LT,
          MCMC_DT_REQ_DT_LT AS MCMW_DT_REQ_DT_LT,
          NVL (TO_NUMBER (TO_CHAR (MCMC_DT_PLND_INLINE_DT, 'J')), -2) AS MCMW_ID_TIME_PLND_INLINE_DT,
          MCMC_DT_PLND_INLINE_DT AS MCMW_DT_PLND_INLINE_DT,
          NVL (TO_NUMBER (TO_CHAR (MCMC_DT_INLINE_DT, 'J')), -2) AS MCMW_ID_TIME_INLINE_DT,
          MCMC_DT_INLINE_DT AS MCMW_DT_INLINE_DT,
          MCMC_CD_PROD_LINE AS MCMW_CD_PROD_LINE,
          MCMC_CD_VEHI_STU AS MCMW_CD_VEHI_STU,
          MCMC_CD_SERIE AS MCMW_CD_SERIE,
          MCMC_NR_SEQ_NBR AS MCMW_NR_SEQ_NBR,
          MCMC_CD_IND_ID AS MCMW_CD_IND_ID,
          MCMC_CD_SALE_ORD_NBR AS MCMW_CD_SALE_ORD_NBR,
          MCMC_CD_SALE_ORD_LN AS MCMW_CD_SALE_ORD_LN,
          MCMC_CD_SCHED_LN_ID AS MCMW_CD_SCHED_LN_ID,
          NVL (MCMC_ID_MTRL_PART_NBR_IR, -2) AS MCMW_ID_MTRL_PART_NBR_IR,
          MCMC_CD_PART_NBR_IR AS MCMW_CD_PART_NBR_IR,
          NVL (MCMC_ID_CUST_CUST_CD, -2) AS MCMW_ID_CUST_CUST_CD,
          MCMC_CD_CUST_CD AS MCMW_CD_CUST_CD,
          NVL (TO_NUMBER (TO_CHAR (MCMC_DT_EXPL_DT, 'J')), -2) AS MCMW_ID_TIME_EXPL_DT,
          MCMC_DT_EXPL_DT AS MCMW_DT_EXPL_DT,
          NVL (MAMD_ID_MAT_MASTER, -2) AS MCMW_ID_MAMD_MAT_MASTER,
          NVL (MCMC_ID_MTRL_COMP, -2) AS MCMW_ID_MTRL_COMP,
          MCMC_CD_COMP AS MCMW_CD_COMP,
          MCMC_CD_PROCUR_TP AS MCMW_CD_PROCUR_TP,
          MCMC_CD_COMP_ASS_MARK AS MCMW_CD_COMP_ASS_MARK,
          NVL (CASE
                   WHEN MCMC_CD_PROCUR_TP IN ('BUY', 'SUBCONTRACTING') THEN MASP_ID_VEND_SUPPL_CD
                   WHEN MCMC_CD_PROCUR_TP IN ('MTS', 'MTO') THEN PLNT_ID_VENDORS
               END, -2) AS MCMW_ID_VEND_SUPPL_CD,
          NVL (CASE
                   WHEN MCMC_CD_PROCUR_TP IN ('BUY', 'SUBCONTRACTING') THEN MASP_CD_SUPPL_CD
                   WHEN MCMC_CD_PROCUR_TP IN ('MTS', 'MTO') THEN PLNT_CD_VENDOR_CD
               END, DDWH02_DM_MA.FUNC_NOT_APPLICABLE_CODE ()) AS MCMW_CD_SUPPL_CD,
          MCMC_FL_LEAF_COMP_MARK AS MCMW_FL_LEAF_COMP_MARK,
          MCMC_QT_COMP_QTY AS MCMW_QT_COMP_QTY,
          MCMC_QT_COMP_QTY_CONS AS MCMW_QT_COMP_QTY_CONS,
          MCMC_QT_COMP_QTY_MNT AS MCMW_QT_COMP_QTY_MNT,
          MCMC_QT_COMP_QTY_MNT_LT AS MCMW_QT_COMP_QTY_MNT_LT,
          MCMC_QT_COMP_QTY_REQ AS MCMW_QT_COMP_QTY_REQ,
          MCMC_QT_COMP_QTY_REQ_LT AS MCMW_QT_COMP_QTY_REQ_LT,
          MCMC_QT_COMP_QTY_REQ_PROG AS MCMW_QT_COMP_QTY_REQ_PROG,
          MCMC_QT_COMP_QTY_REQ_PROG_LT AS MCMW_QT_COMP_QTY_REQ_PROG_LT,
          MCMC_QT_MIN_LEAD_TIME AS MCMW_QT_MIN_LEAD_TIME,
          MCMC_QT_MAX_LEAD_TIME AS MCMW_QT_MAX_LEAD_TIME,
          NVL (MCST_QT_CONS_QTY, 0) AS MCMW_QT_CONS_QTY,
          MCST_NR_AGING_CONS_QTY AS MCMW_NR_AGING_CONS_QTY,
          NVL (MCST_QT_INB_QTY, 0) AS MCMW_QT_INB_QTY,
          MCST_NR_AGING_INB_QTY AS MCMW_NR_AGING_INB_QTY,
          NVL (MCST_QT_QUALITY_AREA_QTY, 0) AS MCMW_QT_QUALITY_AREA_QTY,
          MCST_NR_AGING_QTY_AREA_QTY AS MCMW_NR_AGING_QTY_AREA_QTY,
          NVL (MCST_QT_DEC_QTY, 0) AS MCMW_QT_DEC_QTY,
          MCST_NR_AGING_DEC_QTY AS MCMW_NR_AGING_DEC_QTY,
          NVL (MCST_QT_AVAILABLE_QTY, 0) AS MCMW_QT_AVAILABLE_QTY,
          MCST_NR_AGING_AVAILABLE_QTY AS MCMW_NR_AGING_AVAILABLE_QTY,
          NVL (MCST_QT_EXT_QTY, 0) AS MCMW_QT_EXT_QTY,
          MCST_NR_AGING_EXT_QTY AS MCMW_NR_AGING_EXT_QTY,
          NVL (MCST_QT_OTHERS_QTY, 0) AS MCMW_QT_OTHERS_QTY,
          MCST_NR_AGING_OTHERS_QTY AS MCMW_NR_AGING_OTHERS_QTY,
          NVL (MCST_QT_WIP_LN_QTY, 0) AS MCMW_QT_WIP_LN_QTY,
          NVL (MCST_QT_WIP_HARD_QTY, 0) AS MCMW_QT_WIP_HARD_QTY,
          NVL (MCST_QT_W999_QTY, 0) AS MCMW_QT_W999_QTY,
          NVL (MCST_QT_TOT_STOCK_QTY, 0) AS MCMW_QT_TOT_STOCK_QTY,
          NVL (MCST_QT_MOUNT_QTY, 0) AS MCMW_QT_MOUNT_QTY,
          MCST_NT_MOUNT_COMP_PATH AS MCMW_NT_MOUNT_COMP_PATH,
          NVL (TW_PROMISE.QT_PROM_QTY, 0) AS MCMW_QT_PROM_QTY,
          NVL (TW_PROMISE.TOT_QT_PROM_QTY, 0) AS MCMW_QT_TOT_PROM_QTY,
          NVL (PLNT_ID_VENDORS, -2) AS MCMW_ID_PLNT_VENDORS,
          PLNT_CD_VENDOR_CD AS MCMW_CD_PLNT_VENDOR_CD,
          NVL (MASP_ID_VEND_SUPPL_CD, -2) AS MCMW_ID_MASP_VEND_SUPPL_CD,
          MASP_CD_SUPPL_CD AS MCMW_CD_MASP_SUPPL_CD,
          NVL (MIDE_QT_MISS_QTY, 0) AS MCMW_QT_MIDE_MISS_QTY,
          NVL (BKPM_QT_REM_QTY, 0) AS MCMW_QT_BKPM_REM_QTY,
          NVL (BARE_QT_SCLN_REM_REQ_QTY, 0) AS MCMW_QT_BARE_SCLN_REM_REQ_QTY,
          NVL (CASE
                   WHEN MCMC_CD_PROCUR_TP IN ('BUY', 'SUBCONTRACTING') THEN BARE_QT_SCLN_REM_REQ_QTY
                   WHEN MCMC_CD_PROCUR_TP IN ('MTS', 'MTO') THEN BKPM_QT_REM_QTY
                   ELSE 0
               END, 0) AS MCMW_QT_BACKLOG,
          NVL (
                 (SELECT MCAC_CD_AGING_CAT
                  FROM DDWH02_DM_MA.TW_MCAC_MC_AGING_CAT_CLICK
                  WHERE MCAC_CD_PLANT_CD=P_ELT_CD_PLANT
                    AND MCAC_NR_AG_MIN_INB IS NOT NULL
                    AND MCST_NR_AGING_INB_QTY BETWEEN NVL (MCAC_NR_AG_MIN_INB, 0) AND NVL (MCAC_NR_AG_MAX_INB, 9999) ) , '00') AS MCMW_CD_INB_AGING_CAT,
          NVL (
                 (SELECT MCAC_CD_AGING_CAT
                  FROM DDWH02_DM_MA.TW_MCAC_MC_AGING_CAT_CLICK
                  WHERE MCAC_CD_PLANT_CD=P_ELT_CD_PLANT
                    AND MCAC_NR_AG_MIN_QLTY_AREA IS NOT NULL
                    AND MCST_NR_AGING_QTY_AREA_QTY BETWEEN NVL (MCAC_NR_AG_MIN_QLTY_AREA, 0) AND NVL (MCAC_NR_AG_MAX_QLTY_AREA, 9999) ) , '00') AS MCMW_CD_QLTY_AGING_CAT,
          NVL (
                 (SELECT MCAC_CD_AGING_CAT
                  FROM DDWH02_DM_MA.TW_MCAC_MC_AGING_CAT_CLICK
                  WHERE MCAC_CD_PLANT_CD=P_ELT_CD_PLANT
                    AND MCAC_NR_AG_MIN_DEC_AREA IS NOT NULL
                    AND MCST_NR_AGING_DEC_QTY BETWEEN NVL (MCAC_NR_AG_MIN_DEC_AREA, 0) AND NVL (MCAC_NR_AG_MAX_DEC_AREA, 9999) ) , '00') AS MCMW_CD_DECA_AGING_CAT,
          NVL (
                 (SELECT MCAC_CD_AGING_CAT
                  FROM DDWH02_DM_MA.TW_MCAC_MC_AGING_CAT_CLICK
                  WHERE MCAC_CD_PLANT_CD=P_ELT_CD_PLANT
                    AND MCAC_NR_AG_MIN_EXT IS NOT NULL
                    AND MCST_NR_AGING_EXT_QTY BETWEEN NVL (MCAC_NR_AG_MIN_EXT, 0) AND NVL (MCAC_NR_AG_MAX_EXT, 9999) ) , '00') AS MCMW_CD_EXT_AGING_CAT,
          NVL (
                 (SELECT MCAC_CD_AGING_CAT
                  FROM DDWH02_DM_MA.TW_MCAC_MC_AGING_CAT_CLICK
                  WHERE MCAC_CD_PLANT_CD=P_ELT_CD_PLANT
                    AND MCAC_NR_AG_MIN_OTHER IS NOT NULL
                    AND MCST_NR_AGING_OTHERS_QTY BETWEEN NVL (MCAC_NR_AG_MIN_OTHER, 0) AND NVL (MCAC_NR_AG_MAX_OTHER, 9999) ) , '00') AS MCMW_CD_OTHER_AGING_CAT,
          NVL (
                 (SELECT MCAC_CD_AGING_CAT
                  FROM DDWH02_DM_MA.TW_MCAC_MC_AGING_CAT_CLICK
                  WHERE MCAC_CD_PLANT_CD=P_ELT_CD_PLANT
                    AND MCAC_NR_AG_MIN_STOCK IS NOT NULL
                    AND MCST_NR_AGING_AVAILABLE_QTY BETWEEN NVL (MCAC_NR_AG_MIN_STOCK, 0) AND NVL (MCAC_NR_AG_MAX_STOCK, 9999) ) , '00') AS MCMW_CD_STK_AGING_CAT,
          CASE
              WHEN MCMC_CD_PROCUR_TP IN ('MTO')
                   AND MCMC_CD_COMP_ASS_MARK='1' THEN '1'
              ELSE '0'
          END AS MCMW_FL_MTO_MARK
   FROM
     (SELECT *
      FROM DDWH02_DM_MA.TW_MCMC_MC_MTO_CONS
      WHERE MCMC_CD_PLANT_CD=P_ELT_CD_PLANT ) ,
     (SELECT *
      FROM DDWH02_DM_MA.TW_MCST_MC_STOCK_QTY
      WHERE MCST_CD_PLANT_CD=P_ELT_CD_PLANT ) , TW_PROMISE,

     (SELECT PLNT_CD_VENDOR_CD,
             VEND_ID_VENDORS AS PLNT_ID_VENDORS
      FROM
        (SELECT *
         FROM DDWH01_DW_MA.TM_PLNT_PLANT
         WHERE PLNT_CD_PLANT_CD=P_ELT_CD_PLANT ) ,
        (SELECT *
         FROM DDWH01_DW_MA.TM_VEND_VENDORS
         WHERE VEND_CD_PLANT_CD=P_ELT_CD_PLANT )
      WHERE PLNT_CD_VENDOR_CD=VEND_CD_VENDOR_CD ) PLNT,

     (SELECT MASP_CD_PART_NBR,
             MAX (MASP_CD_SUPPL_CD) KEEP (DENSE_RANK FIRST
                                          ORDER BY MASP_NR_QUOTE_PERC DESC NULLS LAST, MASP_CD_SUPPL_CD) MASP_CD_SUPPL_CD,
                                    MAX (MASP_ID_VEND_SUPPL_CD) KEEP (DENSE_RANK FIRST
                                                                      ORDER BY MASP_NR_QUOTE_PERC DESC NULLS LAST, MASP_CD_SUPPL_CD) MASP_ID_VEND_SUPPL_CD
      FROM DDWH01_DW_MA.TM_MASP_MAT_SUPP_REL
      WHERE MASP_CD_PLANT_CD=P_ELT_CD_PLANT
      GROUP BY MASP_CD_PART_NBR) MASP,

     (SELECT MIDE_CD_PART_NBR,
             MIDE_CD_VAN,
             SUM (MIDE_QT_QTY) MIDE_QT_MISS_QTY
      FROM DDWH01_DW_MA.TT_MIDE_MISS_DECL
      WHERE MIDE_CD_PLANT_CD=P_ELT_CD_PLANT
        AND MIDE_FL_LOGICAL_STATUS= '1'
        AND MIDE_FL_FIX_MARK = '0'
      GROUP BY MIDE_CD_PART_NBR,
               MIDE_CD_VAN) MIDE,

     (SELECT MAMD_ID_MAT_MASTER,
             MAMD_CD_PART_NBR
      FROM DDWH01_DW_MA.TM_MAMD_MAT_MASTER
      WHERE MAMD_CD_PLANT_CD=P_ELT_CD_PLANT ) MAMD,

     (SELECT BKPM_CD_MATERIAL,
             SUM (BKPM_QT_REM_QTY) AS BKPM_QT_REM_QTY
      FROM
        (SELECT ROW_NUMBER () OVER (PARTITION BY BKPM_CD_MATERIAL,
                                                 BKPM_CD_PROD_ORD
                                    ORDER BY BKPM_QT_REM_QTY DESC) AS BKPM_ROW_NUM,
                                   BKPM_CD_MATERIAL,
                                   BKPM_CD_PROD_ORD,
                                   BKPM_CD_OP,
                                   BKPM_ID_TIME_SNAPSHOT,
                                   BKPM_QT_REM_QTY
         FROM DDWH02_DM_MA.TFCT_BKPM_BACKLOG_PARTS
         WHERE BKPM_CD_PLANT_CD=P_ELT_CD_PLANT
           AND BKPM_FL_BACKLOG='1'
           AND BKPM_ID_TIME_SNAPSHOT=
             (SELECT LEAST (TO_NUMBER (TO_CHAR (TO_DATE (P_ELT_DT_JOB_DATE_ELAB, 'YYYYMMDD'), 'J')), MAX (BKPM_ID_TIME_SNAPSHOT))
              FROM DDWH02_DM_MA.TFCT_BKPM_BACKLOG_PARTS
              WHERE BKPM_CD_PLANT_CD=P_ELT_CD_PLANT ) )
      WHERE BKPM_ROW_NUM=1
      GROUP BY BKPM_CD_MATERIAL) BKPM,

     (SELECT BARE_CD_MATERIAL,
             SUM (BARE_QT_SCLN_REM_REQ_QTY) AS BARE_QT_SCLN_REM_REQ_QTY
      FROM DDWH02_DM_MA.TFCT_BARE_BACKLOG_RECEPTION
      WHERE BARE_CD_PLANT_CD=P_ELT_CD_PLANT
        AND BARE_ID_TIME_INV_DT=
          (SELECT LEAST (TO_NUMBER (TO_CHAR (TO_DATE (P_ELT_DT_JOB_DATE_ELAB, 'YYYYMMDD'), 'J')), MAX (BARE_ID_TIME_INV_DT))
           FROM DDWH02_DM_MA.TFCT_BARE_BACKLOG_RECEPTION
           WHERE BARE_CD_PLANT_CD=P_ELT_CD_PLANT )
      GROUP BY BARE_CD_MATERIAL) BARE
   WHERE MCMC_CD_COMP=MCST_CD_PART_NBR (+)
     AND MCMC_CD_COMP=TW_PROMISE.PART_NBR (+)
     AND GREATEST (MCMC_DT_REQ_DT, TRUNC (SYSDATE)) =TW_PROMISE.DT_DAY (+)
     AND MCMC_CD_COMP=MASP_CD_PART_NBR (+)
     AND MCMC_CD_COMP=MIDE_CD_PART_NBR (+)
     AND MCMC_CD_VAN=MIDE_CD_VAN (+)
     AND MCMC_CD_COMP=MAMD_CD_PART_NBR (+)
     AND MCMC_CD_COMP=BKPM.BKPM_CD_MATERIAL (+)
     AND MCMC_CD_COMP=BARE.BARE_CD_MATERIAL (+)
     AND (MCMC_CD_VEHI_STU <> 'FLEET'
          OR (MCMC_CD_VEHI_STU = 'FLEET'
              AND MIDE.MIDE_QT_MISS_QTY > 0)) ) ,
  (SELECT DISTINCT SQLM_CD_SUPPL_CD,
                   SQLP_CD_PART_NBR
   FROM DDWH01_DW_MA.TM_SQLM_SEQ_LIST_MASTER,
        DDWH01_DW_MA.TM_SQLP_SEQ_LIST_PART_NBR
   WHERE SQLM_ID_SEQ_LIST_MASTER=SQLP_ID_SQLM_SEQ_LIST_ID ) SL
WHERE MCMW_CD_SUPPL_CD=SL.SQLM_CD_SUPPL_CD (+)
  AND MCMW_CD_COMP=SL.SQLP_CD_PART_NBR (+)